# -*- coding: utf-8 -*-
"""Lo editorial de cada creencia: lo que hay que saber, con qué se confunde.

DE DONDE SALE
- «clave»: se saca de la DECLARACION misma, que esta transcrita literal de la
  cartilla. Son las listas y las frases exactas que un examen de texto
  especifico puede preguntar. Verificable contra fuente/cartilla.txt.
- «desarrollo»: los titulos de seccion con que el libro de las 28 creencias
  desarrolla el capitulo, sacados de la guia de estudio 2017 del mismo autor.
- «confunde»: con que otra creencia se cruza. Sale de la lista de las 28.
"""

# clave: [(pregunta, respuesta)] — se pintan como bloques que se revelan
# confunde: [(con cual, en que se diferencian)]
ED = {
1: dict(
  desarrollo=['La revelación divina','El foco de las Escrituras','El origen de las Escrituras',
              'La inspiración de las Escrituras','La autoridad de las Escrituras','La unidad de las Escrituras'],
  clave=[('La declaración cierra con CUATRO cosas que son las Escrituras. ¿Cuáles?',
          'Norma del carácter · criterio para evaluar la experiencia · revelación autorizada de las doctrinas · registro fidedigno de los actos de Dios'),
         ('¿Qué comunica Dios por medio de esta Palabra?',
          '«El conocimiento necesario para alcanzar la salvación»'),
         ('¿Cómo dice la declaración que se escribió la Biblia?',
          'Por hombres que «hablaron y escribieron impulsados por el Espíritu Santo». No dice que Dios dictó palabras: lo inspirado es la persona')],
  confunde=[(18,'La 1 es la Biblia. La 18 es el don de profecía, Elena de White. La Biblia es la norma que prueba al don, no al revés')]),
2: dict(
  desarrollo=['El conocimiento de Dios','La existencia de Dios','El Dios de las Escrituras',
              'La soberanía de Dios','La dinámica de la Deidad','Enfoque de la salvación'],
  clave=[('La frase que hay que saber exacta sobre las tres personas',
          '«Una unidad de tres personas coeternas». Un solo Dios, tres personas, y ninguna empezó después de otra'),
         ('¿Cuántos atributos enumera, y cuáles?',
          'Cinco: inmortal · todopoderoso · omnisapiente · superior a todos · omnipresente'),
         ('Si escapa a la comprensión humana, ¿cómo se lo puede conocer?',
          '«Por medio de su autorrevelación». No por razonamiento')],
  confunde=[(3,'La 2 habla de los tres juntos. De la 3 a la 5 va cada persona por separado')]),
3: dict(
  desarrollo=['Conceptos acerca del Padre','Dios el Padre en el Antiguo Testamento',
              'Dios el Padre en el Nuevo Testamento'],
  clave=[('Los CUATRO títulos del Padre',
          'Creador · Originador · Sustentador · Soberano de toda la creación'),
         ('Los seis rasgos de su carácter',
          'Justo · santo · misericordioso · clemente · tardo en airarse · abundante en amor y fidelidad. Salen casi palabra por palabra de Éxodo 34:6, 7'),
         ('¿Dónde más se manifiestan las cualidades del Padre?',
          '«También en el Hijo y en el Espíritu Santo». Es la frase que desarma la idea de un Padre severo y un Hijo bondadoso')],
  confunde=[(2,'La 2 es la Deidad completa; la 3 es solo el Padre')]),
4: dict(
  desarrollo=['La encarnación: predicciones y cumplimiento','Las dos naturalezas de Jesucristo',
              'La unión de las dos naturalezas','Los oficios de Cristo Jesús'],
  clave=[('La declaración es una línea de tiempo. ¿En qué orden va?',
          'Existía antes · creó todo · se encarnó · nació de María · vivió sin pecado · hizo milagros · murió · resucitó · ascendió · hoy ministra en el Santuario · pronto vuelve'),
         ('¿Dónde ministra hoy?',
          '«En el Santuario celestial»'),
         ('¿Para qué volverá?',
          '«Para liberar a su pueblo y restaurar todas las cosas»')],
  confunde=[(9,'La 9 desarrolla la vida, muerte y resurrección'),
            (24,'La 24 desarrolla el ministerio en el Santuario'),
            (25,'La 25 desarrolla la segunda venida')]),
5: dict(
  desarrollo=['¿Quién es el Espíritu Santo?','El Espíritu Santo y la Deidad','El Espíritu prometido',
              'La misión del Espíritu Santo'],
  clave=[('Los TRES momentos en que tuvo parte activa con el Padre y el Hijo',
          'La creación · la encarnación · la redención'),
         ('¿Quién lo envió?',
          '«El Padre y el Hijo». Los dos, no uno solo'),
         ('¿Con qué condición guía a toda la verdad?',
          '«En armonía con las Escrituras». Nunca contradice la Biblia, que es la creencia 1 dicha al revés')],
  confunde=[(17,'La 5 dice que concede dones. La 17 es la que los desarrolla')]),
6: dict(
  desarrollo=['La palabra creadora de Dios','El relato de la creación','El Dios de la creación',
              'El propósito de la creación','La creación y la salvación'],
  clave=[('¿En cuántos días y qué hizo el séptimo?',
          'Seis días, y «reposó en el séptimo día de esa primera semana»'),
         ('¿Qué quedó establecido con ese reposo?',
          'El sábado, «como un monumento perpetuo conmemorativo de la terminación de su obra creadora»'),
         ('Las dos frases entre comillas de la declaración',
          '«Los cielos y la tierra» y «bueno en gran manera»')],
  confunde=[(20,'La 6 es la creación y de paso el origen del sábado. La 20 es el sábado en sí')]),
7: dict(
  desarrollo=['El origen del hombre','La unidad de la naturaleza humana','El hombre a imagen de Dios',
              'La caída','El pacto de la gracia'],
  clave=[('¿De qué está hecho el ser humano, según la declaración?',
          'Una unidad de cuerpo, mente y espíritu, dependiente de Él. No tres partes separables'),
         ('¿Qué pasó al desobedecer?',
          'Adán y Eva cayeron, «distorsionaron la imagen divina y quedaron sujetos a la muerte»'),
         ('¿A qué tres cosas fuimos llamados?',
          'Amar a Dios · al prójimo · cuidar el entorno que nos rodea')],
  confunde=[(8,'La 7 es qué es el ser humano. La 8 es el conflicto en el que está metido')]),
8: dict(
  desarrollo=['Una visión cósmica del conflicto','El tema central','El significado de la doctrina'],
  clave=[('¿Sobre qué tres cosas es el conflicto?',
          'Sobre el carácter de Dios, su ley y su soberanía'),
         ('¿Dónde empezó y con quién?',
          'En el cielo, con Lucifer, «un ser creado» que se rebeló y arrastró a otros ángeles'),
         ('¿En qué culminó la alteración de la creación?',
          'En el diluvio')],
  confunde=[(7,'La 7 explica la caída de Adán y Eva. La 8 la mete en un conflicto que empezó antes, en el cielo')]),
9: dict(
  desarrollo=['La gracia salvadora de Dios','El sacrificio expiatorio de Cristo','Cristo, el Redentor',
              'La vida y la salvación de Cristo','La resurrección y la salvación de Cristo'],
  clave=[('Los CUATRO adjetivos del sacrificio',
          'Vicario · expiatorio · reconciliador · transformador'),
         ('¿Qué hace la muerte de Jesús con la ley?',
          '«Vindica la justicia de la ley de Dios y garantiza el perdón»'),
         ('¿Qué proclama y qué asegura la resurrección?',
          'Proclama la victoria sobre el mal; asegura el triunfo final sobre el pecado y la muerte')],
  confunde=[(10,'La 9 es lo que Cristo HIZO. La 10 es lo que pasa en la persona que lo acepta')]),
10: dict(
  desarrollo=['La justificación','La adopción','El nuevo nacimiento','La santificación'],
  clave=[('¿De dónde viene la fe, según la declaración?',
          'Es «don de la gracia divina» y «viene por la Palabra de Dios». No se produce por esfuerzo propio'),
         ('Las tres cosas que pasan a través de Cristo',
          'Somos justificados · adoptados como hijos · liberados del pecado'),
         ('¿Qué hace el Espíritu?',
          'Nos hace nacer de nuevo, renueva corazones y mentes, graba su ley y nos capacita para una vida santa')],
  confunde=[(11,'La 10 es entrar a la salvación. La 11 es crecer una vez adentro')]),
11: dict(
  desarrollo=['La vida comienza con la muerte','Señales del crecimiento en Cristo'],
  clave=[('¿Dónde venció Jesús a las fuerzas del mal?',
          'En la cruz, «asegurando su destrucción final»'),
         ('Los cinco medios para crecer a su semejanza',
          'La oración · el estudio de su Palabra · la alabanza · la adoración · la misión'),
         ('¿En qué se transforma cada momento?',
          '«En una experiencia espiritual guiada por su presencia», al servir con amor y testificar')],
  confunde=[(10,'La 10 es el momento de la salvación. La 11 es la vida diaria después')]),
12: dict(
  desarrollo=['La naturaleza de la iglesia','La organización de la iglesia','El gobierno de la iglesia'],
  clave=[('Las tres imágenes de la iglesia en la declaración',
          'La familia de Dios · el cuerpo de Cristo, cuya cabeza es Él · la esposa que Él santifica'),
         ('¿De dónde recibe su autoridad?',
          'De Cristo y las Escrituras'),
         ('¿Cómo será la iglesia que Cristo presentará al regresar?',
          '«Gloriosa, santa y sin mancha, formada por los fieles de todas las edades»')],
  confunde=[(13,'La 12 es la iglesia. La 13 es el remanente dentro de ella, en los últimos días')]),
13: dict(
  desarrollo=['La gran apostasía','La reforma','El remanente','La misión del remanente'],
  clave=[('¿Qué guarda el remanente?',
          '«Los mandamientos de Dios y la fe de Jesús»'),
         ('Las tres cosas que anuncia',
          'La llegada de la hora del juicio · la salvación por medio de Cristo · la proximidad de su segunda venida'),
         ('¿Con qué está simbolizada esa proclamación?',
          'Con los tres ángeles de Apocalipsis 14')],
  confunde=[(12,'La 12 es la iglesia universal. La 13 es el llamado del remanente en la apostasía')]),
14: dict(
  desarrollo=['La unidad de la Biblia y la iglesia','El logro de la unidad'],
  clave=[('¿Qué dice el libro de las 28 creencias sobre esta creencia?',
          'Que la iglesia es un solo cuerpo con muchos miembros, llamados de toda nación, raza y lengua; que en Cristo somos una nueva creación y no debe haber diferencias de raza, cultura o condición'),
         ('¿Por qué esta creencia está marcada en la app?',
          'Porque la cartilla 2026 trae aquí, por error de imprenta, el texto de la creencia 13. Está pendiente de confirmar contra el impreso')],
  confunde=[(12,'La 12 es qué es la iglesia. La 14 es que esa iglesia sea UNA sola a pesar de las diferencias')]),
15: dict(
  desarrollo=['¿Cuán importante es el bautismo?','El significado del bautismo','Requisitos para el bautismo',
              'El fruto del bautismo'],
  clave=[('¿De qué es símbolo el bautismo?',
          'De nuestra unión con Cristo, del perdón de nuestros pecados y de nuestro recibimiento del Espíritu Santo'),
         ('¿Cómo se realiza?',
          '«Por inmersión en agua»'),
         ('Los dos requisitos',
          'Una afirmación de fe en Jesús y la evidencia de arrepentimiento del pecado. Y sigue a la instrucción en las Escrituras')],
  confunde=[(16,'La 15 es el bautismo, una sola vez. La 16 es la Cena, que se repite')]),
16: dict(
  desarrollo=['La celebración de la Cena del Señor','El servicio del lavamiento de los pies'],
  clave=[('¿Qué proclamamos al participar?',
          '«Gozosamente la muerte del Señor hasta que venga»'),
         ('Las tres cosas que incluye la preparación',
          'Un examen de conciencia · el arrepentimiento · la confesión'),
         ('¿Para qué ordenó el Maestro el lavamiento de los pies?',
          'Para denotar una renovada purificación, expresar la disposición a servirnos mutuamente en humildad, y unir nuestros corazones en amor')],
  confunde=[(15,'El bautismo es la entrada; la Cena es la comunión que sigue. Y la Cena «está abierta a todos los creyentes cristianos»')]),
17: dict(
  desarrollo=['Los dones del Espíritu Santo','El propósito de los dones espirituales'],
  clave=[('¿Para qué se dan los dones?',
          'Para servir con amor al prójimo y edificar la iglesia'),
         ('¿Quién los distribuye y según qué?',
          'El Espíritu Santo, «según su voluntad»'),
         ('¿Qué pasa cuando los miembros los usan fielmente?',
          'La iglesia crece, se protege de errores, y se edifica en la fe y el amor')],
  confunde=[(18,'La 17 son todos los dones. La 18 es UNO de ellos, el de profecía')]),
18: dict(
  desarrollo=['El don profético en los tiempos bíblicos','El don profético en los últimos días',
              'Los profetas postbíblicos y la Biblia'],
  clave=[('¿De qué es señal este don?',
          'Es «una señal identificadora de la iglesia remanente»'),
         ('¿Qué son los escritos de Elena G. de White, según la declaración?',
          '«Una permanente y autorizada fuente de verdad que proporciona consuelo, dirección, instrucción y corrección a la iglesia»'),
         ('¿Qué establecen esos escritos con claridad?',
          'Que la Biblia es la norma por la cual debe ser probada toda enseñanza y toda experiencia')],
  confunde=[(1,'La 18 se somete a la 1. Nunca al revés, y eso lo dice la 18 misma')]),
19: dict(
  desarrollo=['La naturaleza de la ley','El propósito de la ley','La perpetuidad de la ley',
              'La ley y el evangelio','La obediencia a la ley'],
  clave=[('¿Qué expresan los Diez Mandamientos?',
          'El amor, la voluntad y el propósito de Dios para la conducta humana'),
         ('¿Para qué usa el Espíritu Santo la ley?',
          'Para revelar el pecado y mostrar la necesidad de un Salvador'),
         ('La frase sobre gracia y obediencia',
          '«Aunque la salvación es por gracia, la obediencia es su fruto». La obediencia no salva: es el resultado')],
  confunde=[(20,'La 19 es la ley completa. La 20 es el cuarto mandamiento')]),
20: dict(
  desarrollo=['El sábado a través de la Biblia','Intentos de cambiar el día de adoración','La observancia del sábado'],
  clave=[('Las tres cosas que ordena el cuarto mandamiento',
          'Reposo · adoración · servicio'),
         ('¿De qué es señal el sábado?',
          'De santificación, lealtad y esperanza en la vida eterna. Y es «un pacto perpetuo entre Dios y su pueblo»'),
         ('¿Desde cuándo hasta cuándo se observa?',
          '«De puesta de sol a puesta de sol»')],
  confunde=[(6,'La 6 cuenta cuándo nació el sábado. La 20 dice cómo se guarda')]),
21: dict(
  desarrollo=['¿Qué es la mayordomía?','Cristo como mayordomo','Las bendiciones de la mayordomía'],
  clave=[('¿Qué se nos ha confiado?',
          'Tiempo y oportunidades, capacidades y posesiones, y las bendiciones de la tierra y sus recursos'),
         ('¿Cómo reconocemos el derecho de propiedad de Dios?',
          'Con el servicio fiel a él y al prójimo, y con la devolución de los diezmos y las ofrendas'),
         ('¿Sobre qué dos cosas da la victoria?',
          'Sobre el egoísmo y la codicia')],
  confunde=[(22,'La 21 es qué hago con lo que tengo. La 22 es cómo vivo')]),
22: dict(
  desarrollo=['La conducta y la salvación','Templos del Espíritu Santo','Los principios de las normas cristianas'],
  clave=[('¿Cómo debe ser la vestimenta?',
          '«Modesta y de buen gusto, mostrando una belleza interior»'),
         ('Las tres formas de cuidar el cuerpo',
          'Ejercicio · descanso · una alimentación saludable'),
         ('¿De qué nos abstenemos?',
          'Del alcohol, tabaco, drogas y alimentos inmundos, según las Escrituras')],
  confunde=[(21,'La 22 es la conducta personal; la 21 es la administración de los recursos')]),
23: dict(
  desarrollo=['Desde el comienzo','Desviaciones del ideal de Dios','La familia','Los padres y los hijos'],
  clave=[('¿Cómo define la declaración el matrimonio?',
          '«Una unión para toda la vida entre un hombre y una mujer, basada en el amor y la fe compartida»'),
         ('¿Qué refleja ese compromiso?',
          'La relación entre Cristo y su iglesia'),
         ('¿Qué enseñó Jesús sobre el divorcio?',
          'Que solo es aceptable por inmoralidad sexual; fuera de eso, volver a casarse es adulterio')],
  confunde=[(22,'La 23 es la familia; la 22 es la conducta individual')]),
24: dict(
  desarrollo=['El Santuario del cielo','El ministerio del Santuario celestial','El Día de la Expiación',
              'El Santuario celestial en la profecía'],
  clave=[('¿Qué año y qué empezó?',
          '1844: «la fase final de su ministerio, el juicio investigador»'),
         ('¿Qué busca revelar el juicio investigador?',
          '«Quiénes, muertos o vivos, están en Cristo y preparados para la vida eterna»'),
         ('¿Qué pasa cuando Cristo concluya este ministerio?',
          '«Terminará el tiempo de prueba antes de su regreso»')],
  confunde=[(25,'La 24 es lo que Cristo hace AHORA en el cielo. La 25 es su regreso')]),
25: dict(
  desarrollo=['La certeza del retorno de Jesús','La manera en que Cristo volverá','Estemos listos en todo tiempo'],
  clave=[('Los CUATRO adjetivos del regreso',
          'Literal · personal · visible · global'),
         ('¿Qué pasa con cada grupo en su regreso?',
          'Los justos muertos resucitan y, con los vivos fieles, son glorificados y llevados al cielo. Los impíos mueren'),
         ('¿Qué se dice de la fecha?',
          'Que «no ha sido revelada», y por eso se nos llama a vivir preparados en todo momento')],
  confunde=[(24,'La 25 es la venida. La 24 es lo que la precede en el cielo')]),
26: dict(
  desarrollo=['La inmortalidad y la muerte','La naturaleza de la muerte','La resurrección'],
  clave=[('¿Quién es «el único inmortal», según la declaración?',
          'Dios. La inmortalidad no es algo que el ser humano tenga por naturaleza: es lo que Dios «dará a los redimidos»'),
         ('¿Qué es la muerte mientras tanto?',
          '«Un estado de inconsciencia»'),
         ('¿Cuándo resucita cada grupo?',
          'Los justos muertos cuando Cristo regrese, junto con los vivos fieles. Los impíos «mil años después, como parte del juicio final»')],
  confunde=[(27,'La 26 son las dos resurrecciones. La 27 son los mil años que van entre ellas')]),
27: dict(
  desarrollo=['Acontecimientos durante el milenio','Acontecimientos al fin del milenio'],
  clave=[('¿Entre qué dos cosas va el milenio, y dónde está Cristo?',
          '«Entre la primera y la segunda resurrección», y Cristo reina «con sus santos en el cielo»'),
         ('¿Cómo queda la Tierra durante los mil años?',
          '«Desolada, habitada solo por Satanás y sus ángeles»'),
         ('¿Qué pasa al final del milenio?',
          'Cristo, los redimidos y la Santa Ciudad descienden del cielo; los impíos resucitan, rodean la ciudad con Satanás, y son destruidos por el fuego de Dios')],
  confunde=[(28,'La 27 elimina el pecado «para siempre». La 28 es lo que empieza después')]),
28: dict(
  desarrollo=['La naturaleza de la Tierra Nueva','La Nueva Jerusalén','Nuestro hogar eterno',
              'La vida en la Tierra Nueva'],
  clave=[('¿Qué habita en la Tierra Nueva?',
          'La justicia'),
         ('¿Qué ya no habrá?',
          '«Más sufrimiento ni muerte». El gran conflicto habrá terminado y «el pecado no existirá jamás»'),
         ('¿Qué proclamará todo el universo?',
          '«Que Dios es amor», y Él reinará por la eternidad')],
  confunde=[(27,'La 27 cierra el pecado. La 28 abre lo que sigue para siempre')]),
}
