/* Daniel 1-6 en Reina-Valera 1995, los 196 versiculos.
 *
 * DE DONDE SALE
 * Se genero de files/rv1995-daniel-1..6.txt, que es el texto que se bajo y se
 * partio verso por verso en agosto y contra el que se valida todo el material.
 * Esos .txt viven FUERA del repositorio porque el repo es publico; este
 * archivo si entra, porque la app lo necesita para funcionar y porque «el
 * archivo desplegado es la fuente».
 *
 * PARA QUE ESTA
 * 1. La seccion «Leer el capitulo» de cada capitulo de Daniel.
 * 2. Las referencias tocables: cada «(2:41)» del material abre ESE versiculo
 *    ahi mismo, sin salir de la seccion.
 * 3. Que las pruebas puedan cotejar las citas en cada corrida, en vez de
 *    depender de que alguien se acuerde de correr tools/citas.js con los .txt
 *    a mano. tools/citas.js sigue existiendo para verificar que ESTE archivo
 *    coincide con los .txt; la suite verifica que el material coincide con
 *    este archivo.
 *
 * OJO CON DANIEL 5: en RV1995 tiene 31 versiculos porque 5:31 va ahi. Otras
 * ediciones lo mueven a 6:1 y darian 30 y 29.
 *
 * NO EDITAR A MANO. Si hay que corregir un versiculo se corrige el .txt y se
 * regenera, o las dos fuentes se separan y tools/citas.js empieza a fallar.
 */

const VERS = {
 d1: {
  1: "En el tercer año del reinado de Joacim, rey de Judá, vino Nabucodonosor, rey de Babilonia, a Jerusalén, y la sitió.",
  2: "El Señor entregó en sus manos a Joacim, rey de Judá, y parte de los utensilios de la casa de Dios; los trajo a tierra de Sinar, a la casa de su dios, y colocó los utensilios en la casa del tesoro de su dios.",
  3: "Y dijo el rey a Aspenaz, jefe de sus eunucos, que trajera de los hijos de Israel, del linaje real de los príncipes,",
  4: "muchachos en quienes no hubiera tacha alguna, de buen parecer, instruidos en toda sabiduría, sabios en ciencia, de buen entendimiento e idóneos para estar en el palacio del rey; y que les enseñara las letras y la lengua de los caldeos.",
  5: "Y les señaló el rey una porción diaria de la comida del rey y del vino que él bebía; y que los educara durante tres años, para que al fin de ellos se presentaran delante del rey.",
  6: "Entre ellos estaban Daniel, Ananías, Misael y Azarías, de los hijos de Judá.",
  7: "A estos el jefe de los eunucos puso nombres: a Daniel, Beltsasar; a Ananías, Sadrac; a Misael, Mesac; y a Azarías, Abed-nego.",
  8: "Daniel propuso en su corazón no contaminarse con la porción de la comida del rey ni con el vino que él bebía; pidió, por tanto, al jefe de los eunucos que no se le obligara a contaminarse.",
  9: "Puso Dios a Daniel en gracia y en buena voluntad con el jefe de los eunucos;",
  10: "y el jefe de los eunucos dijo a Daniel: —Temo a mi señor el rey, que asignó vuestra comida y vuestra bebida; pues luego que él vea vuestros rostros más pálidos que los de los muchachos que son semejantes a vosotros, haréis que el rey me condene a muerte.",
  11: "Entonces dijo Daniel a Melsar, a quien el jefe de los eunucos había puesto sobre Daniel, Ananías, Misael y Azarías:",
  12: "—Te ruego que hagas la prueba con tus siervos durante diez días: que nos den legumbres para comer y agua para beber.",
  13: "Compara luego nuestros rostros con los rostros de los muchachos que comen de la porción de la comida del rey, y haz después con tus siervos según veas.",
  14: "Consintió, pues, con ellos en esto, y probó con ellos durante diez días.",
  15: "Y al cabo de los diez días pareció el rostro de ellos mejor y más robusto que el de los otros muchachos que comían de la porción de la comida del rey.",
  16: "Así, pues, Melsar se llevaba la porción de la comida de ellos y el vino que habían de beber, y les daba legumbres.",
  17: "A estos cuatro muchachos, Dios les dio conocimiento e inteligencia en todas las letras y ciencias; y Daniel tuvo entendimiento en toda visión y sueños.",
  18: "Pasados, pues, los días al fin de los cuales había dicho el rey que los llevaran, el jefe de los eunucos los llevó delante de Nabucodonosor.",
  19: "El rey habló con ellos, y no se hallaron entre todos ellos otros como Daniel, Ananías, Misael y Azarías; así, pues, permanecieron al servicio del rey.",
  20: "En todo asunto de sabiduría e inteligencia que el rey los consultó, los halló diez veces mejores que todos los magos y astrólogos que había en todo su reino.",
  21: "Así continuó Daniel hasta el año primero del rey Ciro.",
 },
 d2: {
  1: "En el segundo año del reinado de Nabucodonosor, tuvo Nabucodonosor sueños, y se turbó su espíritu y se le fue el sueño.",
  2: "Hizo llamar el rey a magos, astrólogos, encantadores y caldeos, para que le explicaran sus sueños. Vinieron, pues, y se presentaron delante del rey.",
  3: "El rey les dijo: —He tenido un sueño, y mi espíritu se ha turbado por saber el sueño.",
  4: "Entonces hablaron los caldeos al rey en lengua aramea: —¡Rey, para siempre vive! Cuenta el sueño a tus siervos, y te daremos la interpretación.",
  5: "Respondió el rey y dijo a los caldeos: —El asunto lo olvidé; pero si no me decís el sueño y su interpretación, seréis hechos pedazos y vuestras casas serán convertidas en estercoleros.",
  6: "Pero si me decís el sueño y su interpretación, de mí recibiréis dones, favores y gran honra. Decidme, pues, el sueño y su interpretación.",
  7: "Respondieron por segunda vez, y dijeron: —Cuente el rey el sueño a sus siervos, y le daremos la interpretación.",
  8: "El rey respondió y dijo: —Yo conozco ciertamente que vosotros ponéis dilaciones, porque veis que el asunto se me ha ido.",
  9: "Si no me contáis el sueño, una sola sentencia hay para vosotros. Ciertamente preparáis una respuesta mentirosa y perversa que decir delante de mí, entre tanto que pasa el tiempo. Contadme, pues, el sueño, para que yo sepa que me podéis dar su interpretación.",
  10: "Los caldeos respondieron delante del rey y dijeron: —No hay hombre sobre la tierra que pueda declarar el asunto del rey. Además, ningún rey, príncipe ni señor preguntó cosa semejante a ningún mago ni astrólogo ni caldeo.",
  11: "Porque el asunto que el rey demanda es difícil, y no hay quien lo pueda declarar al rey, salvo los dioses cuya morada no está entre los hombres.",
  12: "Por esto el rey, con ira y con gran enojo, mandó que mataran a todos los sabios de Babilonia.",
  13: "Se publicó, pues, el edicto de que los sabios fueran llevados a la muerte; y buscaron también a Daniel y a sus compañeros para matarlos.",
  14: "Entonces Daniel habló sabia y prudentemente a Arioc, capitán de la guardia del rey, que había salido para matar a los sabios de Babilonia.",
  15: "Habló y dijo a Arioc, capitán del rey: —¿Cuál es la causa de que este edicto se publique de parte del rey tan apresuradamente? Entonces Arioc hizo saber a Daniel lo que había;",
  16: "y Daniel entró y pidió al rey que le concediera tiempo, que él daría al rey la interpretación.",
  17: "Luego se fue Daniel a su casa e hizo saber a Ananías, Misael y Azarías, sus compañeros, lo que sucedía",
  18: "para que pidieran misericordias del Dios del cielo sobre este misterio, a fin de que Daniel y sus compañeros no perecieran con los otros sabios de Babilonia.",
  19: "El secreto le fue revelado a Daniel en visión de noche, por lo cual bendijo Daniel al Dios del cielo.",
  20: "Habló Daniel y dijo: «Sea bendito el nombre de Dios de siglos en siglos, porque suyos son el poder y la sabiduría.",
  21: "Él muda los tiempos y las edades, quita reyes y pone reyes; da la sabiduría a los sabios y la ciencia a los entendidos.",
  22: "Él revela lo profundo y lo escondido, conoce lo que está en tinieblas y con él mora la luz.",
  23: "A ti, Dios de mis padres, te doy gracias y te alabo, porque me has dado sabiduría y fuerza, y ahora me has revelado lo que te pedimos, pues nos has dado a conocer el asunto del rey.»",
  24: "Después de esto fue Daniel a Arioc, al cual el rey había puesto para matar a los sabios de Babilonia, y le dijo: —No mates a los sabios de Babilonia; llévame a la presencia del rey, y yo le daré la interpretación.",
  25: "Entonces Arioc llevó prontamente a Daniel ante el rey, y le dijo así: —He hallado un hombre de los deportados de Judá, el cual dará al rey la interpretación.",
  26: "Respondió el rey y dijo a Daniel, al cual llamaban Beltsasar: —¿Podrás tú hacerme conocer el sueño que vi, y su interpretación?",
  27: "Daniel respondió al rey diciendo: —El misterio que el rey demanda, ni sabios ni astrólogos, ni magos ni adivinos lo pueden revelar al rey.",
  28: "Pero hay un Dios en los cielos que revela los misterios, y él ha hecho saber al rey Nabucodonosor lo que ha de acontecer en los últimos días. Éstos son tu sueño y las visiones que has tenido en tu cama:",
  29: "»Estando tú, rey, en tu cama, te vinieron pensamientos por saber lo que había de suceder en lo por venir; y el que revela los misterios te mostró lo que ha de ser.",
  30: "Y a mí me ha sido revelado este misterio, no porque en mí haya más sabiduría que en los demás vivientes, sino para que se dé a conocer al rey la interpretación y para que entiendas los pensamientos de tu corazón.",
  31: "»Tú, rey, veías en tu sueño una gran imagen. Esta imagen era muy grande y su gloria, muy sublime. Estaba en pie delante de ti y su aspecto era terrible.",
  32: "La cabeza de esta imagen era de oro fino; su pecho y sus brazos, de plata; su vientre y sus muslos, de bronce;",
  33: "sus piernas, de hierro; sus pies, en parte de hierro y en parte de barro cocido.",
  34: "Estabas mirando, hasta que una piedra se desprendió sin que la cortara mano alguna, e hirió a la imagen en sus pies de hierro y de barro cocido, y los desmenuzó.",
  35: "Entonces fueron desmenuzados también el hierro, el barro cocido, el bronce, la plata y el oro, y fueron como tamo de las eras del verano, y se los llevó el viento sin que de ellos quedara rastro alguno. Pero la piedra que hirió a la imagen se hizo un gran monte que llenó toda la tierra.",
  36: "»Éste es el sueño. También la interpretación de él diremos en presencia del rey.",
  37: "Tú, rey, eres rey de reyes; porque el Dios del cielo te ha dado reino, poder, fuerza y majestad.",
  38: "Dondequiera que habitan hijos de hombres, bestias del campo y aves del cielo, él los ha entregado en tus manos, y te ha dado el dominio sobre todo. Tú eres aquella cabeza de oro.",
  39: "Después de ti se levantará otro reino, inferior al tuyo; y luego un tercer reino de bronce, el cual dominará sobre toda la tierra.",
  40: "Y el cuarto reino será fuerte como el hierro; y como el hierro desmenuza y rompe todas las cosas, así él lo desmenuzará y lo quebrantará todo.",
  41: "»Lo que viste de los pies y los dedos, en parte de barro cocido de alfarero y en parte de hierro, será un reino dividido; pero habrá en él algo de la fuerza del hierro, así como viste el hierro mezclado con barro cocido.",
  42: "Y por ser los dedos de los pies en parte de hierro y en parte de barro cocido, este reino será en parte fuerte y en parte frágil.",
  43: "Así como viste el hierro mezclado con barro, así se mezclarán por medio de alianzas humanas; pero no se unirán el uno con el otro, como el hierro no se mezcla con el barro.",
  44: "En los días de estos reyes, el Dios del cielo levantará un reino que no será jamás destruido, ni será el reino dejado a otro pueblo; desmenuzará y consumirá a todos estos reinos, pero él permanecerá para siempre,",
  45: "de la manera que viste que del monte se desprendió una piedra sin que la cortara mano alguna, la cual desmenuzó el hierro, el bronce, el barro, la plata y el oro. El gran Dios ha mostrado al rey lo que ha de acontecer en lo por venir; y el sueño es verdadero, y fiel su interpretación.»",
  46: "Entonces el rey Nabucodonosor se postró sobre su rostro, se humilló ante Daniel, y mandó que le ofrecieran presentes e incienso.",
  47: "El rey habló a Daniel, y dijo: —Ciertamente el Dios vuestro es Dios de dioses, Señor de los reyes y el que revela los misterios, pues pudiste revelar este misterio.",
  48: "Entonces el rey engrandeció a Daniel, le dio muchos honores y grandes dones, y lo hizo gobernador de toda la provincia de Babilonia y jefe supremo de todos los sabios de Babilonia.",
  49: "Daniel solicitó y obtuvo del rey que pusiera sobre los negocios de la provincia de Babilonia a Sadrac, Mesac y Abed-nego; y Daniel estaba en la corte del rey.",
 },
 d3: {
  1: "El rey Nabucodonosor hizo una estatua de oro, cuya altura era de sesenta codos y la anchura de seis codos; la levantó en el campo de Dura, en la provincia de Babilonia.",
  2: "Y ordenó el rey Nabucodonosor que se reunieran los sátrapas, los magistrados, capitanes, oidores, tesoreros, consejeros, jueces y todos los gobernadores de las provincias, para que vinieran a la dedicación de la estatua que el rey Nabucodonosor había levantado.",
  3: "Se reunieron, pues, los sátrapas, magistrados, capitanes, oidores, tesoreros, consejeros, jueces y todos los gobernadores de las provincias, para la dedicación de la estatua que el rey Nabucodonosor había levantado; y estaban en pie delante de la estatua que había levantado el rey Nabucodonosor.",
  4: "Y el pregonero anunciaba en alta voz: «Se os ordena a vosotros, pueblos, naciones y lenguas,",
  5: "que al oír el son de la bocina, la flauta, la cítara, el arpa, el salterio, la zampoña y todo instrumento de música, os postréis y adoréis la estatua de oro que el rey Nabucodonosor ha levantado;",
  6: "y cualquiera que no se postre y adore, inmediatamente será echado dentro de un horno de fuego ardiente.»",
  7: "Por lo cual, al oír todos los pueblos el son de la bocina, la flauta, la cítara, el arpa, el salterio, la zampoña y todo instrumento de música, todos los pueblos, naciones y lenguas se postraron y adoraron la estatua de oro que el rey Nabucodonosor había levantado.",
  8: "Por esto, en aquel tiempo algunos hombres caldeos vinieron y acusaron maliciosamente a los judíos.",
  9: "Hablaron y dijeron al rey Nabucodonosor: —¡Rey, para siempre vive!",
  10: "Tú, rey, has dado una ley que todo hombre, al oír el son de la bocina, la flauta, la cítara, el arpa, el salterio, la zampoña y todo instrumento de música, se postre y adore la estatua de oro;",
  11: "y el que no se postre y adore, sea echado dentro de un horno de fuego ardiente.",
  12: "Hay unos hombres judíos, a los cuales pusiste sobre los negocios de la provincia de Babilonia: Sadrac, Mesac y Abed-nego; estos hombres, oh rey, no te han respetado; no adoran a tus dioses ni adoran la estatua de oro que has levantado.",
  13: "Entonces Nabucodonosor dijo con ira y con enojo que trajeran a Sadrac, Mesac y Abed-nego. Al instante fueron traídos delante del rey.",
  14: "Habló Nabucodonosor y les dijo: —¿Es verdad, Sadrac, Mesac y Abed-nego, que vosotros no honráis a mi dios ni adoráis la estatua de oro que he levantado?",
  15: "Ahora, pues, ¿estáis dispuestos para que, al oír el son de la bocina, la flauta, la cítara, el arpa, el salterio, la zampoña y todo instrumento de música, os postréis y adoréis la estatua que he hecho? Porque si no la adoráis, en la misma hora seréis echados en medio de un horno de fuego ardiente, ¿y qué dios será el que os libre de mis manos?",
  16: "Sadrac, Mesac y Abed-nego respondieron al rey Nabucodonosor, diciendo: —No es necesario que te respondamos sobre este asunto.",
  17: "Nuestro Dios, a quien servimos, puede librarnos del horno de fuego ardiente; y de tus manos, rey, nos librará.",
  18: "Y si no, has de saber, oh rey, que no serviremos a tus dioses ni tampoco adoraremos la estatua que has levantado.",
  19: "Entonces Nabucodonosor se llenó de ira, cambió el aspecto de su rostro contra Sadrac, Mesac y Abed-nego y ordenó que el horno se calentara siete veces más de lo acostumbrado.",
  20: "Y ordenó a hombres muy vigorosos que tenía en su ejército, que ataran a Sadrac, Mesac y Abed-nego, para echarlos en el horno de fuego ardiente.",
  21: "Así pues, estos hombres fueron atados con sus mantos, sus calzados, sus turbantes y sus vestidos, y fueron echados dentro del horno de fuego ardiente.",
  22: "Y como la orden del rey era apremiante, y habían calentado mucho el horno, la llama del fuego mató a aquellos que habían alzado a Sadrac, Mesac y Abed-nego.",
  23: "Estos tres hombres, Sadrac, Mesac y Abed-nego, cayeron atados dentro del horno de fuego ardiente.",
  24: "Entonces el rey Nabucodonosor se espantó, se levantó apresuradamente y dijo a los de su consejo: —¿No echaron a tres hombres atados dentro del fuego? Ellos respondieron al rey: —Es verdad, oh rey.",
  25: "Y él dijo: —Sin embargo, yo veo cuatro hombres sueltos, que se pasean en medio del fuego sin sufrir ningún daño; y el aspecto del cuarto es semejante a un hijo de los dioses.",
  26: "Entonces Nabucodonosor se acercó a la puerta del horno de fuego ardiente, y dijo: —Sadrac, Mesac y Abed-nego, siervos del Dios Altísimo, salid y venid. Sadrac, Mesac y Abed-nego salieron de en medio del fuego.",
  27: "Y se juntaron los sátrapas, los gobernadores, los capitanes y los consejeros del rey para mirar a estos hombres, cómo el fuego no había tenido poder alguno sobre sus cuerpos y ni aun el cabello de sus cabezas se había quemado; sus ropas, intactas, ni siquiera olor de fuego tenían.",
  28: "Y Nabucodonosor dijo: «Bendito sea el Dios de Sadrac, Mesac y Abed-nego, que envió su ángel y libró a sus siervos que confiaron en él, los cuales no cumplieron el edicto del rey y entregaron sus cuerpos antes que servir y adorar a otro dios que su Dios.",
  29: "Por lo tanto, decreto que todo pueblo, nación o lengua que diga blasfemia contra el Dios de Sadrac, Mesac y Abed-nego, sea descuartizado, y su casa convertida en estercolero; por cuanto no hay dios que pueda librar como éste.»",
  30: "Entonces el rey engrandeció a Sadrac, Mesac y Abed-nego en la provincia de Babilonia.",
 },
 d4: {
  1: "«Nabucodonosor, rey, a todos los pueblos, naciones y lenguas que moran en toda la tierra: Paz os sea multiplicada.",
  2: "»Conviene que yo declare las señales y milagros que el Dios Altísimo ha hecho conmigo.",
  3: "¡Cuán grandes son sus señales y cuán potentes sus maravillas! Su reino, reino sempiterno; su señorío, de generación en generación.",
  4: "»Yo, Nabucodonosor, estaba tranquilo en mi casa, floreciente en mi palacio.",
  5: "Tuve un sueño que me espantó; tendido en la cama, las imaginaciones y visiones de mi cabeza me turbaron.",
  6: "Por esto mandé que vinieran ante mí todos los sabios de Babilonia para que me dieran la interpretación del sueño.",
  7: "Y vinieron magos, astrólogos, caldeos y adivinos, y les conté el sueño, pero no me pudieron dar su interpretación,",
  8: "hasta que entró ante mí Daniel, cuyo nombre es Beltsasar, como el nombre de mi dios, y en quien mora el espíritu de los dioses santos. Conté delante de él el sueño, diciendo:",
  9: "“Beltsasar, jefe de los magos, ya que he entendido que hay en ti espíritu de los dioses santos y que ningún misterio se te esconde, declárame las visiones de mi sueño que he visto, y su interpretación.",
  10: "Éstas fueron las visiones de mi cabeza mientras estaba en mi cama: »”Me parecía ver en medio de la tierra un árbol cuya altura era grande.",
  11: "Crecía este árbol, y se hacía fuerte, y su copa llegaba hasta el cielo y se le alcanzaba a ver desde todos los confines de la tierra.",
  12: "Su follaje era hermoso, su fruto abundante y había en él alimento para todos. Debajo de él, a su sombra, se ponían las bestias del campo, en sus ramas anidaban las aves del cielo y se mantenía de él todo ser viviente.",
  13: "»”Vi en las visiones de mi cabeza, mientras estaba en mi cama, que un vigilante y santo descendía del cielo.",
  14: "Clamaba fuertemente y decía así: »”‘Derribad el árbol y cortad sus ramas, quitadle el follaje y dispersad su fruto; váyanse las bestias que están debajo de él, y las aves de sus ramas.",
  15: "Mas la cepa de sus raíces dejaréis en la tierra, con atadura de hierro y de bronce entre la hierba del campo; que lo empape el rocío del cielo, y con las bestias sea su parte entre la hierba de la tierra.",
  16: "Su corazón de hombre sea cambiado y le sea dado corazón de bestia, y pasen sobre él siete tiempos.",
  17: "La sentencia es por decreto de los vigilantes y por dicho de los santos la resolución, para que conozcan los vivientes que el Altísimo gobierna el reino de los hombres, que a quien él quiere lo da y sobre él constituye al más humilde de los hombres.’",
  18: "»”Yo, el rey Nabucodonosor, he visto este sueño. Tú, pues, Beltsasar, darás su interpretación, porque ninguno entre los sabios de mi reino lo ha podido interpretar; pero tú puedes, porque habita en ti el espíritu de los dioses santos.”»",
  19: "Entonces Daniel, cuyo nombre era Beltsasar, quedó atónito casi una hora, y sus pensamientos lo turbaban. El rey habló y dijo: —Beltsasar, no te turben ni el sueño ni su interpretación. Beltsasar respondió y dijo: —Señor mío, el sueño sea para tus enemigos y su interpretación para los que mal te quieren.",
  20: "El árbol que viste, que crecía y se hacía fuerte, cuya copa llegaba hasta el cielo, que se veía desde todos los confines de la tierra,",
  21: "cuyo follaje era hermoso y su fruto abundante, en el que había alimento para todos, debajo del cual vivían las bestias del campo y en cuyas ramas anidaban las aves del cielo,",
  22: "tú mismo eres, oh rey, que creciste y te hiciste fuerte, pues creció tu grandeza y ha llegado hasta el cielo, y tu dominio hasta los confines de la tierra.",
  23: "En cuanto a lo que vio el rey, un vigilante y santo que descendía del cielo y decía: “Cortad el árbol y destruidlo; mas la cepa de sus raíces dejaréis en la tierra, con atadura de hierro y de bronce en la hierba del campo; que lo empape el rocío del cielo, y con las bestias del campo sea su parte hasta que pasen sobre él siete tiempos”,",
  24: "ésta es la interpretación, oh rey, y la sentencia del Altísimo, que ha venido sobre mi señor, el rey:",
  25: "Que te echarán de entre los hombres y con las bestias del campo será tu habitación, con hierba del campo te apacentarán como a los bueyes y con el rocío del cielo serás bañado; y siete tiempos pasarán sobre ti, hasta que conozcas que el Altísimo tiene dominio en el reino de los hombres, y que lo da a quien él quiere.",
  26: "Y en cuanto a la orden de dejar en la tierra la cepa de las raíces del mismo árbol, significa que tu reino te quedará firme, después que reconozcas que es el cielo el que gobierna.",
  27: "Por tanto, oh rey, acepta mi consejo: redime tus pecados con justicia, y tus iniquidades haciendo misericordias con los oprimidos, pues tal vez será eso una prolongación de tu tranquilidad.",
  28: "Todo esto vino sobre el rey Nabucodonosor:",
  29: "Al cabo de doce meses, paseando por el palacio real de Babilonia,",
  30: "habló el rey y dijo: «¿No es ésta la gran Babilonia que yo edifiqué para casa real con la fuerza de mi poder, y para gloria de mi majestad?»",
  31: "Aún estaba la palabra en la boca del rey, cuando vino una voz del cielo: «A ti se te dice, rey Nabucodonosor: “El reino te ha sido quitado;",
  32: "de entre los hombres te arrojarán, con las bestias del campo será tu habitación y como a los bueyes te apacentarán; y siete tiempos pasarán sobre ti, hasta que reconozcas que el Altísimo tiene el dominio en el reino de los hombres, y lo da a quien él quiere.”»",
  33: "En la misma hora se cumplió la palabra sobre Nabucodonosor: Fue echado de entre los hombres, comía hierba como los bueyes y su cuerpo se empapaba del rocío del cielo, hasta que su pelo creció como plumas de águila y sus uñas como las de las aves.",
  34: "«Al fin del tiempo, yo, Nabucodonosor, alcé mis ojos al cielo y mi razón me fue devuelta; bendije al Altísimo, y alabé y glorifiqué al que vive para siempre: »“Su dominio es sempiterno; su reino, por todas las edades.",
  35: "Considerados como nada son los habitantes todos de la tierra; él hace según su voluntad en el ejército del cielo y en los habitantes de la tierra; no hay quien detenga su mano y le diga: ‘¿Qué haces?’”",
  36: "»En el mismo tiempo mi razón me fue devuelta, la majestad de mi reino, mi dignidad y mi grandeza volvieron a mí, y mis gobernadores y mis consejeros me buscaron; fui restablecido en mi reino, y mayor grandeza me fue añadida.",
  37: "»Ahora yo, Nabucodonosor, alabo, engrandezco y glorifico al Rey del cielo, porque todas sus obras son verdaderas y sus caminos justos; y él puede humillar a los que andan con soberbia.»",
 },
 d5: {
  1: "El rey Belsasar hizo un gran banquete a mil de sus príncipes, y en presencia de los mil bebía vino.",
  2: "Belsasar, con el gusto del vino, mandó que trajeran los vasos de oro y de plata que Nabucodonosor, su padre, había traído del templo de Jerusalén, para que bebieran de ellos el rey y sus grandes, sus mujeres y sus concubinas.",
  3: "Entonces trajeron los vasos de oro que habían traído del templo de la casa de Dios, que estaba en Jerusalén, y bebieron de ellos el rey y sus príncipes, sus mujeres y sus concubinas.",
  4: "Bebieron vino y alabaron a los dioses de oro y plata, de bronce, de hierro, de madera y de piedra.",
  5: "En aquella misma hora aparecieron los dedos de una mano de hombre que escribía delante del candelabro, sobre lo encalado de la pared del palacio real; y el rey veía la mano que escribía.",
  6: "Entonces el rey palideció y sus pensamientos lo turbaron, se debilitaron sus caderas y sus rodillas daban la una contra la otra.",
  7: "El rey gritó en alta voz que hicieran venir magos, caldeos y adivinos; y dijo el rey a los sabios de Babilonia: «Cualquiera que lea esta escritura y me dé su interpretación, será vestido de púrpura, llevará en su cuello un collar de oro y será el tercer señor en el reino.»",
  8: "Entonces fueron introducidos todos los sabios del rey, pero no pudieron leer la escritura ni dar al rey su interpretación.",
  9: "Entonces el rey Belsasar se turbó sobremanera y palideció, y sus príncipes estaban perplejos.",
  10: "La reina, por las palabras del rey y de sus príncipes, entró a la sala del banquete, y dijo: —¡Rey, vive para siempre! No te turben tus pensamientos ni palidezca tu rostro.",
  11: "En tu reino hay un hombre en el que mora el espíritu de los dioses santos, y en los días de tu padre se halló en él luz, inteligencia y sabiduría, como la sabiduría de los dioses. El rey Nabucodonosor, tu padre, oh rey, lo constituyó jefe sobre todos los magos, astrólogos, caldeos y adivinos,",
  12: "por cuanto en él se halló más espíritu, ciencia y entendimiento para interpretar sueños, descifrar enigmas y resolver dudas; esto es, en Daniel, al cual el rey puso por nombre Beltsasar. Llámese, pues, ahora a Daniel, y él te dará la interpretación.",
  13: "Entonces trajeron a Daniel ante el rey. Y dijo el rey a Daniel: —¿Eres tú aquel Daniel de los hijos de la cautividad de Judá, que mi padre trajo de Judea?",
  14: "Yo he oído de ti que el espíritu de los dioses santos está en ti, y que en ti se halló luz, entendimiento y mayor sabiduría.",
  15: "Y ahora trajeron ante mí sabios y astrólogos para que leyeran esta escritura y me dieran su interpretación; pero no han podido interpretarme el asunto.",
  16: "Yo, pues, he oído de ti que puedes interpretar y resolver dificultades. Si ahora puedes leer esta escritura y darme su interpretación, serás vestido de púrpura, llevarás en tu cuello un collar de oro y serás el tercer señor en el reino.",
  17: "Entonces Daniel respondió y dijo al rey: —Tus dones sean para ti; da tus recompensas a otros. Leeré la escritura al rey y le daré la interpretación.",
  18: "»El Altísimo Dios, oh rey, dio a Nabucodonosor, tu padre, el reino, la grandeza, la gloria y la majestad.",
  19: "Y por la grandeza que le dio, todos los pueblos, naciones y lenguas temblaban y temían delante de él. A quien le placía, mataba, y a quien le placía, daba vida; engrandecía a quien le placía, y a quien le placía, humillaba.",
  20: "Pero cuando su corazón se ensoberbeció y su espíritu se endureció en su orgullo, fue depuesto del trono de su reino y despojado de su gloria.",
  21: "Fue echado de entre los hijos de los hombres, su mente se hizo semejante a la de las bestias y con los asnos monteses fue su habitación. Le hicieron comer hierba, como al buey, y su cuerpo se empapó del rocío del cielo, hasta que reconoció que el Altísimo Dios tiene dominio sobre el reino de los hombres, y que pone sobre él al que le place.",
  22: "Pero tú, su hijo Belsasar, no has humillado tu corazón sabiendo todo esto,",
  23: "sino que contra el Señor del cielo te has ensoberbecido; hiciste traer ante ti los vasos de su Casa, y tú y tus grandes, tus mujeres y tus concubinas bebisteis vino de ellos; además diste alabanza a dioses de plata y oro, de bronce, de hierro, de madera y de piedra, que ni ven ni oyen ni saben; pero nunca honraste al Dios en cuya mano está tu vida y de quien son todos tus caminos.",
  24: "»Por eso, de su presencia envió él la mano que trazó esta escritura.",
  25: "Y la escritura que trazó es: “Mene, Mene, Tekel, Uparsin.”",
  26: "Ésta es la interpretación del asunto: “Mene”: Contó Dios tu reino y le ha puesto fin.",
  27: "“Tekel”: Pesado has sido en balanza y hallado falto.",
  28: "“Peres”: Tu reino ha sido roto y dado a los medos y a los persas.",
  29: "Entonces Belsasar mandó vestir a Daniel de púrpura, poner en su cuello un collar de oro y proclamar que él era el tercer señor del reino.",
  30: "La misma noche fue muerto Belsasar, rey de los caldeos.",
  31: "Y Darío, de Media, cuando tenía sesenta y dos años, tomó el reino.",
 },
 d6: {
  1: "Pareció bien a Darío constituir sobre el reino ciento veinte sátrapas que gobernaran en todo el reino.",
  2: "Y sobre ellos tres gobernadores, de los cuales Daniel era uno, a quienes estos sátrapas dieran cuenta, para que el rey no fuera perjudicado.",
  3: "Pero Daniel mismo era superior a estos sátrapas y gobernadores, porque había en él un espíritu superior; y el rey pensó en ponerlo sobre todo el reino.",
  4: "Los gobernadores y sátrapas buscaron ocasión para acusar a Daniel en lo relacionado con el reino; pero no podían hallar motivo alguno o falta, porque él era fiel, y ningún error ni falta hallaron en él.",
  5: "Entonces dijeron aquellos hombres: «No hallaremos contra este Daniel motivo alguno para acusarlo, si no lo hallamos contra él en relación con la ley de su Dios.»",
  6: "Entonces estos gobernadores y sátrapas se juntaron delante del rey, y le dijeron: —¡Rey Darío, para siempre vive!",
  7: "Todos los gobernadores del reino, magistrados, sátrapas, príncipes y capitanes han acordado por consejo que promulgues un edicto real, y lo confirmes, ordenando que cualquiera que en el espacio de treinta días demande petición de cualquier dios u hombre fuera de ti, rey, sea echado al foso de los leones.",
  8: "Ahora, pues, oh rey, confirma el edicto y fírmalo, para que no pueda ser revocado, conforme a la ley de Media y de Persia, que no puede ser abrogada.",
  9: "Firmó, pues, el rey Darío el edicto y la prohibición.",
  10: "Cuando Daniel supo que el edicto había sido firmado, entró en su casa; abiertas las ventanas de su habitación que daban a Jerusalén, se arrodillaba tres veces al día, oraba y daba gracias delante de su Dios como solía hacerlo antes.",
  11: "Se juntaron entonces aquellos hombres, y hallaron a Daniel orando y rogando en presencia de su Dios.",
  12: "Fueron luego ante el rey y le hablaron del edicto real: —¿No has confirmado un edicto ordenando que cualquiera que en el espacio de treinta días pida a cualquier dios u hombre fuera de ti, rey, sea echado al foso de los leones? Respondió el rey diciendo: —Verdad es, conforme a la ley de Media y de Persia, que no puede ser abrogada.",
  13: "Entonces respondieron y dijeron delante del rey: —Daniel, que es de los hijos de los cautivos de Judá, no te respeta a ti, rey, ni acata el edicto que confirmaste, sino que tres veces al día hace su petición.",
  14: "Cuando el rey oyó el asunto, le pesó en gran manera y resolvió librar a Daniel; y hasta la puesta del sol trabajó para librarlo.",
  15: "Pero aquellos hombres rodearon al rey y le dijeron: —Sabes, oh rey, que es ley de Media y de Persia que ningún edicto u ordenanza que el rey confirme puede ser abrogado.",
  16: "Entonces el rey ordenó que trajeran a Daniel, y lo echaron al foso de los leones. El rey dijo a Daniel: —El Dios tuyo, a quien tú continuamente sirves, él te libre.",
  17: "Trajeron una piedra y la pusieron sobre la puerta del foso, la cual selló el rey con su anillo y con el anillo de sus príncipes, para que el acuerdo acerca de Daniel no se cambiara.",
  18: "Luego el rey se fue a su palacio, y se acostó en ayunas; no trajeron ante él instrumentos musicales, y se le fue el sueño.",
  19: "El rey se levantó muy de mañana, y fue apresuradamente al foso de los leones.",
  20: "Acercándose al foso, llamó a gritos a Daniel con voz triste, y le dijo: —Daniel, siervo del Dios viviente, el Dios tuyo, a quien tú continuamente sirves, ¿te ha podido librar de los leones?",
  21: "Entonces Daniel respondió al rey: —¡Rey, vive para siempre!",
  22: "Mi Dios envió su ángel, el cual cerró la boca de los leones para que no me hicieran daño, porque ante él fui hallado inocente; y aun delante de ti, oh rey, yo no he hecho nada malo.",
  23: "Se alegró el rey en gran manera a causa de él, y mandó sacar a Daniel del foso. Sacaron, pues, del foso a Daniel, pero ninguna lesión se halló en él, porque había confiado en su Dios.",
  24: "Luego ordenó el rey que trajeran a aquellos hombres que habían acusado a Daniel, y fueron echados al foso de los leones ellos, sus hijos y sus mujeres; y aún no habían llegado al fondo del foso, cuando los leones se apoderaron de ellos y quebraron todos sus huesos.",
  25: "Entonces el rey Darío escribió a todos los pueblos, naciones y lenguas que habitan en toda la tierra: «Paz os sea multiplicada.",
  26: "De parte mía es promulgada esta ordenanza: “Que en todo el dominio de mi reino, todos teman y tiemblen ante la presencia del Dios de Daniel. »”Porque él es el Dios viviente y permanece por todos los siglos, su reino no será jamás destruido y su dominio perdurará hasta el fin.",
  27: "Él salva y libra, y hace señales y maravillas en el cielo y en la tierra; él ha librado a Daniel del poder de los leones.”»",
  28: "Daniel prosperó durante los reinados de Darío y de Ciro, el persa.",
 },
};

module.exports = { VERS };
