/* matutina-extra.js — NO EDITAR A MANO.
   Lo escribe tools/creencias/gen_matutina2.py.

   POR QUE EXISTE
   La matutina tenia cinco preguntas por dia, contra cuarenta y seis por
   capitulo en Daniel. Era la actividad mas floja del banco y el examen no la
   califica mas suave por ser corta.

   Las preguntas se CRUZAN de dos tablas que ya estaban publicadas en la app
   (los 31 versiculos con su referencia, y quien es quien dia por dia). No se
   inventa contenido: se convierte en pregunta lo que ya estaba escrito. */

const MAT_EXTRA = [
  {cap:"m01",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 1 de octubre?",
   o:["Lucas 12:15", "Salmo 113:7", "1 Juan 5:15", "2 Timoteo 2:21 (NTV)"],a:0},
  {cap:"m01",t:"mc",nv:2,q:"¿De qué día es este versículo? «Cuídense ustedes de toda avaricia; porque la vida no depende del poseer muchas cosas»",
   o:["1.º de octubre", "2 de octubre", "3 de octubre", "4 de octubre"],a:0},
  {cap:"m01",t:"mc",nv:1,q:"En «El villano pirata Dienterroto» (día 1), ¿quién es?",
   o:["Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha", "Héroes: el profesor Elisha y un desconocido"],a:0},
  {cap:"m01",t:"tf",q:"El día 1 de octubre, «El villano pirata Dienterroto», presenta a un VILLANO.",a:true,
   e:"Correcto. Villano: el pirata Dienterroto."},
  {cap:"m02",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 2 de octubre?",
   o:["Salmo 113:7", "Lucas 12:15", "1 Juan 5:15", "2 Timoteo 2:21 (NTV)"],a:0},
  {cap:"m02",t:"mc",nv:2,q:"¿De qué día es este versículo? «El Señor levanta del suelo al pobre, y saca del lugar más bajo al necesitado»",
   o:["2 de octubre", "1 de octubre", "3 de octubre", "4 de octubre"],a:0},
  {cap:"m02",t:"mc",nv:1,q:"En «El héroe sabe que Dios lo levanta» (día 2), ¿quién es?",
   o:["Un experimento con dos huevos", "Villano: el pirata Dienterroto", "Héroe: el profesor Elisha", "Héroes: el profesor Elisha y un desconocido"],a:0},
  {cap:"m03",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 3 de octubre?",
   o:["1 Juan 5:15", "Lucas 12:15", "Salmo 113:7", "2 Timoteo 2:21 (NTV)"],a:0},
  {cap:"m03",t:"mc",nv:2,q:"¿De qué día es este versículo? «Así como sabemos que Dios oye nuestras oraciones, también sabemos que ya tenemos lo que le hemos pedido»",
   o:["3 de octubre", "1 de octubre", "2 de octubre", "4 de octubre"],a:0},
  {cap:"m03",t:"mc",nv:1,q:"En «El héroe que dio 5 kinas» (día 3), ¿quién es?",
   o:["Héroe: el profesor Elisha", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroes: el profesor Elisha y un desconocido"],a:0},
  {cap:"m03",t:"tf",q:"El día 3 de octubre, «El héroe que dio 5 kinas», presenta a un VILLANO.",a:false,
   e:"Falso. Héroe: el profesor Elisha."},
  {cap:"m04",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 4 de octubre?",
   o:["2 Timoteo 2:21 (NTV)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m04",t:"mc",nv:2,q:"¿De qué día es este versículo? «Si te mantienes puro, serás un utensilio especial para uso honorable. Tu vida será limpia, y estarás listo para que el Maestro te use en toda buena ob»",
   o:["4 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m04",t:"mc",nv:1,q:"En «El héroe que ayudaba a jóvenes estudiantes» (día 4), ¿quién es?",
   o:["Héroes: el profesor Elisha y un desconocido", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m04",t:"tf",q:"El día 4 de octubre, «El héroe que ayudaba a jóvenes estudiantes», presenta a un VILLANO.",a:false,
   e:"Falso. Héroes: el profesor Elisha y un desconocido."},
  {cap:"m05",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 5 de octubre?",
   o:["1 Timoteo 2:4", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m05",t:"mc",nv:2,q:"¿De qué día es este versículo? «[Dios] quiere que todos se salven»",
   o:["5 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m05",t:"mc",nv:1,q:"En «Estás invitado a la boda» (día 5), ¿quién es?",
   o:["Las bodas de Papúa Nueva Guinea", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m06",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 6 de octubre?",
   o:["Isaías 41:10", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m06",t:"mc",nv:2,q:"¿De qué día es este versículo? «No temas, pues yo soy tu Dios. Yo te doy fuerzas, yo te ayudo, yo te sostengo con mi mano victoriosa»",
   o:["6 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m06",t:"mc",nv:1,q:"En «Nunca estás solo» (día 6), ¿quién es?",
   o:["Sophie y su mamá", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m07",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 7 de octubre?",
   o:["1 Tesalonicenses 5:18", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m07",t:"mc",nv:2,q:"¿De qué día es este versículo? «Den gracias a Dios por todo, porque esto es lo que él quiere de ustedes como creyentes en Cristo Jesús»",
   o:["7 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m07",t:"mc",nv:1,q:"En «Una joven heroína alienta a los tripulantes» (día 7), ¿quién es?",
   o:["Heroína: Sophie", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m07",t:"tf",q:"El día 7 de octubre, «Una joven heroína alienta a los tripulantes», presenta a un VILLANO.",a:false,
   e:"Falso. Heroína: Sophie."},
  {cap:"m08",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 8 de octubre?",
   o:["Hechos 1:8", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m08",t:"mc",nv:2,q:"¿De qué día es este versículo? «Cuando el Espíritu Santo venga sobre ustedes, recibirán poder y saldrán a dar testimonio de mí [...] hasta en las partes más lejanas de la tierra»",
   o:["8 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m08",t:"mc",nv:1,q:"En «El poder del héroe» (día 8), ¿quién es?",
   o:["Héroe: Unia Api", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m08",t:"tf",q:"El día 8 de octubre, «El poder del héroe», presenta a un VILLANO.",a:false,
   e:"Falso. Héroe: Unia Api."},
  {cap:"m09",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 9 de octubre?",
   o:["2 Timoteo 4:2", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m09",t:"mc",nv:2,q:"¿De qué día es este versículo? «Tú anuncia el mensaje de Dios en todo momento»",
   o:["9 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m09",t:"mc",nv:1,q:"En «El héroe narrador de historias» (día 9), ¿quién es?",
   o:["Héroe: Unia", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m09",t:"tf",q:"El día 9 de octubre, «El héroe narrador de historias», presenta a un VILLANO.",a:false,
   e:"Falso. Héroe: Unia."},
  {cap:"m10",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 10 de octubre?",
   o:["Cantares 2:2", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m10",t:"mc",nv:2,q:"¿De qué día es este versículo? «Mi amada es, entre las mujeres, como una rosa entre los espinos»",
   o:["10 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m10",t:"mc",nv:1,q:"En «El héroe se enamora — 1.ª parte» (día 10), ¿quién es?",
   o:["Unia y Julie", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m11",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 11 de octubre?",
   o:["Proverbios 16:9", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m11",t:"mc",nv:2,q:"¿De qué día es este versículo? «Al hombre le toca hacer planes, y al Señor dirigir sus pasos»",
   o:["11 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m11",t:"mc",nv:1,q:"En «El héroe se enamora — 2.ª parte» (día 11), ¿quién es?",
   o:["Unia y Julie", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m12",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 12 de octubre?",
   o:["Filipenses 3:14 (PDT)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m12",t:"mc",nv:2,q:"¿De qué día es este versículo? «Sigo hacia la meta para ganar el premio que Dios me ofreció cuando me llamó por medio de Jesucristo»",
   o:["12 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m12",t:"mc",nv:1,q:"En «La pequeña gran mujer» (día 12), ¿quién es?",
   o:["Heroína: Gladys Aylward", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m12",t:"tf",q:"El día 12 de octubre, «La pequeña gran mujer», presenta a un VILLANO.",a:false,
   e:"Falso. Heroína: Gladys Aylward."},
  {cap:"m13",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 13 de octubre?",
   o:["Proverbios 31:10 (RV95)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m13",t:"mc",nv:2,q:"¿De qué día es este versículo? «Mujer virtuosa, ¿quién la hallará? Su valor sobrepasa largamente al de las piedras preciosas»",
   o:["13 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m13",t:"mc",nv:1,q:"En «Mujer virtuosa» (día 13), ¿quién es?",
   o:["Heroína: Gladys Aylward", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m13",t:"tf",q:"El día 13 de octubre, «Mujer virtuosa», presenta a un VILLANO.",a:false,
   e:"Falso. Heroína: Gladys Aylward."},
  {cap:"m14",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 14 de octubre?",
   o:["Gálatas 1:10", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m14",t:"mc",nv:2,q:"¿De qué día es este versículo? «Yo no busco la aprobación de los hombres, sino la aprobación de Dios»",
   o:["14 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m14",t:"mc",nv:1,q:"En «No me arrepiento» (día 14), ¿quién es?",
   o:["Heroína: Gladys Aylward", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m14",t:"tf",q:"El día 14 de octubre, «No me arrepiento», presenta a un VILLANO.",a:false,
   e:"Falso. Heroína: Gladys Aylward."},
  {cap:"m15",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 15 de octubre?",
   o:["Marcos 5:19", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m15",t:"mc",nv:2,q:"¿De qué día es este versículo? «Vete a tu casa, con tus parientes, y cuéntales todo lo que el Señor te ha hecho, y cómo ha tenido compasión de ti»",
   o:["15 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m15",t:"mc",nv:1,q:"En «Testigos de Jesús» (día 15), ¿quién es?",
   o:["Tres personajes de la Biblia", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m16",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 16 de octubre?",
   o:["Filipenses 4:3", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m16",t:"mc",nv:2,q:"¿De qué día es este versículo? «Sus nombres ya están escritos en el libro de la vida»",
   o:["16 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m16",t:"mc",nv:1,q:"En «Héroes anónimos» (día 16), ¿quién es?",
   o:["Los cristianos de los primeros siglos", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m17",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 17 de octubre?",
   o:["Salmo 120:2", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m17",t:"mc",nv:2,q:"¿De qué día es este versículo? «Señor, líbrame de los labios mentirosos y de la lengua embustera»",
   o:["17 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m17",t:"mc",nv:1,q:"En «El amigo villano» (día 17), ¿quién es?",
   o:["Villano: Axel", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m17",t:"tf",q:"El día 17 de octubre, «El amigo villano», presenta a un VILLANO.",a:true,
   e:"Correcto. Villano: Axel."},
  {cap:"m18",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 18 de octubre?",
   o:["Josué 1:9", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m18",t:"mc",nv:2,q:"¿De qué día es este versículo? «Yo soy quien te manda que tengas valor y firmeza. No tengas miedo ni te desanimes porque yo, tu Señor y Dios, estaré contigo dondequiera que vayas»",
   o:["18 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m18",t:"mc",nv:1,q:"En «¿Héroes o no?» (día 18), ¿quién es?",
   o:["Marcos, Ana y Lucía, Mónica y Ester", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m19",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 19 de octubre?",
   o:["Juan 14:3", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m19",t:"mc",nv:2,q:"¿De qué día es este versículo? «Después de irme y de prepararles un lugar, vendré otra vez para llevarlos conmigo, para que ustedes estén en el mismo lugar en donde yo voy a estar»",
   o:["19 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m19",t:"mc",nv:1,q:"En «Di siempre dónde estás» (día 19), ¿quién es?",
   o:["El señor McMullen", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m20",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 20 de octubre?",
   o:["Filipenses 4:8", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m20",t:"mc",nv:2,q:"¿De qué día es este versículo? «Piensen en todo lo verdadero, en todo lo que es digno de respeto, en todo lo recto, en todo lo puro»",
   o:["20 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m20",t:"mc",nv:1,q:"En «El villano del baloncesto» (día 20), ¿quién es?",
   o:["Villano: Tim Donaghy", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m20",t:"tf",q:"El día 20 de octubre, «El villano del baloncesto», presenta a un VILLANO.",a:true,
   e:"Correcto. Villano: Tim Donaghy."},
  {cap:"m21",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 21 de octubre?",
   o:["Salmo 71:17", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m21",t:"mc",nv:2,q:"¿De qué día es este versículo? «Dios mío, tú me has enseñado desde mi juventud»",
   o:["21 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m21",t:"mc",nv:1,q:"En «Tus maestros son héroes» (día 21), ¿quién es?",
   o:["Los maestros", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m22",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 22 de octubre?",
   o:["Lucas 2:46-47", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m22",t:"mc",nv:2,q:"¿De qué día es este versículo? «Sentado [Jesús] entre los maestros de la ley, [...] todos los que lo oían se admiraban de su inteligencia y de sus respuestas»",
   o:["22 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m22",t:"mc",nv:1,q:"En «Jesús: el Maestro de los maestros» (día 22), ¿quién es?",
   o:["Jesús a los doce años", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m23",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 23 de octubre?",
   o:["Isaías 52:7 (TLA)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m23",t:"mc",nv:2,q:"¿De qué día es este versículo? «¡Qué hermoso es ver al que llega por las colinas trayendo buenas noticias: noticias de paz, noticias de salvación»",
   o:["23 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m23",t:"mc",nv:1,q:"En «Héroes de ayer y de hoy» (día 23), ¿quién es?",
   o:["Los mensajeros", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m24",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 24 de octubre?",
   o:["Gálatas 5:16-17 (TLA)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m24",t:"mc",nv:2,q:"¿De qué día es este versículo? «Obedezcan al Espíritu de Dios, y así no desearán hacer lo malo. [...] Ustedes no pueden hacer lo que se les antoje»",
   o:["24 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m24",t:"mc",nv:1,q:"En «El villano que maltrató a un animal» (día 24), ¿quién es?",
   o:["Villano: Balaam", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m24",t:"tf",q:"El día 24 de octubre, «El villano que maltrató a un animal», presenta a un VILLANO.",a:true,
   e:"Correcto. Villano: Balaam."},
  {cap:"m25",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 25 de octubre?",
   o:["Proverbios 14:29 (NBV)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m25",t:"mc",nv:2,q:"¿De qué día es este versículo? «El que controla su enojo es muy inteligente»",
   o:["25 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m25",t:"mc",nv:1,q:"En «Fernando, el niño enojado» (día 25), ¿quién es?",
   o:["Fernando", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m26",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 26 de octubre?",
   o:["Proverbios 12:25 (NBV)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m26",t:"mc",nv:2,q:"¿De qué día es este versículo? «La angustia desalienta el corazón del hombre, pero una palabra alentadora lo anima»",
   o:["26 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m26",t:"mc",nv:1,q:"En «La heroína que ayudó a un niño con sus palabras» (día 26), ¿quién es?",
   o:["Heroína: Emely", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m26",t:"tf",q:"El día 26 de octubre, «La heroína que ayudó a un niño con sus palabras», presenta a un VILLANO.",a:false,
   e:"Falso. Heroína: Emely."},
  {cap:"m27",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 27 de octubre?",
   o:["Santiago 3:15 (NTV)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m27",t:"mc",nv:2,q:"¿De qué día es este versículo? «La envidia y el egoísmo no forman parte de la sabiduría que proviene de Dios»",
   o:["27 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m27",t:"mc",nv:1,q:"En «El niño que se quedó sentado en el banquillo» (día 27), ¿quién es?",
   o:["Víctor", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m28",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 28 de octubre?",
   o:["Hechos 10:34 (NTV)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m28",t:"mc",nv:2,q:"¿De qué día es este versículo? «Veo con claridad que Dios no muestra favoritismo»",
   o:["28 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m28",t:"mc",nv:1,q:"En «Un héroe diferente» (día 28), ¿quién es?",
   o:["Héroe: Pablo Pineda", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m28",t:"tf",q:"El día 28 de octubre, «Un héroe diferente», presenta a un VILLANO.",a:false,
   e:"Falso. Héroe: Pablo Pineda."},
  {cap:"m29",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 29 de octubre?",
   o:["Filipenses 4:19 (LBLA)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m29",t:"mc",nv:2,q:"¿De qué día es este versículo? «Mi Dios proveerá a todas vuestras necesidades»",
   o:["29 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m29",t:"mc",nv:1,q:"En «Dios provee» (día 29), ¿quién es?",
   o:["Héroe: Charles Tindley", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m29",t:"tf",q:"El día 29 de octubre, «Dios provee», presenta a un VILLANO.",a:false,
   e:"Falso. Héroe: Charles Tindley."},
  {cap:"m30",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 30 de octubre?",
   o:["Proverbios 29:11 (NVI)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m30",t:"mc",nv:2,q:"¿De qué día es este versículo? «El necio da rienda suelta a su ira, pero el sabio sabe dominarla»",
   o:["30 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m30",t:"mc",nv:1,q:"En «Nabal, el villano necio» (día 30), ¿quién es?",
   o:["Villano: Nabal", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m30",t:"tf",q:"El día 30 de octubre, «Nabal, el villano necio», presenta a un VILLANO.",a:true,
   e:"Correcto. Villano: Nabal."},
  {cap:"m31",t:"mc",nv:1,q:"¿Cuál es la referencia del versículo del día 31 de octubre?",
   o:["Proverbios 15:1 (RVC)", "Lucas 12:15", "Salmo 113:7", "1 Juan 5:15"],a:0},
  {cap:"m31",t:"mc",nv:2,q:"¿De qué día es este versículo? «La respuesta amable calma la ira; la respuesta grosera aumenta el enojo»",
   o:["31 de octubre", "1 de octubre", "2 de octubre", "3 de octubre"],a:0},
  {cap:"m31",t:"mc",nv:1,q:"En «La sabia Abigail» (día 31), ¿quién es?",
   o:["Heroína: Abigail", "Villano: el pirata Dienterroto", "Un experimento con dos huevos", "Héroe: el profesor Elisha"],a:0},
  {cap:"m31",t:"tf",q:"El día 31 de octubre, «La sabia Abigail», presenta a un VILLANO.",a:false,
   e:"Falso. Heroína: Abigail."},
];

if (typeof module !== "undefined") module.exports = { MAT_EXTRA };
