/* Preguntas de completar para los capitulos de Profetas y Reyes que no tenian.

   EL HUECO
   De los seis capitulos de P&R, solo pr39, pr41 y pr44 traian preguntas de
   completar; pr40, pr42 y pr43 no tenian ninguna. El examen real trae su
   seccion de completar y no distingue de que capitulo salio la pregunta.

   DE DONDE SALEN LAS FRASES
   De «Profetas y Reyes», files/profetas-y-reyes.pdf, capitulos 40, 42 y 43.
   Se transcriben tal como estan en el libro, con su ortografia («fué»), igual
   que las que ya existian para pr39. Las comillas angulares se reservan en
   este proyecto para lo verificable, y estas lo son: salen del libro. */

const BANCO_PR = [

/* ─────── P&R 40 — El sueño de Nabucodonosor ─────── */
{cap:'pr40',t:'fill',ins:'Profetas y Reyes, cap. 40 — Completa la frase sobre el poder de los gobernantes:',
 p:[{x:'«El poder ejercido por todo gobernante de la tierra es '},{b:'impartido',h:'¿de dónde viene?'},
    {x:' del Cielo; y del uso que hace de este poder el tal gobernante, depende su '},
    {b:'éxito',h:'¿de qué depende?'},{x:'.»'}]},
{cap:'pr40',t:'fill',ins:'Profetas y Reyes, cap. 40 — Completa la frase sobre lo que Dios iba a revelar:',
 p:[{x:'«Dios iba a revelarle que él ejerce el poder sobre los reinos del mundo, el poder de '},
    {b:'entronizar',h:'¿poder de qué?'},{x:' y de '},{b:'destronar',h:'¿y de qué?'},{x:' a los reyes.»'}]},

/* ─────── P&R 42 — La verdadera grandeza ─────── */
{cap:'pr42',t:'fill',ins:'Profetas y Reyes, cap. 42 — Completa la frase sobre en qué falló el rey:',
 p:[{x:'«Endureciendo su corazón, usó los '},{b:'talentos',h:'¿qué usó mal?'},
    {x:' que Dios le había dado para '},{b:'glorificarse',h:'¿para qué?'},
    {x:' a sí mismo, y para ensalzarse sobre el Dios que le había dado la vida y el poder.»'}]},
{cap:'pr42',t:'fill',ins:'Profetas y Reyes, cap. 42 — Completa la frase sobre su restauración:',
 p:[{x:'«Al cabo de ese tiempo, la razón le fué devuelta, y mirando con '},
    {b:'humildad',h:'¿cómo miró?'},{x:' hacia el Dios del cielo, reconoció en su '},
    {b:'castigo',h:'¿en qué reconoció la mano divina?'},{x:' la intervención de la mano divina.»'}]},

/* ─────── P&R 43 — El vigía invisible ─────── */
{cap:'pr43',t:'fill',ins:'Profetas y Reyes, cap. 43 — Completa la frase sobre lo que Dios había intentado:',
 p:[{x:'«Mediante múltiples '},{b:'providencias',h:'¿mediante qué?'},
    {x:', Dios había procurado enseñarles a '},{b:'reverenciar',h:'¿a qué?'},{x:' su ley.»'}]},
{cap:'pr43',t:'fill',ins:'Profetas y Reyes, cap. 43 — Completa la frase sobre la noche del banquete:',
 p:[{x:'«Como en visión '},{b:'panorámica',h:'¿cómo desfilaron?'},
    {x:' desfilaron ante sus ojos los actos de su vida impía; les pareció estar emplazados ante el '},
    {b:'tribunal',h:'¿ante qué?'},{x:' del Dios eterno, cuyo poder acababan de desafiar.»'}]},


/* ─── v133: Profetas y Reyes 39 a 44, parte por parte ───
   Camilo pidió que P&R cubra todas las enseñanzas principales. Cada
   capítulo se partió en las partes de la historia (texto de EGW Writings,
   libro 217) y estas preguntas cubren las que no tenían ninguna. Cada una
   se respalda con una frase literal del capítulo, verificada por script;
   la referencia PR va en el comentario de la línea. */

/* ── P&R 39 ── */
{"cap": "pr39", "t": "mc", "q": "Según P&R cap. 39, ¿qué nombre le pusieron a Daniel en Babilonia?", "o": ["Beltsasar", "Sadrach", "Mesach", "Abednego"], "a": 0, "e": "A Daniel le pusieron Beltsasar; Sadrach, Mesach y Abednego fueron los nombres de sus tres compañeros."},  // PR 352.3
{"cap": "pr39", "t": "mc", "q": "Según P&R cap. 39, ¿cuántos días duró la prueba que pidió Daniel?", "o": ["Tres días", "Siete días", "Diez días", "Cuarenta días"], "a": 2, "e": "Daniel pidió una prueba de diez días con alimento sencillo."},  // PR 354.4
{"cap": "pr39", "t": "tf", "q": "Según P&R cap. 39, al final de los diez días los jóvenes hebreos se veían más débiles que los que comían la comida del rey.", "a": false, "e": "Es falso: se veían mejor y más nutridos que los otros muchachos."},  // PR 355.1
{"cap": "pr39", "t": "mc", "q": "Según P&R cap. 39, ¿qué propósito tenía Dios con los hebreos fieles en la tierra del cautiverio?", "o": ["Que dieran a las naciones paganas el conocimiento de Jehová", "Que aprendieran la sabiduría de los caldeos para volver a Judá", "Que se ganaran el favor del rey para liberar a su pueblo", "Que vivieran apartados de los babilonios sin hablar con ellos"], "a": 0, "e": "Habían de ser representantes de Dios y llevar a los paganos el conocimiento de Jehová."},  // PR 351.1
{"cap": "pr39", "t": "fill", "ins": "Profetas y Reyes, cap. 39 — Completa la frase del libro sobre los hebreos fieles:", "p": [{"x": "«Honraron a Dios en la prosperidad y en la "}, {"b": "adversidad", "h": "¿qué palabra falta?"}, {"x": "; y Dios los "}, {"b": "honró", "h": "¿qué palabra falta?"}, {"x": " a ellos.»"}]},  // PR 351.1
{"cap": "pr39", "t": "mc", "q": "Según P&R cap. 39, ¿qué apreciaba Daniel más que el favor del rey?", "o": ["La aprobación de Dios", "La amistad de Aspenaz", "Su puesto en el palacio", "Los estudios de los caldeos"], "a": 0, "e": "Apreciaba más la aprobación de Dios que el favor del rey, y aun más que la vida misma."},  // PR 354.1
{"cap": "pr39", "t": "mc", "q": "Según P&R cap. 39, en el examen del rey, ¿cuántas veces mejores que sus magos y astrólogos halló a los cuatro jóvenes?", "o": ["Dos veces", "Siete veces", "Diez veces", "Cien veces"], "a": 2, "e": "El rey los halló diez veces mejores que todos los magos y astrólogos de su reino."},  // PR 356.1
{"cap": "pr39", "t": "mc", "q": "Según P&R cap. 39, ¿qué entendimiento especial le dio Dios a Daniel, además del conocimiento que dio a los cuatro?", "o": ["Entendimiento en toda visión y sueños", "Entendimiento en las leyes de los persas", "Entendimiento en la guerra y las armas", "Entendimiento en la medicina de Babilonia"], "a": 0, "e": "A los cuatro Dios les dio conocimiento; Daniel además tuvo entendimiento en toda visión y sueños."},  // PR 355.3
{"cap": "pr39", "t": "fill", "ins": "Profetas y Reyes, cap. 39 — Completa la frase del libro sobre el verdadero éxito:", "p": [{"x": "«Dios da las "}, {"b": "oportunidades", "h": "¿qué palabra falta?"}, {"x": "; el éxito depende del "}, {"b": "uso", "h": "¿qué palabra falta?"}, {"x": " que se haga de ellas.»"}]},  // PR 357.1
{"cap": "pr39", "t": "tf", "q": "Según P&R cap. 39, la gracia de Dios se nos da para reemplazar nuestro esfuerzo.", "a": false, "e": "Es falso: la gracia obra en nosotros el querer y el hacer, nunca para reemplazar nuestro esfuerzo. Debemos hacer nuestra parte."},  // PR 357.2

/* ── P&R 40 ── */
{"cap": "pr40", "t": "mc", "q": "Según P&R cap. 40, cuando los magos dijeron que nadie podía declarar el sueño, ¿quiénes dijeron que sí podrían?", "o": ["Solo los dioses cuya morada no es con la carne", "Solo los astrólogos más ancianos de Caldea", "Solo el rey, si recordaba su propio sueño", "Solo los sacerdotes del templo de Babilonia"], "a": 0, "e": "Los magos dijeron que solo los dioses, cuya morada no es con la carne, podían declararlo."},  // PR 362.1
{"cap": "pr40", "t": "mc", "q": "Según P&R cap. 40, ¿quién era Arioc?", "o": ["El capitán de la guardia del rey", "El jefe de los magos de Babilonia", "El príncipe de los eunucos", "Uno de los tres amigos de Daniel"], "a": 0, "e": "Arioc era el capitán de la guardia del rey, encargado de cumplir el decreto."},  // PR 362.3
{"cap": "pr40", "t": "mc", "q": "Según P&R cap. 40, ¿qué le pidió Daniel al rey antes de conocer el sueño?", "o": ["Tiempo para rogar a su Dios que le revelase el sueño", "Que perdonara primero a los magos y astrólogos", "Que le contara al menos una parte de lo que soñó", "Que lo dejara consultar los libros de los caldeos"], "a": 0, "e": "Daniel pidió tiempo para orar a su Dios, que le revelaría el sueño y su interpretación."},  // PR 362.3
{"cap": "pr40", "t": "mc", "q": "Según P&R cap. 40, ¿qué pasó con la piedra que golpeó la imagen?", "o": ["Se hizo un gran monte que llenó toda la tierra", "Se partió en pedazos junto con la imagen", "El viento se la llevó como el tamo", "Quedó enterrada a los pies de la imagen"], "a": 0, "e": "La piedra se convirtió en un gran monte que llenó toda la tierra. Lo que el viento se llevó fueron los pedazos de la imagen."},  // PR 364.3
{"cap": "pr40", "t": "mc", "q": "Según P&R cap. 40, ¿quién era la cabeza de oro de la imagen?", "o": ["Nabucodonosor", "Daniel", "El cuarto reino", "El reino del Dios del cielo"], "a": 0, "e": "Daniel le dijo a Nabucodonosor: «tú eres aquella cabeza de oro»."},  // PR 365.1
{"cap": "pr40", "t": "tf", "q": "Según P&R cap. 40, el reino que levantará el Dios del cielo será dejado después a otro pueblo.", "a": false, "e": "Es falso: ese reino nunca será destruido, no será dejado a otro pueblo y permanecerá para siempre."},  // PR 365.5
{"cap": "pr40", "t": "fill", "ins": "Profetas y Reyes, cap. 40 — Completa lo que dijo el rey después de oír la interpretación:", "p": [{"x": "«Ciertamente que el Dios vuestro es Dios de "}, {"b": "dioses", "h": "¿qué palabra falta?"}, {"x": ", y el Señor de los "}, {"b": "reyes", "h": "¿qué palabra falta?"}, {"x": "»"}]},  // PR 365.6
{"cap": "pr40", "t": "mc", "q": "Según P&R cap. 40, ¿qué cargo le dio el rey a Daniel?", "o": ["Gobernador de toda la provincia de Babilonia", "Capitán de la guardia del rey", "Jefe de los eunucos del palacio", "Sacerdote mayor del templo"], "a": 0, "e": "Lo puso por gobernador de toda la provincia de Babilonia y jefe de todos los sabios; además revocó el decreto contra los magos."},  // PR 365.7
{"cap": "pr40", "t": "mc", "q": "Según P&R cap. 40, ¿por qué desapareció finalmente Babilonia?", "o": ["Porque en la prosperidad sus gobernantes se creyeron independientes de Dios", "Porque sus ejércitos no tenían suficiente hierro para las armas", "Porque sus magos no supieron interpretar el sueño del rey", "Porque Daniel dejó de servir como gobernador de la provincia"], "a": 0, "e": "Cayó porque, en tiempos de prosperidad, sus gobernantes se consideraron independientes de Dios y atribuyeron la gloria a hazañas humanas."},  // PR 367.3
{"cap": "pr40", "t": "fill", "ins": "Profetas y Reyes, cap. 40 — Completa la frase final del capítulo sobre la fuerza de las naciones y de las personas:", "p": [{"x": "«Se mide por la "}, {"b": "fidelidad", "h": "¿qué palabra falta?"}, {"x": " con que cumplen el "}, {"b": "propósito", "h": "¿qué palabra falta?"}, {"x": " de Dios.»"}]},  // PR 368.3

/* ── P&R 41 ── */
{"cap": "pr41", "t": "mc", "q": "Según P&R cap. 41, ¿qué medidas tenía la estatua de oro de Dura?", "o": ["Sesenta codos de alto y seis de ancho", "Seis codos de alto y sesenta de ancho", "Setenta codos de alto y siete de ancho", "Cien codos de alto y diez de ancho"], "a": 0, "e": "El libro dice que medía sesenta codos de altura y seis de anchura."},  // PR 371.1
{"cap": "pr41", "t": "mc", "q": "Según P&R cap. 41, ¿qué propósito de Dios esperaba derrotar Satanás con el culto a la imagen de oro?", "o": ["Que Israel cautivo fuera una bendición para las naciones paganas", "Que Daniel llegara a ser gobernador de toda Babilonia", "Que el templo de Jerusalén fuera reconstruido pronto", "Que Nabucodonosor dejara de conquistar otras naciones"], "a": 0, "e": "Satanás quería impedir que la presencia de Israel en Babilonia bendijera a todas las naciones paganas."},  // PR 371.2
{"cap": "pr41", "t": "fill", "ins": "Profetas y Reyes, cap. 41 — Completa lo que sabía el enemigo de la humanidad:", "p": [{"x": "«El enemigo de la humanidad sabía que la verdad sin mezcla de "}, {"b": "error", "h": "¿qué palabra falta?"}, {"x": " es un gran poder para "}, {"b": "salvar", "h": "¿qué palabra falta?"}, {"x": "»"}]},  // PR 370.3
{"cap": "pr41", "t": "mc", "q": "Según P&R cap. 41, ¿por qué ciertos sabios acusaron a Sadrach, Mesach y Abed-nego ante el rey?", "o": ["Por celos de los honores que se les habían dado", "Porque Daniel les pidió que los vigilaran de cerca", "Porque el rey les ofreció oro por cada acusado", "Porque querían quedarse con la estatua de oro"], "a": 0, "e": "Los acusadores estaban celosos de los honores concedidos a los compañeros de Daniel."},  // PR 372.1
{"cap": "pr41", "t": "tf", "q": "Según P&R cap. 41, el rey les dio a los tres hebreos otra oportunidad porque habían sido fieles en el cumplimiento de todos sus deberes.", "a": true, "e": "Verdadero. El rey notó que tenían algo que los otros sabios no tenían y que habían cumplido fielmente sus deberes; por eso les dio otra oportunidad."},  // PR 372.3
{"cap": "pr41", "t": "mc", "q": "Según P&R cap. 41, ¿qué habían aprendido los tres jóvenes de la historia de sus padres?", "o": ["Que desobedecer a Dios trae deshonor, desastre y muerte", "Que los reyes de Babilonia siempre cumplen su palabra", "Que Dios libra del fuego a todo el que ora con fe", "Que era mejor callar delante de los reyes paganos"], "a": 0, "e": "De la historia de sus padres aprendieron que la desobediencia a Dios resulta en deshonor, desastre y muerte."},  // PR 372.4
{"cap": "pr41", "t": "fill", "ins": "Profetas y Reyes, cap. 41 — Completa la orden del rey:", "p": [{"x": "«Ordenando que se calentase el horno "}, {"b": "siete", "h": "¿qué palabra falta?"}, {"x": " veces más que de costumbre»"}]},  // PR 373.1
{"cap": "pr41", "t": "tf", "q": "Según P&R cap. 41, la llama del horno mató a los hombres que llevaron a Sadrach, Mesach y Abed-nego.", "a": true, "e": "Verdadero. El fuego estaba tan encendido que mató a los que los alzaron para echarlos al horno."},  // PR 373.2
{"cap": "pr41", "t": "tf", "q": "Según P&R cap. 41, estuvo mal que Nabucodonosor confesara públicamente al Dios de los cielos.", "a": false, "e": "Falso. Era correcto que hiciera una confesión pública y exaltara a Dios; lo que estuvo mal fue obligar a sus súbditos a hacer lo mismo (PR 375.3)."},  // PR 375.3
{"cap": "pr41", "t": "mc", "q": "Según P&R cap. 41, ¿cómo llegó la noticia de la liberación de los tres jóvenes a muchos países?", "o": ["Por los representantes de las naciones invitadas a la dedicación", "Por cartas que Daniel escribió a los judíos dispersos", "Por los soldados que regresaron de la llanura de Dura", "Por los sacerdotes que viajaban a los templos paganos"], "a": 0, "e": "La transmitieron los representantes de las naciones que Nabucodonosor había invitado a la dedicación."},  // PR 375.4

/* ── P&R 42 ── */
{"cap": "pr42", "t": "mc", "q": "Según P&R cap. 42, ¿qué vio Nabucodonosor en su segundo sueño?", "o": ["Un árbol gigantesco en medio de la tierra", "Una gran imagen hecha de varios metales", "Cuatro bestias que subían del gran mar", "Un río que crecía hasta cubrir la tierra"], "a": 0, "e": "En una visión de noche vio un árbol gigantesco que crecía en medio de la tierra."},  // PR 378.1
{"cap": "pr42", "t": "tf", "q": "Según P&R cap. 42, los sabios de Babilonia lograron interpretar el sueño del árbol antes de que llegara Daniel.", "a": false, "e": "Falso. Aunque el sueño era muy explícito, ninguno de los sabios pudo interpretarlo."},  // PR 379.1
{"cap": "pr42", "t": "tf", "q": "Según P&R cap. 42, Daniel sabía que debía declarar la verdad al rey, cualesquiera que fuesen las consecuencias para sí.", "a": true, "e": "Verdadero. Aunque el significado lo espantó, sabía que su deber era decir la verdad, le costara lo que le costara."},  // PR 379.4
{"cap": "pr42", "t": "mc", "q": "Según P&R cap. 42, ¿a quién representaba el árbol del sueño?", "o": ["Al mismo rey Nabucodonosor", "Al reino eterno del Dios del cielo", "Al pueblo de Israel en el cautiverio", "A los sabios y magos de Babilonia"], "a": 0, "e": "Daniel le dijo al rey que el árbol era él mismo, que había crecido y se había hecho fuerte."},  // PR 380.1
{"cap": "pr42", "t": "mc", "q": "Según P&R cap. 42, ¿qué significaba que dejaran en la tierra la cepa de las raíces del árbol?", "o": ["Que su reino quedaría firme cuando entendiera que el señorío es en los cielos", "Que sus hijos heredarían el reino mientras él estuviera lejos de Babilonia", "Que Babilonia nunca sería conquistada por los reinos que vendrían después", "Que Daniel gobernaría el reino durante los siete tiempos del castigo"], "a": 0, "e": "La cepa significaba que el reino le quedaría firme luego de que entendiera que el señorío es en los cielos."},  // PR 380.2
{"cap": "pr42", "t": "mc", "q": "Según P&R cap. 42, ¿qué pasó con el gobierno de Nabucodonosor cuando volvieron su orgullo y su ambición?", "o": ["Que había sido bastante justo y se volvió opresivo", "Que había sido cruel y se volvió misericordioso", "Que se debilitó y perdió a Tiro y a Egipto", "Que se lo entregó por un tiempo a Daniel"], "a": 0, "e": "Su gobierno, hasta entonces en buena medida justo y misericordioso, se volvió opresivo."},  // PR 380.4
{"cap": "pr42", "t": "mc", "q": "Según P&R cap. 42, ¿qué hizo el rey durante los meses en que Dios demoró el juicio?", "o": ["Alentó su orgullo y se burló de sus temores anteriores", "Ayudó a los pobres, como le había aconsejado Daniel", "Mandó a los sabios a estudiar otra vez el sueño", "Ordenó adorar al Dios de Daniel en todo el reino"], "a": 0, "e": "En vez de arrepentirse, alentó su orgullo, perdió confianza en la interpretación y se burló de sus temores."},  // PR 381.1
{"cap": "pr42", "t": "mc", "q": "Según P&R cap. 42, ¿durante cuánto tiempo fue humillado Nabucodonosor delante de todo el mundo?", "o": ["Siete años", "Siete meses", "Un año", "Tres años"], "a": 0, "e": "Durante siete años fue el asombro de sus súbditos y fue humillado delante de todo el mundo."},  // PR 382.1
{"cap": "pr42", "t": "fill", "ins": "Profetas y Reyes, cap. 42 — Completa el camino que lleva a la verdadera grandeza:", "p": [{"x": "«se sintiera tentado a desviarse de la senda de la "}, {"b": "humildad", "h": "¿qué palabra falta?"}, {"x": ", la única que lleva a la verdadera grandeza.»"}]},  // PR 377.3
{"cap": "pr42", "t": "fill", "ins": "Profetas y Reyes, cap. 42 — Completa la lección que aprendió Nabucodonosor:", "p": [{"x": "«la verdadera grandeza consiste en ser verdaderamente "}, {"b": "buenos", "h": "¿qué palabra falta?"}, {"x": ".»"}]},  // PR 382.3

/* ── P&R 43 ── */
{"cap": "pr43", "t": "mc", "q": "Según P&R cap. 43, ¿quién sitió la ciudad de Babilonia?", "o": ["Ciro, sobrino de Darío el Medo", "Darío, hijo de Ciro el Persa", "Un general enviado desde Egipto", "Los príncipes de Judá rebelados"], "a": 0, "e": "Babilonia fue sitiada por Ciro, sobrino de Darío el Medo y general de los ejércitos de medos y persas."},  // PR 384.3
{"cap": "pr43", "t": "mc", "q": "Según P&R cap. 43, ¿qué quería probar Belsasar al mandar traer los vasos del templo?", "o": ["Que nada era demasiado sagrado para sus manos", "Que respetaba al Dios de los cautivos judíos", "Que su riqueza superaba la de Nabucodonosor", "Que los judíos debían servirle en el palacio"], "a": 0, "e": "El texto dice que el rey quería probar que nada era demasiado sagrado para sus manos."},  // PR 385.2
{"cap": "pr43", "t": "fill", "ins": "Profetas y Reyes, cap. 43. Completa la frase sobre quién miraba el banquete:", "p": [{"x": "«pero un "}, {"b": "Vigía", "h": "¿qué palabra falta?"}, {"x": " divino, aunque no reconocido, miraba la escena de "}, {"b": "profanación", "h": "¿qué palabra falta?"}, {"x": "»"}]},  // PR 385.3
{"cap": "pr43", "t": "mc", "q": "Según P&R cap. 43, ¿quién recordó a Daniel y aconsejó al rey que lo llamara?", "o": ["La reina madre", "El jefe de los astrólogos", "Uno de los mil príncipes", "El general Ciro"], "a": 0, "e": "La reina madre recordó que Daniel había interpretado el sueño de Nabucodonosor más de medio siglo antes."},  // PR 387.1
{"cap": "pr43", "t": "mc", "q": "Según P&R cap. 43, ¿qué respondió Daniel cuando el rey le ofreció púrpura, collar de oro y el tercer lugar en el reino?", "o": ["«Tus dones sean para ti, y tus presentes dalos a otro»", "«Acepto tus dones, oh rey, si dejas libre a mi pueblo»", "«Dame un día para orar y mañana te daré la respuesta»", "«La leeré cuando devuelvas los vasos del templo»"], "a": 0, "e": "Daniel no se interesó en las recompensas; vino a dar un mensaje de Dios."},  // PR 387.3
{"cap": "pr43", "t": "mc", "q": "Según P&R cap. 43, ¿qué significa la palabra TEKEL?", "o": ["Pesado has sido en balanza, y fuiste hallado falto", "Contó Dios tu reino, y halo rematado", "Tu reino fué rompido, y es dado a Medos y Persas", "Tu reino pasará a tus hijos y a tus nietos"], "a": 0, "e": "MENE: el reino contado y terminado; TEKEL: pesado y hallado falto; PERES: el reino dado a medos y persas."},  // PR 389.1
{"cap": "pr43", "t": "mc", "q": "Según P&R cap. 43, ¿cómo lograron los medos y persas entrar en Babilonia?", "o": ["Desviaron el curso del río Eufrates", "Derribaron las puertas de bronce", "Unos traidores les abrieron las puertas", "Escalaron las murallas del palacio"], "a": 0, "e": "Mientras el rey bebía en los vasos sagrados, los medos y persas desviaron el Eufrates y entraron a la ciudad desprevenida."},  // PR 389.5
{"cap": "pr43", "t": "mc", "q": "Según P&R cap. 43, ¿qué enseñan las ruedas que vio Ezequiel, guiadas por la mano bajo las alas de los querubines?", "o": ["Que los acontecimientos humanos están bajo el control divino", "Que las naciones se mueven sin ningún orden ni propósito", "Que los reyes de la tierra dirigen su propio destino", "Que los querubines gobiernan cada reino en lugar de Dios"], "a": 0, "e": "Así como la mano guiaba las ruedas, el complicado juego de los acontecimientos humanos está bajo el control de Dios."},  // PR 393.2
{"cap": "pr43", "t": "tf", "q": "Según P&R cap. 43, Dios decide el destino de cada persona sin que ella pueda elegir.", "a": false, "e": "Falso. El capítulo dice que cada uno decide su destino por su propia elección, y que Dios lo rige todo para cumplir sus propósitos."},  // PR 393.3
{"cap": "pr43", "t": "fill", "ins": "Profetas y Reyes, cap. 43. Completa la promesa del final del capítulo:", "p": [{"x": "«Dios no "}, {"b": "desamparará", "h": "¿qué palabra falta?"}, {"x": " a su iglesia en la hora de su mayor "}, {"b": "peligro", "h": "¿qué palabra falta?"}, {"x": ".»"}]},  // PR 395.5

/* ── P&R 44 ── */
{"cap": "pr44", "t": "mc", "q": "Según P&R cap. 44, ¿hacia dónde tenía abiertas las ventanas Daniel cuando oraba?", "o": ["Hacia Jerusalén", "Hacia el palacio del rey", "Hacia el río Eufrates", "Hacia la plaza de Babilonia"], "a": 0, "e": "Oraba en su cámara con las ventanas abiertas hacia Jerusalén, según su costumbre, sin ocultarse."},  // PR 397.2
{"cap": "pr44", "t": "tf", "q": "Según P&R cap. 44, después del decreto Daniel dejó de obedecer al rey en todo.", "a": false, "e": "Falso. Daniel obedecía al rey en todo lo que el rey tenía derecho a mandar; solo no dejaría su lealtad al Rey de reyes."},  // PR 397.2
{"cap": "pr44", "t": "mc", "q": "Según P&R cap. 44, ¿qué le recordaron los príncipes al rey cuando quiso librar a Daniel?", "o": ["Que ningún decreto confirmado por el rey podía mudarse", "Que Daniel había conspirado en secreto contra el rey", "Que los dioses de Persia pedían castigar a Daniel", "Que el pueblo se rebelaría si Daniel quedaba libre"], "a": 0, "e": "Según la ley de Media y de Persia, el decreto era inalterable y debía cumplirse."},  // PR 398.4
{"cap": "pr44", "t": "mc", "q": "Según P&R cap. 44, ¿qué hizo el rey Darío la noche en que Daniel estuvo en el foso?", "o": ["Se acostó ayuno, sin música, y se le fue el sueño", "Celebró un banquete con sus príncipes", "Fue a dormir tranquilo en su palacio", "Pasó la noche orando junto al foso"], "a": 0, "e": "El rey se fue a su palacio, se acostó sin comer, no quiso música y no pudo dormir."},  // PR 398.5
{"cap": "pr44", "t": "mc", "q": "Según P&R cap. 44, ¿qué le dijo Daniel al rey que había hecho Dios en el foso?", "o": ["Envió su ángel, que cerró la boca de los leones", "Hizo que los leones se durmieran toda la noche", "Mandó a los leones fuera del foso antes de entrar", "Lo sacó del foso a medianoche por otra salida"], "a": 0, "e": "Daniel dijo: «El Dios mío envió su ángel, el cual cerró la boca de los leones»."},  // PR 399.3
{"cap": "pr44", "t": "fill", "ins": "Profetas y Reyes, cap. 44. Completa la frase sobre cómo salió Daniel del foso:", "p": [{"x": "«y ninguna "}, {"b": "lesión", "h": "¿qué palabra falta?"}, {"x": " se halló en él, porque "}, {"b": "creyó", "h": "¿qué palabra falta?"}, {"x": " en su Dios.»"}]},  // PR 399.4
{"cap": "pr44", "t": "mc", "q": "Según P&R cap. 44, ¿qué pasa con quien toca a los escogidos de Cristo?", "o": ["Le toca a Cristo mismo", "Recibe el perdón del rey", "Pierde su puesto en el reino", "Queda libre de toda culpa"], "a": 0, "e": "Cristo identifica sus intereses con los de su pueblo fiel y sufre en la persona de sus santos."},  // PR 400.3
{"cap": "pr44", "t": "mc", "q": "Según P&R cap. 44, ¿qué se le ordenó a Daniel acerca de sus escritos proféticos?", "o": ["Que cerrara las palabras y sellara el libro", "Que los leyera en público ante el rey Ciro", "Que los enviara a los cautivos en Jerusalén", "Que los quemara después de haberlos escrito"], "a": 0, "e": "Esos escritos debían quedar sellados «hasta el tiempo del fin»."},  // PR 401.2
{"cap": "pr44", "t": "tf", "q": "Según P&R cap. 44, las profecías de Daniel y del Apocalipsis no se pueden comprender.", "a": false, "e": "Falso. Eso es lo que Satanás ha inducido a muchos a creer; el capítulo dice que una bendición especial acompañará el estudio de esas profecías."},  // PR 402.1
{"cap": "pr44", "t": "fill", "ins": "Profetas y Reyes, cap. 44. Completa la frase sobre lo que permanece:", "p": [{"x": "«Sólo puede perdurar lo que se vincula con su "}, {"b": "propósito", "h": "¿qué palabra falta?"}, {"x": " y expresa su "}, {"b": "carácter", "h": "¿qué palabra falta?"}, {"x": ".»"}]},  // PR 402.2

];

if (typeof module !== "undefined") module.exports = { BANCO_PR };
