/* Banco de preguntas. cap = capítulo al que pertenece.
   El examen se arma filtrando por los capítulos de la categoría. */

const BANCO = [

/* ─────────── DANIEL 1 ─────────── */
{cap:'d1',t:'mc',q:'¿En qué año del reinado de Joacim vino Nabucodonosor a Jerusalén y la sitió? (Daniel 1:1)',
 o:['En el primer año','En el segundo año','En el tercer año','En el cuarto año'],a:2},
{cap:'d1',t:'mc',q:'¿A dónde llevó Nabucodonosor los utensilios de la casa de Dios? (Daniel 1:2)',
 o:['Al palacio real de Babilonia','A la casa del tesoro de su dios, en tierra de Sinar','Al templo de Marduc','A la fortaleza de Susa'],a:1},
{cap:'d1',t:'mc',q:'¿Cómo se llamaba el jefe de los eunucos al que el rey dio la orden? (Daniel 1:3)',
 o:['Melsar','Arioc','Aspenaz','Nabuzaradán'],a:2},
{cap:'d1',t:'mc',q:'¿Cómo se llamaba el sirviente puesto directamente sobre Daniel y sus compañeros? (Daniel 1:11)',
 o:['Aspenaz','Arioc','Nabuzaradán','Melsar'],a:3},
{cap:'d1',t:'mc',q:'¿Cuántos años debían ser educados los jóvenes antes de presentarse ante el rey? (Daniel 1:5)',
 o:['Dos años','Tres años','Cinco años','Siete años'],a:1},
{cap:'d1',t:'mc',q:'¿Cuál era el nombre babilónico de Ananías? (Daniel 1:7)',
 o:['Sadrac','Mesac','Abed-nego','Beltsasar'],a:0},
{cap:'d1',t:'mc',q:'¿Cuál era el nombre babilónico de Azarías? (Daniel 1:7)',
 o:['Sadrac','Mesac','Abed-nego','Beltsasar'],a:2},
{cap:'d1',t:'mc',q:'¿Qué pidió Daniel que les dieran durante la prueba? (Daniel 1:12)',
 o:['Pan y agua','Legumbres para comer y agua para beber','Frutas y miel','Grano y aceite'],a:1},
{cap:'d1',t:'mc',q:'Según Daniel 1:15, ¿cómo apareció el rostro de los cuatro al cabo de los diez días?',
 o:['Más pálido pero más sabio','Igual que el de los demás','Mejor y más robusto que el de los otros muchachos','Más delgado pero más fuerte'],a:2},
{cap:'d1',t:'mc',q:'¿Cuántas veces mejores los halló el rey respecto a los magos y astrólogos? (Daniel 1:20)',
 o:['Dos veces','Cinco veces','Diez veces','Cien veces'],a:2},
{cap:'d1',t:'mc',q:'¿Qué don especial recibió Daniel que no se menciona para los otros tres? (Daniel 1:17)',
 o:['Poder para sanar','Entendimiento en toda visión y sueños','Dominio de todas las lenguas','Fuerza física superior'],a:1},
{cap:'d1',t:'tf',q:'Daniel continuó en el servicio del rey hasta el año primero del rey Ciro. (Daniel 1:21)',
 a:true,e:'Verdadero. Daniel 1:21 lo dice textualmente.'},
{cap:'d1',t:'tf',q:'Fue Aspenaz quien aceptó directamente la prueba de los diez días propuesta por Daniel.',
 a:false,e:'Falso. Daniel habló con MELSAR, el sirviente que Aspenaz había puesto sobre ellos (Daniel 1:11).'},
{cap:'d1',t:'fill',ins:'Daniel 1:20 (RV1995) — Completa:',
 p:[{x:'«...los halló '},{b:'diez',h:'¿cuántas veces?'},{x:' veces mejores que todos los '},{b:'magos',h:'¿quiénes?'},{x:' y astrólogos que había en todo su reino.»'}]},
{cap:'d1',t:'fill',ins:'Daniel 1:15 (RV1995) — Completa:',
 p:[{x:'«Y al cabo de los diez días pareció el rostro de ellos '},{b:'mejor',h:'¿cómo?'},{x:' y más '},{b:'robusto',h:'¿cómo?'},{x:' que el de los otros muchachos.»'}]},

/* ─────────── DANIEL 2 ─────────── */
{cap:'d2',t:'mc',q:'¿En qué año del reinado de Nabucodonosor tuvo él sus sueños? (Daniel 2:1)',
 o:['En el primer año','En el segundo año','En el tercer año','En el décimo año'],a:1},
{cap:'d2',t:'mc',q:'¿Quién era Arioc? (Daniel 2:14)',
 o:['El jefe de los eunucos','El capitán de la guardia del rey','El principal de los magos','El mayordomo del palacio'],a:1},
{cap:'d2',t:'mc',q:'¿Cómo le fue revelado a Daniel el misterio del sueño? (Daniel 2:19)',
 o:['Por un ángel visible en el día','En visión de noche','Por voz audible desde el cielo','Leyendo los libros de los profetas'],a:1},
{cap:'d2',t:'mc',q:'¿De qué material eran el vientre y los muslos de la imagen? (Daniel 2:32)',
 o:['De plata','De hierro','De bronce','De barro cocido'],a:2},
{cap:'d2',t:'mc',q:'¿En qué parte hirió la piedra a la imagen? (Daniel 2:34)',
 o:['En la cabeza de oro','En el pecho de plata','En sus pies de hierro y de barro cocido','En las piernas de hierro'],a:2},
{cap:'d2',t:'mc',q:'Según Daniel 2:35, ¿con qué se comparó lo que quedó de la imagen desmenuzada?',
 o:['Con ceniza del altar','Con arena del desierto','Con tamo de las eras del verano','Con polvo del camino'],a:2},
{cap:'d2',t:'mc',q:'¿Qué cargo recibió Daniel tras interpretar el sueño? (Daniel 2:48)',
 o:['Príncipe del palacio real','Gobernador de la provincia de Babilonia y principal de los gobernadores sobre los sabios','Consejero personal del rey','Jefe del ejército'],a:1},
{cap:'d2',t:'mc',q:'¿Qué representa la piedra cortada sin manos? (Daniel 2:44-45)',
 o:['La caída de Babilonia','El reino eterno de Dios que no será jamás destruido','El imperio romano','La restauración de Jerusalén'],a:1},
{cap:'d2',t:'tf',q:'La cabeza de la gran imagen era de plata. (Daniel 2:32)',
 a:false,e:'Falso. La cabeza era de ORO FINO; el pecho y los brazos eran de plata.'},
{cap:'d2',t:'tf',q:'Daniel pidió tiempo al rey y oró con sus compañeros antes de recibir la revelación. (Daniel 2:16-18)',
 a:true,e:'Verdadero. Pidió tiempo, fue a su casa e hizo saber el asunto a sus compañeros para pedir misericordia.'},
{cap:'d2',t:'fill',ins:'Daniel 2:20 (RV1995) — Completa:',
 p:[{x:'«Sea bendito el nombre de Dios de siglos en siglos, porque suyos son el '},{b:'poder',h:'¿qué?'},{x:' y la '},{b:'sabiduría',h:'¿qué?'},{x:'.»'}]},

/* ─────────── DANIEL 3 ─────────── */
{cap:'d3',t:'mc',q:'¿Cuántos codos de altura tenía la estatua de oro? (Daniel 3:1)',
 o:['Seis codos','Treinta codos','Sesenta codos','Cien codos'],a:2},
{cap:'d3',t:'mc',q:'¿Cuántos codos de anchura tenía la estatua de oro? (Daniel 3:1)',
 o:['Tres codos','Seis codos','Doce codos','Veinte codos'],a:1},
{cap:'d3',t:'mc',q:'¿En qué lugar fue levantada la estatua de oro? (Daniel 3:1)',
 o:['Frente al palacio real','En el campo de Dura, en la provincia de Babilonia','En la llanura de Sinar','En el templo principal'],a:1},
{cap:'d3',t:'mc',q:'¿Cuál es el PRIMER instrumento de la lista de Daniel 3:5?',
 o:['La flauta','El arpa','La bocina','El tamboril'],a:2},
{cap:'d3',t:'mc',q:'¿Cuál de estos instrumentos NO aparece en Daniel 3:5?',
 o:['La zampoña','El salterio','La trompeta','El tamboril'],a:2},
{cap:'d3',t:'mc',q:'¿Cuántas veces más de lo acostumbrado mandó calentar el horno? (Daniel 3:19)',
 o:['Dos veces','Cuatro veces','Siete veces','Diez veces'],a:2},
{cap:'d3',t:'mc',q:'¿Con qué ropa fueron echados al horno los tres jóvenes? (Daniel 3:21)',
 o:['Solo con túnicas de lino','Con sus mantos, sus calzas, sus turbantes y sus vestidos','Sin ropa alguna','Con armaduras de guerra'],a:1},
{cap:'d3',t:'mc',q:'¿Qué les ocurrió a los varones que echaron a los jóvenes al horno? (Daniel 3:22)',
 o:['Cayeron desmayados','La llama del fuego los mató','Huyeron aterrados','Fueron perdonados'],a:1},
{cap:'d3',t:'mc',q:'¿Cómo describió Nabucodonosor al cuarto personaje del horno? (Daniel 3:25)',
 o:['Como un ángel de gran poder','Como un hombre de fuego','Semejante al Hijo de Dios','Como una estrella brillante'],a:2},
{cap:'d3',t:'mc',q:'¿Qué decretó Nabucodonosor sobre quien blasfemara contra el Dios de los tres jóvenes? (Daniel 3:29)',
 o:['Prisión perpetua','Destierro del reino','Que sea descuartizado y su casa puesta por muladar','Pérdida de todos sus bienes'],a:2},
{cap:'d3',t:'tf',q:'Al salir del horno, ni olor de fuego había en los tres jóvenes. (Daniel 3:27)',
 a:true,e:'Verdadero. Daniel 3:27 lo dice textualmente, junto con que el fuego no se enseñoreó de sus cuerpos.'},
{cap:'d3',t:'tf',q:'Los tres jóvenes dijeron que si Dios no los libraba, entonces sí adorarían la estatua.',
 a:false,e:'Falso. Dijeron: «Y si no, no serviremos a tus dioses ni adoraremos la estatua» (Daniel 3:18).'},
{cap:'d3',t:'fill',ins:'Daniel 3:25 (RV1995) — Completa:',
 p:[{x:'«He aquí yo veo '},{b:'cuatro',h:'¿cuántos?'},{x:' varones sueltos, que se pasean en medio del fuego... y el parecer del cuarto es semejante al '},{b:'Hijo de Dios',h:'¿a quién?'},{x:'.»'}]},
{cap:'d3',t:'fill',ins:'Daniel 3:27 (RV1995) — Completa:',
 p:[{x:'«...ni cabello de sus cabezas fue '},{b:'quemado',h:'¿qué le pasó?'},{x:', ni sus vestidos se alteraron, ni '},{b:'olor',h:'¿qué no había?'},{x:' de fuego había en ellos.»'}]},

/* ─────────── DANIEL 4 ─────────── */
{cap:'d4',t:'mc',q:'¿Hasta dónde llegaba la copa del árbol del sueño? (Daniel 4:11)',
 o:['Hasta las nubes','Hasta el cielo','Hasta los confines del mar','Hasta la cima del monte'],a:1},
{cap:'d4',t:'mc',q:'Según Daniel 4:15, ¿con qué debía quedar atada la cepa de las raíces?',
 o:['Con cuerdas de lino','Con cadenas de oro','Con atadura de hierro y de bronce','Con ataduras de plata'],a:2},
{cap:'d4',t:'mc',q:'¿Cuántos tiempos debían pasar sobre Nabucodonosor? (Daniel 4:25)',
 o:['Tres tiempos','Cinco tiempos','Siete tiempos','Doce tiempos'],a:2},
{cap:'d4',t:'mc',q:'¿Cuánto tiempo pasó entre la advertencia de Daniel y el cumplimiento? (Daniel 4:29)',
 o:['Siete días','Un mes','Doce meses','Tres años'],a:2},
{cap:'d4',t:'mc',q:'¿Cómo le creció el cabello a Nabucodonosor? (Daniel 4:33)',
 o:['Como lana blanca','Como plumas de águila','Como ramas secas','Como crin de caballo'],a:1},
{cap:'d4',t:'mc',q:'¿Qué acción marcó el momento en que recuperó la razón? (Daniel 4:34)',
 o:['Comió hierba del campo','Alzó sus ojos al cielo','Daniel oró por él','Sus consejeros lo llamaron'],a:1},
{cap:'d4',t:'mc',q:'¿Qué consejo le dio Daniel al rey antes del juicio? (Daniel 4:27)',
 o:['Que destruyera los ídolos','Que redimiera sus pecados con justicia y sus iniquidades haciendo misericordias para con los oprimidos','Que ayunara cuarenta días','Que liberara a los cautivos judíos'],a:1},
{cap:'d4',t:'tf',q:'Las uñas de Nabucodonosor crecieron como las de las aves. (Daniel 4:33)',
 a:true,e:'Verdadero. Daniel 4:33 lo dice junto con que su cabello creció como plumas de águila.'},
{cap:'d4',t:'fill',ins:'Daniel 4:37 (RV1995) — Completa:',
 p:[{x:'«Ahora yo Nabucodonosor alabo, engrandezco y glorifico al Rey del cielo, porque todas sus obras son '},{b:'verdaderas',h:'¿cómo son?'},{x:', y sus caminos '},{b:'justos',h:'¿cómo son?'},{x:'.»'}]},

/* ─────────── DANIEL 5 ─────────── */
{cap:'d5',t:'mc',q:'¿A cuántos príncipes hizo Belsasar su gran banquete? (Daniel 5:1)',
 o:['Quinientos','Ochocientos','Mil','Dos mil'],a:2},
{cap:'d5',t:'mc',q:'¿De dónde provenían los vasos que Belsasar mandó traer? (Daniel 5:2)',
 o:['Del templo de Marduc','Del tesoro personal del rey','Del templo que estaba en Jerusalén','De Persia'],a:2},
{cap:'d5',t:'mc',q:'¿Frente a qué objeto apareció la escritura en la pared? (Daniel 5:5)',
 o:['Frente al trono','Delante del candelero','Sobre el altar','Junto a la puerta principal'],a:1},
{cap:'d5',t:'mc',q:'¿Cuál es el texto exacto de la escritura? (Daniel 5:25)',
 o:['MENE, TEKEL, UPARSIN','MENE, MENE, TEKEL, PERES','MENE, MENE, TEKEL, UPARSIN','TEKEL, MENE, PERES, UPARSIN'],a:2},
{cap:'d5',t:'mc',q:'¿Qué significa TEKEL? (Daniel 5:27)',
 o:['Contó Dios tu reino y le ha puesto fin','Pesado has sido en balanza y fuiste hallado falto','Tu reino ha sido roto y dado a otros','Tus días están contados'],a:1},
{cap:'d5',t:'mc',q:'¿Qué significa PERES? (Daniel 5:28)',
 o:['Contó Dios tu reino','Pesado y hallado falto','Tu reino ha sido roto y dado a los medos y a los persas','Serás humillado hasta el polvo'],a:2},
{cap:'d5',t:'mc',q:'¿Qué tres cosas ofreció Belsasar a quien leyera la escritura? (Daniel 5:7)',
 o:['Oro, plata y tierras','Ser vestido de púrpura, collar de oro y ser el tercer señor del reino','Un palacio, siervos y honores militares','La mitad de su reino'],a:1},
{cap:'d5',t:'mc',q:'¿Cuántos años tenía Darío de Media al recibir el reino? (Daniel 5:31)',
 o:['Cincuenta años','Sesenta y dos años','Setenta años','Cuarenta y cinco años'],a:1},
{cap:'d5',t:'tf',q:'Belsasar fue muerto esa misma noche en que apareció la escritura. (Daniel 5:30)',
 a:true,e:'Verdadero. «La misma noche fue muerto Belsasar, rey de los caldeos» (Daniel 5:30).'},
{cap:'d5',t:'tf',q:'Fueron los magos de Babilonia quienes recordaron a Daniel ante el rey Belsasar.',
 a:false,e:'Falso. Fue LA REINA quien entró a la sala del banquete y le habló al rey de Daniel (Daniel 5:10-12).'},
{cap:'d5',t:'fill',ins:'Daniel 5:27 (RV1995) — Completa:',
 p:[{x:'«TEKEL: '},{b:'Pesado',h:'¿qué te hicieron?'},{x:' has sido en balanza, y fuiste hallado '},{b:'falto',h:'¿cómo?'},{x:'.»'}]},

/* ─────────── DANIEL 6 ─────────── */
{cap:'d6',t:'mc',q:'¿Cuántos sátrapas constituyó Darío sobre el reino? (Daniel 6:1)',
 o:['Ochenta','Cien','Ciento veinte','Ciento cincuenta'],a:2},
{cap:'d6',t:'mc',q:'¿Cuántos gobernadores puso sobre los sátrapas? (Daniel 6:2)',
 o:['Dos','Tres','Cuatro','Siete'],a:1},
{cap:'d6',t:'mc',q:'¿Por qué sobresalía Daniel sobre los demás? (Daniel 6:3)',
 o:['Porque era el más antiguo','Porque había en él un espíritu superior','Porque era pariente del rey','Porque hablaba muchos idiomas'],a:1},
{cap:'d6',t:'mc',q:'¿Por qué no pudieron hallar ocasión para acusar a Daniel? (Daniel 6:4)',
 o:['Porque el rey lo protegía','Porque él era fiel y ningún vicio ni falta fue hallado en él','Porque era demasiado poderoso','Porque sus enemigos eran torpes'],a:1},
{cap:'d6',t:'mc',q:'¿Cuántos días duraba el edicto que prohibía orar a otro que no fuera el rey? (Daniel 6:7)',
 o:['Diez días','Veinte días','Treinta días','Cuarenta días'],a:2},
{cap:'d6',t:'mc',q:'¿Hacia dónde daban las ventanas de la cámara donde oraba Daniel? (Daniel 6:10)',
 o:['Hacia el palacio real','Hacia el oriente','Hacia Jerusalén','Hacia el río'],a:2},
{cap:'d6',t:'mc',q:'¿Con qué fue sellada la piedra sobre la puerta del foso? (Daniel 6:17)',
 o:['Solo con el anillo del rey','Con el anillo del rey y con el de sus príncipes','Con cadenas de hierro','Con cera y el sello del templo'],a:1},
{cap:'d6',t:'mc',q:'¿Qué hizo el rey Darío aquella noche? (Daniel 6:18)',
 o:['Celebró un banquete','Pasó la noche en ayuno, sin instrumentos de música, y se le fue el sueño','Consultó a sus adivinos','Durmió profundamente'],a:1},
{cap:'d6',t:'mc',q:'¿En qué momento fue Darío al foso? (Daniel 6:19)',
 o:['Al mediodía','Al anochecer','Muy de mañana, al rayar el alba','A la hora tercera'],a:2},
{cap:'d6',t:'mc',q:'¿Qué respondió Daniel sobre por qué estaba ileso? (Daniel 6:22)',
 o:['Que los leones estaban dormidos','Que Dios envió su ángel, el cual cerró la boca de los leones','Que se hizo invisible','Que los leones ya estaban saciados'],a:1},
{cap:'d6',t:'tf',q:'El rey Darío trabajó hasta la puesta del sol tratando de librar a Daniel. (Daniel 6:14)',
 a:true,e:'Verdadero. «...y hasta la puesta del sol trabajó para librarle» (Daniel 6:14).'},
{cap:'d6',t:'tf',q:'Daniel dejó de orar durante los treinta días del edicto para no arriesgarse.',
 a:false,e:'Falso. Siguió orando tres veces al día, «como lo solía hacer antes» (Daniel 6:10).'},
{cap:'d6',t:'fill',ins:'Daniel 6:10 (RV1995) — Completa:',
 p:[{x:'«...abiertas las ventanas de su cámara que daban hacia '},{b:'Jerusalén',h:'¿hacia dónde?'},{x:', se arrodillaba '},{b:'tres',h:'¿cuántas veces?'},{x:' veces al día, y oraba y daba gracias delante de su Dios, como lo solía hacer antes.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:22 (RV1995) — Completa:',
 p:[{x:'«Mi Dios envió su '},{b:'ángel',h:'¿a quién?'},{x:', el cual cerró la boca de los '},{b:'leones',h:'¿de qué?'},{x:', para que no me hiciesen daño.»'}]},

/* ─────────── P&R 39 ─────────── */
{cap:'pr39',t:'mc',q:'¿Cuál es el título del capítulo 39 de Profetas y Reyes?',
 o:['Cautivos en Babilonia','En la corte de Babilonia','El fiel en tierra extraña','En la corte del rey'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿por qué razón principal rechazó Daniel la comida del rey?',
 o:['No tenía hambre','Había sido ofrecida a los ídolos y violaba las leyes de Dios','Era demasiado costosa','No le gustaba su sabor'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué relación hay entre los hábitos físicos y la mente?',
 o:['Ninguna relación','Los hábitos temperantes favorecen la claridad mental y espiritual','Solo la oración afecta el intelecto','El cuerpo y la mente son independientes'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿cuál era el mayor peligro para los jóvenes hebreos?',
 o:['La persecución abierta','La tentación de ceder poco a poco en sus principios','El clima de Babilonia','La falta de alimentos'],a:1},
{cap:'pr39',t:'tf',q:'Según P&R cap. 39, Daniel se negó a la comida del rey de forma rebelde y desafiante.',
 a:false,e:'Falso. Elena de White destaca que fue firme y cortés a la vez, y propuso una prueba razonable.'},

/* ─────────── P&R 40 ─────────── */
{cap:'pr40',t:'mc',q:'¿Cuál es el título del capítulo 40 de Profetas y Reyes?',
 o:['La gran imagen','El sueño de Nabucodonosor','El misterio revelado','La piedra y el monte'],a:1},
{cap:'pr40',t:'mc',q:'Según P&R cap. 40, ¿a qué recurrieron primero Daniel y sus compañeros ante la sentencia?',
 o:['A la estrategia política','A la oración','A los libros de los sabios','A pedir clemencia al rey'],a:1},
{cap:'pr40',t:'mc',q:'Según P&R cap. 40, ¿qué representa la piedra cortada sin manos?',
 o:['La caída de Babilonia','Cristo y el establecimiento de su reino eterno','La restauración de Israel','El fin del imperio griego'],a:1},
{cap:'pr40',t:'tf',q:'Según P&R cap. 40, la sucesión de los imperios muestra que la historia es gobernada por Dios.',
 a:true,e:'Verdadero. La imagen revela que Dios gobierna el reino de los hombres y dirige el curso de la historia.'},

/* ─────────── P&R 41 ─────────── */
{cap:'pr41',t:'mc',q:'¿Cuál es el título del capítulo 41 de Profetas y Reyes?',
 o:['El horno de fuego','La imagen de oro','Los tres hebreos fieles','La prueba de la fe'],a:0},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿quién era el cuarto personaje del horno?',
 o:['Un ángel creado','El Espíritu Santo','El Hijo de Dios mismo','El profeta Elías'],a:2},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿qué muestra la frase «y si no» de los tres jóvenes?',
 o:['Que dudaban del poder de Dios','Que su obediencia no dependía de recibir el milagro','Que negociaban con el rey','Que esperaban morir'],a:1},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿para qué es un modelo la experiencia del horno?',
 o:['Solo para casos de idolatría literal','Para la crisis final cuando se exija adoración contraria a Dios','Para los conflictos políticos','No tiene aplicación moderna'],a:1},
{cap:'pr41',t:'tf',q:'Según P&R cap. 41, Dios libró a los tres jóvenes evitando que entraran al horno.',
 a:false,e:'Falso. No los libró DE la prueba: el Hijo de Dios estuvo con ellos DENTRO del horno.'},

/* ─────────── P&R 42 ─────────── */
{cap:'pr42',t:'mc',q:'¿Cuál es el título del capítulo 42 de Profetas y Reyes?',
 o:['Nabucodonosor humillado','El orgullo del rey','La verdadera grandeza','El rey entre las bestias'],a:2},
{cap:'pr42',t:'mc',q:'Según P&R cap. 42, ¿cuál fue el pecado principal de Nabucodonosor?',
 o:['La idolatría','El orgullo, al atribuirse la gloria que pertenecía a Dios','La crueldad con los cautivos','El saqueo del templo'],a:1},
{cap:'pr42',t:'mc',q:'Según P&R cap. 42, ¿cuánto tiempo de gracia recibió el rey antes del juicio?',
 o:['Siete días','Un mes','Un año completo','Tres años'],a:2},
{cap:'pr42',t:'tf',q:'Según P&R cap. 42, Nabucodonosor murió sin reconocer nunca la soberanía de Dios.',
 a:false,e:'Falso. Fue restaurado y terminó siendo adorador del Dios verdadero; su testimonio final es uno de los más poderosos de la Biblia.'},

/* ─────────── P&R 43 ─────────── */
{cap:'pr43',t:'mc',q:'¿Cuál es el título del capítulo 43 de Profetas y Reyes?',
 o:['La fiesta de Belsasar','La escritura en la pared','El vigía invisible','El último rey'],a:2},
{cap:'pr43',t:'mc',q:'Según P&R cap. 43, ¿por qué Belsasar no tenía excusa?',
 o:['Porque era un rey justo','Porque conocía la experiencia de Nabucodonosor y aun así se rebeló','Porque los profetas le hablaron en persona','Porque había leído las Escrituras'],a:1},
{cap:'pr43',t:'mc',q:'Según P&R cap. 43, ¿qué representó usar los vasos sagrados en el banquete?',
 o:['Un descuido de protocolo','Una costumbre normal de la época','Un desafío deliberado a Dios y la cima de su impiedad','Un gesto de generosidad'],a:2},
{cap:'pr43',t:'tf',q:'Según P&R cap. 43, mayor conocimiento implica mayor responsabilidad delante de Dios.',
 a:true,e:'Verdadero. Belsasar tenía más luz que Nabucodonosor, y por eso su culpa fue mayor.'},

/* ─────────── P&R 44 ─────────── */
{cap:'pr44',t:'mc',q:'¿Cuál es el título del capítulo 44 de Profetas y Reyes?',
 o:['Daniel el profeta fiel','El profeta y el rey','En el foso de los leones','Fidelidad hasta el fin'],a:2},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿qué caracterizaba la oración de Daniel?',
 o:['Que oraba solo en las crisis','Que era la fuente diaria de su fortaleza','Que oraba para ser visto','Que era una formalidad religiosa'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿por qué sus enemigos no hallaron falta en Daniel?',
 o:['Porque el rey lo protegía','Porque su vida pública y privada eran igual de intachables','Porque era muy poderoso','Porque escondía bien sus faltas'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿qué enseña el ejemplo de Daniel a los jóvenes?',
 o:['Que deben evitar los cargos públicos','Que pueden ser testigos fieles de Dios en cualquier posición','Que la fidelidad siempre trae milagros visibles','Que deben apartarse de la sociedad'],a:1},
{cap:'pr44',t:'tf',q:'Según P&R cap. 44, Daniel era un hombre joven cuando fue echado al foso de los leones.',
 a:false,e:'Falso. Tenía más de ochenta años. Lo que decidió de joven (Daniel 1) fue lo que lo sostuvo de anciano.'},

];

/* Preguntas adicionales — segunda tanda, para estudio profundo. */
const BANCO_EXTRA = [

/* DANIEL 1 */
{cap:'d1',t:'mc',q:'Según Daniel 1:4, ¿qué debían aprender los jóvenes escogidos?',
 o:['Las artes de la guerra','Las letras y la lengua de los caldeos','La astrología babilónica','La administración del reino'],a:1},
{cap:'d1',t:'mc',q:'¿Qué hizo Dios por Daniel ante el jefe de los eunucos? (Daniel 1:9)',
 o:['Le envió un sueño','Puso a Daniel en gracia y en buena voluntad ante él','Le habló por medio de un ángel','Lo hizo enfermar'],a:1},
{cap:'d1',t:'mc',q:'Según Daniel 1:8, ¿dónde tomó Daniel su decisión de no contaminarse?',
 o:['En público, delante del rey','Propuso en su corazón','Por consejo de sus compañeros','Después de consultar a un sacerdote'],a:1},
{cap:'d1',t:'mc',q:'¿Qué hizo Melsar al comprobar el resultado de la prueba? (Daniel 1:16)',
 o:['Informó al rey','Se llevaba la porción de comida y el vino, y les daba legumbres','Los castigó','Extendió la prueba a todos'],a:1},
{cap:'d1',t:'tf',q:'Los jóvenes escogidos debían ser de aquellos en quienes no hubiera tacha alguna. (Daniel 1:4)',
 a:true,e:'Verdadero. Ésa es la primera condición que menciona Daniel 1:4.'},

/* DANIEL 2 */
{cap:'d2',t:'mc',q:'¿Qué amenazó el rey a los caldeos si no revelaban el sueño? (Daniel 2:5)',
 o:['Prisión perpetua','Destierro','Ser hechos pedazos y sus casas convertidas en muladares','Perder sus cargos'],a:2},
{cap:'d2',t:'mc',q:'¿Qué declaró Daniel ante el rey sobre el origen de la revelación? (Daniel 2:28)',
 o:['Que él era el más sabio de todos','Que hay un Dios en los cielos que revela los misterios','Que lo dedujo de los astros','Que se lo dijo un ángel en secreto'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:43, ¿por qué el hierro y el barro no se unen?',
 o:['Porque el barro es débil','Porque no se unirán el uno con el otro, como el hierro no se mezcla con el barro','Porque están separados por el tiempo','Porque uno destruye al otro'],a:1},
{cap:'d2',t:'tf',q:'Daniel pidió a sus compañeros que oraran pidiendo misericordias del Dios del cielo sobre el misterio. (Daniel 2:18)',
 a:true,e:'Verdadero. Daniel 2:18 lo dice textualmente.'},

/* DANIEL 3 */
{cap:'d3',t:'mc',q:'¿Cuántas veces se repite la lista de instrumentos en Daniel 3?',
 o:['Una vez','Dos veces','Tres veces','Cuatro veces (vv. 5, 7, 10 y 15)'],a:3},
{cap:'d3',t:'mc',q:'Según Daniel 3:19, ¿qué le pasó al rostro de Nabucodonosor?',
 o:['Palideció de miedo','Se demudó contra Sadrac, Mesac y Abed-nego','Sonrió con desprecio','Se llenó de lágrimas'],a:1},
{cap:'d3',t:'mc',q:'¿Quiénes se juntaron para ver que el fuego no los había dañado? (Daniel 3:27)',
 o:['Solo el rey','El pueblo de Babilonia','Los sátrapas, gobernadores, capitanes y consejeros del rey','Los sacerdotes del templo'],a:2},
{cap:'d3',t:'mc',q:'Según Daniel 3:29, ¿qué reconoció Nabucodonosor sobre el Dios de los hebreos?',
 o:['Que era uno más entre los dioses','Que no hay dios que pueda librar como él','Que era el dios de una nación pequeña','Que su poder era limitado'],a:1},
{cap:'d3',t:'tf',q:'Después del milagro, Nabucodonosor engrandeció a los tres jóvenes en la provincia de Babilonia. (Daniel 3:30)',
 a:true,e:'Verdadero. Daniel 3:30 cierra el capítulo con esa promoción.'},

/* DANIEL 4 */
{cap:'d4',t:'mc',q:'Según Daniel 4:12, ¿qué había debajo y en las ramas del árbol?',
 o:['Solo pastores','Las bestias del campo debajo y las aves del cielo en sus ramas','Ejércitos acampados','Ciudades enteras'],a:1},
{cap:'d4',t:'mc',q:'¿Cuál era el propósito declarado del juicio sobre el rey? (Daniel 4:17)',
 o:['Castigar su crueldad','Para que conozcan que el Altísimo gobierna el reino de los hombres','Vengar a los cautivos','Destruir Babilonia'],a:1},
{cap:'d4',t:'mc',q:'¿Qué dijo Nabucodonosor justo antes de que cayera el juicio? (Daniel 4:30)',
 o:['«Que venga el juicio de los dioses»','«¿No es ésta la gran Babilonia que yo edifiqué?»','«Nadie puede tocar mi reino»','«Los dioses me han bendecido»'],a:1},
{cap:'d4',t:'tf',q:'Después de su restauración, a Nabucodonosor le fue añadida mayor grandeza. (Daniel 4:36)',
 a:true,e:'Verdadero. Fue restituido en su reino y «mayor grandeza me fue añadida».'},

/* DANIEL 5 */
{cap:'d5',t:'mc',q:'¿Quiénes bebieron en los vasos del templo? (Daniel 5:3)',
 o:['Solo el rey','El rey, sus príncipes, sus mujeres y sus concubinas','Los sacerdotes de Babilonia','Los embajadores extranjeros'],a:1},
{cap:'d5',t:'mc',q:'¿A qué dioses alabaron durante el banquete? (Daniel 5:4)',
 o:['Solo a Marduc','A los dioses de oro, plata, bronce, hierro, madera y piedra','A los dioses del cielo','A los antepasados del rey'],a:1},
{cap:'d5',t:'mc',q:'Según Daniel 5:6, ¿qué le ocurrió al rey al ver la escritura?',
 o:['Se desmayó','Se demudó su rostro, se debilitaron sus lomos y sus rodillas daban la una contra la otra','Se enfureció','Huyó de la sala'],a:1},
{cap:'d5',t:'tf',q:'Belsasar cumplió lo prometido y vistió a Daniel de púrpura antes de morir. (Daniel 5:29)',
 a:true,e:'Verdadero. Daniel 5:29 dice que lo vistieron de púrpura y fue proclamado tercer señor del reino.'},

/* DANIEL 6 */
{cap:'d6',t:'mc',q:'¿Qué buscaban los gobernadores para acusar a Daniel? (Daniel 6:4)',
 o:['Testigos falsos','Ocasión de acusarlo en lo relacionado con el reino','Documentos secretos','Testimonios de sus enemigos'],a:1},
{cap:'d6',t:'mc',q:'¿Qué concluyeron sus enemigos que era la única vía para acusarlo? (Daniel 6:5)',
 o:['Sobornar a un testigo','Hallar algo en relación con la ley de su Dios','Acusarlo de robo','Convencer al rey de destituirlo'],a:1},
{cap:'d6',t:'mc',q:'¿Hasta cuándo trabajó el rey Darío para librar a Daniel? (Daniel 6:14)',
 o:['Hasta el mediodía','Hasta la puesta del sol','Toda la noche','Solo unos minutos'],a:1},
{cap:'d6',t:'mc',q:'¿Por qué no se halló lesión alguna en Daniel? (Daniel 6:23)',
 o:['Porque los leones estaban saciados','Porque había confiado en su Dios','Porque el foso era poco profundo','Porque lo sacaron rápido'],a:1},
{cap:'d6',t:'mc',q:'Según el decreto de Darío, ¿cómo se describe a Dios? (Daniel 6:26)',
 o:['El más grande entre los dioses','El Dios viviente que permanece por todos los siglos','El dios de los hebreos','Un dios poderoso entre otros'],a:1},
{cap:'d6',t:'tf',q:'Los acusadores de Daniel fueron echados al foso junto con sus hijos y sus mujeres. (Daniel 6:24)',
 a:true,e:'Verdadero. Daniel 6:24 lo dice, y añade que los leones se apoderaron de ellos.'},

/* TRANSVERSALES — comparación entre capítulos */
{cap:'d5',t:'mc',q:'¿Cuál rey terminó alabando, engrandeciendo y glorificando al Rey del cielo?',
 o:['Belsasar','Nabucodonosor','Darío','Joacim'],a:1},
{cap:'d6',t:'mc',q:'¿Cuál rey emitió un decreto para que todos temieran al Dios de Daniel?',
 o:['Nabucodonosor','Belsasar','Darío','Ciro'],a:2},
{cap:'d1',t:'mc',q:'¿Bajo cuántos reinados distintos sirvió Daniel según el libro?',
 o:['Uno solo','Dos','Tres','Cuatro: Nabucodonosor, Belsasar, Darío y Ciro'],a:3},
{cap:'d2',t:'tf',q:'Beltsasar y Belsasar son la misma persona.',
 a:false,e:'Falso. Beltsasar es el nombre babilónico de DANIEL (1:7); Belsasar es el REY del capítulo 5.'},

];

BANCO.push(...BANCO_EXTRA);

/* Completar el versículo — segunda tanda */
BANCO.push(
{cap:'d1',t:'fill',ins:'Daniel 1:8 (RV1995) — Completa:',
 p:[{x:'«Y Daniel propuso en su '},{b:'corazón',h:'¿dónde?'},{x:' no '},{b:'contaminarse',h:'¿qué no hacer?'},{x:' con la porción de la comida del rey.»'}]},
{cap:'d1',t:'fill',ins:'Daniel 1:17 (RV1995) — Completa:',
 p:[{x:'«...y Daniel tuvo entendimiento en toda '},{b:'visión',h:'¿en qué?'},{x:' y '},{b:'sueños',h:'¿y qué más?'},{x:'.»'}]},
{cap:'d2',t:'fill',ins:'Daniel 2:28 (RV1995) — Completa:',
 p:[{x:'«Pero hay un Dios en los '},{b:'cielos',h:'¿dónde?'},{x:', el cual revela los '},{b:'misterios',h:'¿qué revela?'},{x:'.»'}]},
{cap:'d2',t:'fill',ins:'Daniel 2:44 (RV1995) — Completa:',
 p:[{x:'«...el Dios del cielo levantará un reino que no será jamás '},{b:'destruido',h:'¿qué no será?'},{x:'... pero él permanecerá para '},{b:'siempre',h:'¿hasta cuándo?'},{x:'.»'}]},
{cap:'d3',t:'fill',ins:'Daniel 3:18 (RV1995) — Completa la frase clave:',
 p:[{x:'«Y si '},{b:'no',h:'una palabra'},{x:', sepas, oh rey, que no serviremos a tus '},{b:'dioses',h:'¿a quiénes?'},{x:', ni tampoco adoraremos la estatua que has levantado.»'}]},
{cap:'d4',t:'fill',ins:'Daniel 4:34 (RV1995) — Completa:',
 p:[{x:'«...yo Nabucodonosor alcé mis '},{b:'ojos',h:'¿qué alzó?'},{x:' al '},{b:'cielo',h:'¿hacia dónde?'},{x:', y mi razón me fue devuelta.»'}]},
{cap:'d5',t:'fill',ins:'Daniel 5:26 (RV1995) — Completa:',
 p:[{x:'«MENE: '},{b:'Contó',h:'¿qué hizo Dios?'},{x:' Dios tu reino, y le ha puesto '},{b:'fin',h:'¿qué le puso?'},{x:'.»'}]},
{cap:'d5',t:'fill',ins:'Daniel 5:28 (RV1995) — Completa:',
 p:[{x:'«PERES: Tu reino ha sido '},{b:'roto',h:'¿qué le pasó?'},{x:', y dado a los '},{b:'medos',h:'¿a quiénes?'},{x:' y a los persas.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:4 (RV1995) — Completa:',
 p:[{x:'«...porque él era '},{b:'fiel',h:'¿cómo era?'},{x:', y ningún vicio ni '},{b:'falta',h:'¿ni qué?'},{x:' fue hallado en él.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:26 (RV1995) — Completa:',
 p:[{x:'«...porque él es el Dios '},{b:'viviente',h:'¿qué Dios?'},{x:' y permanece por todos los '},{b:'siglos',h:'¿por cuánto?'},{x:'.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:23 (RV1995) — Completa:',
 p:[{x:'«...y ninguna '},{b:'lesión',h:'¿qué no se halló?'},{x:' se halló en él, porque había '},{b:'confiado',h:'¿qué había hecho?'},{x:' en su Dios.»'}]},
);

/* ─── Ampliación 22-ago: derivadas de citas RV1995 ya verificadas
   en contenido.js y de afirmaciones auditadas de P&R ─── */
BANCO.push(
{cap:'d2',t:'fill',ins:'Daniel 2:35 (RV1995) — Completa:',
 p:[{x:'«...fueron desmenuzados... como '},{b:'tamo',h:'¿como qué?'},{x:' de las eras del verano...» «...un gran '},{b:'monte',h:'¿qué se hizo la piedra?'},{x:' que llenó toda la tierra.»'}]},
{cap:'d3',t:'fill',ins:'Daniel 3:17 (RV1995) — Completa:',
 p:[{x:'«He aquí nuestro Dios a quien '},{b:'servimos',h:'¿qué hacemos ante él?'},{x:' puede librarnos del horno de fuego ardiendo; y de tu mano, oh rey, nos '},{b:'librará',h:'¿qué hará?'},{x:'.»'}]},
{cap:'d4',t:'fill',ins:'Daniel 4:27 (RV1995) — Completa el consejo de Daniel al rey:',
 p:[{x:'«...tus pecados redime con '},{b:'justicia',h:'¿con qué?'},{x:', y tus iniquidades haciendo '},{b:'misericordias',h:'¿haciendo qué?'},{x:' para con los oprimidos...»'}]},
{cap:'d4',t:'fill',ins:'Daniel 4:30 (RV1995) — Completa la jactancia del rey:',
 p:[{x:'«¿No es ésta la gran '},{b:'Babilonia',h:'¿qué ciudad?'},{x:' que yo edifiqué... con la fuerza de mi poder y para gloria de mi '},{b:'majestad',h:'¿para gloria de qué?'},{x:'?»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:5 (RV1995) — Completa lo que dijeron los enemigos:',
 p:[{x:'«no hallaremos contra este Daniel '},{b:'ocasión',h:'¿qué no hallarán?'},{x:' alguna, si no la hallamos contra él en relación con la '},{b:'ley',h:'¿con qué de su Dios?'},{x:' de su Dios.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:27 (RV1995) — Completa:',
 p:[{x:'«Él salva y '},{b:'libra',h:'salva y ¿qué más?'},{x:', y hace señales y '},{b:'maravillas',h:'señales y ¿qué?'},{x:' en el cielo y en la tierra.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:26 (RV1995) — Completa:',
 p:[{x:'«Su reino no será jamás '},{b:'destruido',h:'¿qué no será?'},{x:', y su dominio perdurará hasta el '},{b:'fin',h:'¿hasta cuándo?'},{x:'.»'}]},
{cap:'pr39',t:'tf',q:'Según P&R cap. 39, el vino de la mesa del rey embotaba las facultades mentales y debilitaba el dominio propio.',
 a:true,e:'Verdadero. Es una de las razones por las que rechazaron la comida y el vino del rey.'},
{cap:'pr40',t:'tf',q:'Según P&R cap. 40, la piedra cortada sin manos representa a Cristo y el establecimiento de su reino eterno.',
 a:true,e:'Verdadero. La piedra destruye todos los reinos terrenales y permanece para siempre.'},
{cap:'pr41',t:'tf',q:'Según P&R cap. 41, los tres jóvenes condicionaron su obediencia a que Dios les garantizara el milagro.',
 a:false,e:'Falso. La frase «y si no» muestra que obedecieron sin condicionar su lealtad al resultado.'},
{cap:'pr42',t:'tf',q:'Según P&R cap. 42, Dios le concedió a Nabucodonosor un año completo para arrepentirse antes del juicio.',
 a:true,e:'Verdadero. El juicio solo cayó cuando la jactancia salió de su boca.'},
{cap:'pr43',t:'tf',q:'Según P&R cap. 43, Belsasar pecó por ignorancia porque no conocía la historia de Nabucodonosor.',
 a:false,e:'Falso. Conocía el orgullo, la humillación y la restauración de Nabucodonosor, y aun así eligió el mal.'},
{cap:'pr44',t:'tf',q:'Según P&R cap. 44, cuando llegó el decreto Daniel siguió orando como solía hacerlo antes, sin cambiar nada.',
 a:true,e:'Verdadero. No oró más para desafiar, ni menos para esconderse.'},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué efecto tenía el vino de la mesa del rey?',
 o:['Daba fuerza para el estudio','Embotaba las facultades mentales y debilitaba el dominio propio','Era saludable en pequeñas cantidades','Solo se servía en las fiestas'],a:1},
{cap:'pr40',t:'mc',q:'Según P&R cap. 40, ¿qué representa cada metal de la imagen?',
 o:['Un rey de Babilonia','Un imperio sucesivo en la historia','Una virtud del carácter','Una época de la iglesia'],a:1},
{cap:'pr42',t:'mc',q:'Según P&R cap. 42, ¿cuándo cayó el juicio sobre Nabucodonosor?',
 o:['Apenas Daniel interpretó el sueño','Cuando la jactancia salió de su boca','Al cumplirse siete años del sueño','Cuando atacó Jerusalén'],a:1},
{cap:'pr43',t:'mc',q:'Según P&R cap. 43, ¿qué acto colmó la medida de la impiedad de Belsasar?',
 o:['Burlarse de Daniel','Usar los vasos del templo para beber vino y alabar a los ídolos','Encarcelar a los sabios','Negarse a leer la escritura'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿qué encontraron los enemigos de Daniel al investigar su vida?',
 o:['Pequeñas faltas en su trabajo','Nada: su vida pública y privada eran igual de intachables','Errores solo en su juventud','Que descuidaba su cargo por orar'],a:1}
);

module.exports = { BANCO };
