/* Banco de preguntas. cap = capítulo al que pertenece.
   El examen se arma filtrando por los capítulos de la categoría. */

const BANCO = [

/* ─────────── DANIEL 1 ─────────── */
{cap:'d1',t:'mc',q:'¿En qué año del reinado de Joacim vino Nabucodonosor a Jerusalén y la sitió? (Daniel 1:1)',
 o:['En el primer año','En el segundo año','En el tercer año','En el cuarto año'],a:2},
{cap:'d1',t:'mc',q:'¿A dónde llevó Nabucodonosor los utensilios de la casa de Dios? (Daniel 1:2)',
 o:['Al palacio real de Babilonia','A la casa del tesoro de su dios, en tierra de Sinar','Al templo de Marduc','A la fortaleza de Susa'],a:1},
{cap:'d1',t:'mc',q:'¿Cómo se llamaba el jefe de los eunucos al que el rey dio la orden? (Daniel 1:3)',
 o:['Melsar','Arioc','Aspenaz','Nabuzaradán'],a:2},
{cap:'d1',t:'mc',q:'¿Cómo se llamaba el sirviente puesto directamente sobre Daniel y sus compañeros? (Daniel 1:11)',
 o:['Aspenaz','Arioc','Nabuzaradán','Melsar'],a:3},
{cap:'d1',t:'mc',q:'¿Cuántos años debían ser educados los jóvenes antes de presentarse ante el rey? (Daniel 1:5)',
 o:['Dos años','Tres años','Cinco años','Siete años'],a:1},
{cap:'d1',t:'mc',q:'¿Cuál era el nombre babilónico de Ananías? (Daniel 1:7)',
 o:['Sadrac','Mesac','Abed-nego','Beltsasar'],a:0},
{cap:'d1',t:'mc',q:'¿Cuál era el nombre babilónico de Azarías? (Daniel 1:7)',
 o:['Sadrac','Mesac','Abed-nego','Beltsasar'],a:2},
{cap:'d1',t:'mc',q:'¿Qué pidió Daniel que les dieran durante la prueba? (Daniel 1:12)',
 o:['Pan y agua','Legumbres para comer y agua para beber','Frutas y miel','Grano y aceite'],a:1},
{cap:'d1',t:'mc',q:'Según Daniel 1:15, ¿cómo apareció el rostro de los cuatro al cabo de los diez días?',
 o:['Más pálido pero más sabio','Igual que el de los demás','Mejor y más robusto que el de los otros muchachos','Más delgado pero más fuerte'],a:2},
{cap:'d1',t:'mc',q:'¿Cuántas veces mejores los halló el rey respecto a los magos y astrólogos? (Daniel 1:20)',
 o:['Dos veces','Cinco veces','Diez veces','Cien veces'],a:2},
{cap:'d1',t:'mc',q:'¿Qué don especial recibió Daniel que no se menciona para los otros tres? (Daniel 1:17)',
 o:['Poder para sanar','Entendimiento en toda visión y sueños','Dominio de todas las lenguas','Fuerza física superior'],a:1},
{cap:'d1',t:'tf',q:'Daniel continuó en el servicio del rey hasta el año primero del rey Ciro. (Daniel 1:21)',
 a:true,e:'Verdadero. Daniel 1:21 lo dice textualmente.'},
{cap:'d1',t:'tf',q:'Fue Aspenaz quien aceptó directamente la prueba de los diez días propuesta por Daniel.',
 a:false,e:'Falso. Daniel habló con MELSAR, el sirviente que Aspenaz había puesto sobre ellos (Daniel 1:11).'},
{cap:'d1',t:'fill',ins:'Daniel 1:20 (RV1995) — Completa:',
 p:[{x:'«...los halló '},{b:'diez',h:'¿cuántas veces?'},{x:' veces mejores que todos los '},{b:'magos',h:'¿quiénes?'},{x:' y astrólogos que había en todo su reino.»'}]},
{cap:'d1',t:'fill',ins:'Daniel 1:15 (RV1995) — Completa:',
 p:[{x:'«Y al cabo de los diez días pareció el rostro de ellos '},{b:'mejor',h:'¿cómo?'},{x:' y más '},{b:'robusto',h:'¿cómo?'},{x:' que el de los otros muchachos.»'}]},

/* ─────────── DANIEL 2 ─────────── */
{cap:'d2',t:'mc',q:'¿En qué año del reinado de Nabucodonosor tuvo él sus sueños? (Daniel 2:1)',
 o:['En el primer año','En el segundo año','En el tercer año','En el décimo año'],a:1},
{cap:'d2',t:'mc',q:'¿Quién era Arioc? (Daniel 2:14)',
 o:['El jefe de los eunucos','El capitán de la guardia del rey','El principal de los magos','El mayordomo del palacio'],a:1},
{cap:'d2',t:'mc',q:'¿Cómo le fue revelado a Daniel el misterio del sueño? (Daniel 2:19)',
 o:['Por un ángel visible en el día','En visión de noche','Por voz audible desde el cielo','Leyendo los libros de los profetas'],a:1},
{cap:'d2',t:'mc',q:'¿De qué material eran el vientre y los muslos de la imagen? (Daniel 2:32)',
 o:['De plata','De hierro','De bronce','De barro cocido'],a:2},
{cap:'d2',t:'mc',q:'¿En qué parte hirió la piedra a la imagen? (Daniel 2:34)',
 o:['En la cabeza de oro','En el pecho de plata','En sus pies de hierro y de barro cocido','En las piernas de hierro'],a:2},
{cap:'d2',t:'mc',q:'Según Daniel 2:35, ¿con qué se comparó lo que quedó de la imagen desmenuzada?',
 o:['Con ceniza del altar','Con arena del desierto','Con tamo de las eras del verano','Con polvo del camino'],a:2},
{cap:'d2',t:'mc',q:'¿Qué cargo recibió Daniel tras interpretar el sueño? (Daniel 2:48)',
 o:['Príncipe del palacio real','Gobernador de la provincia de Babilonia y principal de los gobernadores sobre los sabios','Consejero personal del rey','Jefe del ejército'],a:1},
{cap:'d2',t:'mc',q:'¿Qué representa la piedra cortada sin manos? (Daniel 2:44-45)',
 o:['La caída de Babilonia','El reino eterno de Dios que no será jamás destruido','El imperio romano','La restauración de Jerusalén'],a:1},
{cap:'d2',t:'tf',q:'La cabeza de la gran imagen era de plata. (Daniel 2:32)',
 a:false,e:'Falso. La cabeza era de ORO FINO; el pecho y los brazos eran de plata.'},
{cap:'d2',t:'tf',q:'Daniel pidió tiempo al rey y oró con sus compañeros antes de recibir la revelación. (Daniel 2:16-18)',
 a:true,e:'Verdadero. Pidió tiempo, fue a su casa e hizo saber el asunto a sus compañeros para pedir misericordia.'},
{cap:'d2',t:'fill',ins:'Daniel 2:20 (RV1995) — Completa:',
 p:[{x:'«Sea bendito el nombre de Dios de siglos en siglos, porque suyos son el '},{b:'poder',h:'¿qué?'},{x:' y la '},{b:'sabiduría',h:'¿qué?'},{x:'.»'}]},

/* ─────────── DANIEL 3 ─────────── */
{cap:'d3',t:'mc',q:'¿Cuántos codos de altura tenía la estatua de oro? (Daniel 3:1)',
 o:['Seis codos','Treinta codos','Sesenta codos','Cien codos'],a:2},
{cap:'d3',t:'mc',q:'¿Cuántos codos de anchura tenía la estatua de oro? (Daniel 3:1)',
 o:['Tres codos','Seis codos','Doce codos','Veinte codos'],a:1},
{cap:'d3',t:'mc',q:'¿En qué lugar fue levantada la estatua de oro? (Daniel 3:1)',
 o:['Frente al palacio real','En el campo de Dura, en la provincia de Babilonia','En la llanura de Sinar','En el templo principal'],a:1},
{cap:'d3',t:'mc',q:'¿Cuál es el PRIMER instrumento de la lista de Daniel 3:5?',
 o:['La flauta','El arpa','La bocina','La cítara'],a:2},
{cap:'d3',t:'mc',q:'¿Cuál de estos instrumentos NO aparece en Daniel 3:5?',
 o:['La zampoña','El salterio','La trompeta','La cítara'],a:2},
{cap:'d3',t:'mc',q:'¿Cuántas veces más de lo acostumbrado mandó calentar el horno? (Daniel 3:19)',
 o:['Dos veces','Cuatro veces','Siete veces','Diez veces'],a:2},
{cap:'d3',t:'mc',q:'¿Con qué ropa fueron echados al horno los tres jóvenes? (Daniel 3:21)',
 o:["Con sus mantos y sus turbantes, pero sin calzados ni vestidos","Con sus mantos, sus calzados, sus turbantes y sus vestidos","Solo con las túnicas de lino que usaban los sacerdotes caldeos","Con las armaduras de los hombres vigorosos que los ataron"],a:1},
{cap:'d3',t:'mc',q:'¿Qué les ocurrió a los varones que echaron a los jóvenes al horno? (Daniel 3:22)',
 o:['Cayeron desmayados','La llama del fuego los mató','Huyeron aterrados','Fueron perdonados'],a:1},
{cap:'d3',t:'mc',q:'¿Cómo describió Nabucodonosor al cuarto personaje del horno? (Daniel 3:25)',
 o:['Semejante a un ángel del cielo','Semejante a un hombre de fuego','Semejante a un hijo de los dioses','Semejante al Hijo de Dios'],a:2},
{cap:'d3',t:'mc',q:'¿Qué decretó Nabucodonosor sobre quien blasfemara contra el Dios de los tres jóvenes? (Daniel 3:29)',
 o:['Prisión perpetua','Destierro del reino','Que sea descuartizado y su casa convertida en estercolero','Pérdida de todos sus bienes'],a:2},
{cap:'d3',t:'tf',q:'Al salir del horno, sus ropas quedaron intactas y ni siquiera olor de fuego tenían. (Daniel 3:27)',
 a:true,e:'Verdadero. RV1995: «el fuego no había tenido poder alguno sobre sus cuerpos... sus ropas, intactas, ni siquiera olor de fuego tenían».'},
{cap:'d3',t:'tf',q:'Los tres jóvenes dijeron que si Dios no los libraba, entonces sí adorarían la estatua.',
 a:false,e:'Falso. Dijeron: «Y si no, no serviremos a tus dioses ni adoraremos la estatua» (Daniel 3:18).'},
{cap:'d3',t:'fill',ins:'Daniel 3:25 (RV1995) — Completa:',
 p:[{x:'«Sin embargo, yo veo '},{b:'cuatro',h:'¿cuántos?'},{x:' hombres sueltos, que se pasean en medio del fuego sin sufrir ningún daño; y el aspecto del cuarto es semejante a un hijo de los '},{b:'dioses',h:'¿de quiénes? (así lo dijo el rey pagano)'},{x:'.»'}]},
{cap:'d3',t:'fill',ins:'Daniel 3:27 (RV1995) — Completa:',
 p:[{x:'«...el fuego no había tenido poder alguno sobre sus cuerpos y ni aun el cabello de sus cabezas se había '},{b:'quemado',h:'¿qué le pasó?'},{x:'; sus ropas, intactas, ni siquiera '},{b:'olor',h:'¿ni siquiera qué?'},{x:' de fuego tenían.»'}]},

/* ─────────── DANIEL 4 ─────────── */
{cap:'d4',t:'mc',q:'¿Hasta dónde llegaba la copa del árbol del sueño? (Daniel 4:11)',
 o:['Hasta las nubes','Hasta el cielo','Hasta los confines del mar','Hasta la cima del monte'],a:1},
{cap:'d4',t:'mc',q:'Según Daniel 4:15, ¿con qué debía quedar atada la cepa de las raíces?',
 o:['Con cuerdas de lino','Con cadenas de oro','Con atadura de hierro y de bronce','Con ataduras de plata'],a:2},
{cap:'d4',t:'mc',q:'¿Cuántos tiempos debían pasar sobre Nabucodonosor? (Daniel 4:25)',
 o:['Tres tiempos','Cinco tiempos','Siete tiempos','Doce tiempos'],a:2},
{cap:'d4',t:'mc',q:'¿Cuánto tiempo pasó entre la advertencia de Daniel y el cumplimiento? (Daniel 4:29)',
 o:['Siete días','Un mes','Doce meses','Tres años'],a:2},
{cap:'d4',t:'mc',q:'¿Cómo le creció el cabello a Nabucodonosor? (Daniel 4:33)',
 o:['Como lana blanca','Como plumas de águila','Como ramas secas','Como crin de caballo'],a:1},
{cap:'d4',t:'mc',q:'¿Qué acción marcó el momento en que recuperó la razón? (Daniel 4:34)',
 o:['Comió hierba del campo','Alzó sus ojos al cielo','Daniel oró por él','Sus consejeros lo llamaron'],a:1},
{cap:'d4',t:'mc',q:'¿Qué consejo le dio Daniel al rey antes del juicio? (Daniel 4:27)',
 o:['Que destruyera los ídolos','Que redimiera sus pecados con justicia y sus iniquidades haciendo misericordias para con los oprimidos','Que ayunara cuarenta días','Que liberara a los cautivos judíos'],a:1},
{cap:'d4',t:'tf',q:'Las uñas de Nabucodonosor crecieron como las de las aves. (Daniel 4:33)',
 a:true,e:'Verdadero. Daniel 4:33 lo dice junto con que su cabello creció como plumas de águila.'},
{cap:'d4',t:'fill',ins:'Daniel 4:37 (RV1995) — Completa:',
 p:[{x:'«Ahora yo Nabucodonosor alabo, engrandezco y glorifico al Rey del cielo, porque todas sus obras son '},{b:'verdaderas',h:'¿cómo son?'},{x:', y sus caminos '},{b:'justos',h:'¿cómo son?'},{x:'.»'}]},

/* ─────────── DANIEL 5 ─────────── */
{cap:'d5',t:'mc',q:'¿A cuántos príncipes hizo Belsasar su gran banquete? (Daniel 5:1)',
 o:['Quinientos','Ochocientos','Mil','Dos mil'],a:2},
{cap:'d5',t:'mc',q:'¿De dónde provenían los vasos que Belsasar mandó traer? (Daniel 5:2)',
 o:['Del templo de Marduc','Del tesoro personal del rey','Del templo que estaba en Jerusalén','De Persia'],a:2},
{cap:'d5',t:'mc',q:'¿Frente a qué objeto apareció la escritura en la pared? (Daniel 5:5)',
 o:['Frente al trono','Delante del candelero','Sobre el altar','Junto a la puerta principal'],a:1},
{cap:'d5',t:'mc',q:'¿Cuál es el texto exacto de la escritura? (Daniel 5:25)',
 o:['MENE, TEKEL, UPARSIN','MENE, MENE, TEKEL, PERES','MENE, MENE, TEKEL, UPARSIN','TEKEL, MENE, PERES, UPARSIN'],a:2},
{cap:'d5',t:'mc',q:'¿Qué significa TEKEL? (Daniel 5:27)',
 o:['Contó Dios tu reino y le ha puesto fin','Pesado has sido en balanza y fuiste hallado falto','Tu reino ha sido roto y dado a otros','Tus días están contados'],a:1},
{cap:'d5',t:'mc',q:'¿Qué significa PERES? (Daniel 5:28)',
 o:['Contó Dios tu reino','Pesado y hallado falto','Tu reino ha sido roto y dado a los medos y a los persas','Serás humillado hasta el polvo'],a:2},
{cap:'d5',t:'mc',q:'¿Qué tres cosas ofreció Belsasar a quien leyera la escritura? (Daniel 5:7)',
 o:['Oro, plata y tierras','Ser vestido de púrpura, collar de oro y ser el tercer señor del reino','Un palacio, siervos y honores militares','La mitad de su reino'],a:1},
{cap:'d5',t:'mc',q:'¿Cuántos años tenía Darío de Media al recibir el reino? (Daniel 5:31)',
 o:['Cincuenta años','Sesenta y dos años','Setenta años','Cuarenta y cinco años'],a:1},
{cap:'d5',t:'tf',q:'Belsasar fue muerto esa misma noche en que apareció la escritura. (Daniel 5:30)',
 a:true,e:'Verdadero. «La misma noche fue muerto Belsasar, rey de los caldeos» (Daniel 5:30).'},
{cap:'d5',t:'tf',q:'Fueron los magos de Babilonia quienes recordaron a Daniel ante el rey Belsasar.',
 a:false,e:'Falso. Fue LA REINA quien entró a la sala del banquete y le habló al rey de Daniel (Daniel 5:10-12).'},
{cap:'d5',t:'fill',ins:'Daniel 5:27 (RV1995) — Completa:',
 p:[{x:'«TEKEL: '},{b:'Pesado',h:'¿qué te hicieron?'},{x:' has sido en balanza y hallado '},{b:'falto',h:'¿cómo?'},{x:'.»'}]},

/* Agregadas el 29 ago 2026 para cerrar huecos que marcó tools/cobertura.js.
   SOLO se escribieron las de versículos cuyo texto RV1995 ya está citado y
   verificado dentro del propio material de la app (fuente/contenido.js). Los
   demás huecos de Daniel 4 y 5 quedan abiertos a propósito: sin el archivo de
   referencia que pide tools/verificar.js no se puede garantizar precisión
   literal, y una pregunta que no se puede verificar no entra al banco. */
{cap:'d4',t:'mc',q:'En el sueño de Nabucodonosor, ¿dónde estaba el árbol y cómo era su altura? (Daniel 4:10)',
 o:['En un valle, y era pequeño','En medio de la tierra, y su altura era grande','En la orilla del río, y era torcido','En el monte, y era seco'],a:1},
{cap:'d4',t:'tf',q:'Sobre el rey debían pasar siete tiempos. (Daniel 4:16)',
 a:true,e:'Verdadero. Daniel 4:16 y 4:25 dicen que siete tiempos pasarían sobre él.'},
{cap:'d4',t:'mc',q:'¿En qué momento exacto vino la voz del cielo sobre Nabucodonosor? (Daniel 4:31)',
 o:['Un año después de la jactancia','Mientras dormía esa noche','Aún estaba la palabra en su boca','Al amanecer del día siguiente'],a:2},
{cap:'d5',t:'tf',q:'Alguno de los sabios de Babilonia logró leer la escritura de la pared, pero no supo interpretarla. (Daniel 5:8)',
 a:false,e:'Falso. Daniel 5:8 dice que ninguno pudo leer la escritura NI mostrar al rey su interpretación.'},

/* ─────────── DANIEL 6 ─────────── */
{cap:'d6',t:'mc',q:'¿Cuántos sátrapas constituyó Darío sobre el reino? (Daniel 6:1)',
 o:['Ochenta','Cien','Ciento veinte','Ciento cincuenta'],a:2},
{cap:'d6',t:'mc',q:'¿Cuántos gobernadores puso sobre los sátrapas? (Daniel 6:2)',
 o:['Dos','Tres','Cuatro','Siete'],a:1},
{cap:'d6',t:'mc',q:'¿Por qué sobresalía Daniel sobre los demás? (Daniel 6:3)',
 o:['Porque era el más antiguo','Porque había en él un espíritu superior','Porque era pariente del rey','Porque hablaba muchos idiomas'],a:1},
{cap:'d6',t:'mc',q:'¿Por qué no pudieron hallar ocasión para acusar a Daniel? (Daniel 6:4)',
 o:['Porque el rey lo protegía','Porque él era fiel y ningún error ni falta hallaron en él','Porque era demasiado poderoso','Porque sus enemigos eran torpes'],a:1},
{cap:'d6',t:'mc',q:'¿Cuántos días duraba el edicto que prohibía orar a otro que no fuera el rey? (Daniel 6:7)',
 o:['Diez días','Veinte días','Treinta días','Cuarenta días'],a:2},
{cap:'d6',t:'mc',q:'¿Hacia dónde daban las ventanas de la habitación donde oraba Daniel? (Daniel 6:10)',
 o:['Hacia el palacio real','Hacia el oriente','Hacia Jerusalén','Hacia el río'],a:2},
{cap:'d6',t:'mc',q:'¿Con qué fue sellada la piedra sobre la puerta del foso? (Daniel 6:17)',
 o:['Solo con el anillo del rey','Con el anillo del rey y con el de sus príncipes','Con cadenas de hierro','Con cera y el sello del templo'],a:1},
{cap:'d6',t:'mc',q:'¿Qué hizo el rey Darío aquella noche? (Daniel 6:18)',
 o:["Se acostó después de cenar, mandó traer músicos para distraerse, y durmió hasta el alba","Se acostó en ayunas; no trajeron ante él instrumentos musicales, y se le fue el sueño","Pasó la noche junto a la piedra sellada del foso, sin comer ni beber nada","Reunió a sus consejeros toda la noche para buscar cómo abrogar el edicto firmado"],a:1},
{cap:'d6',t:'mc',q:'¿En qué momento fue Darío al foso? (Daniel 6:19)',
 o:['Al mediodía','Al anochecer','Muy de mañana, y fue apresuradamente al foso','A la hora tercera'],a:2},
{cap:'d6',t:'mc',q:'¿Qué respondió Daniel sobre por qué estaba ileso? (Daniel 6:22)',
 o:['Que los leones estaban dormidos','Que Dios envió su ángel, el cual cerró la boca de los leones','Que se hizo invisible','Que los leones ya estaban saciados'],a:1},
{cap:'d6',t:'tf',q:'El rey Darío trabajó hasta la puesta del sol tratando de librar a Daniel. (Daniel 6:14)',
 a:true,e:'Verdadero. «...y hasta la puesta del sol trabajó para librarle» (Daniel 6:14).'},
{cap:'d6',t:'tf',q:'Daniel dejó de orar durante los treinta días del edicto para no arriesgarse.',
 a:false,e:'Falso. Siguió orando tres veces al día, «como solía hacerlo antes» (Daniel 6:10).'},
{cap:'d6',t:'fill',ins:'Daniel 6:10 (RV1995) — Completa:',
 p:[{x:'«...abiertas las ventanas de su habitación que daban a '},{b:'Jerusalén',h:'¿hacia dónde?'},{x:', se arrodillaba '},{b:'tres',h:'¿cuántas veces?'},{x:' veces al día, oraba y daba gracias delante de su Dios como solía hacerlo antes.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:22 (RV1995) — Completa:',
 p:[{x:'«Mi Dios envió su '},{b:'ángel',h:'¿a quién?'},{x:', el cual cerró la boca de los '},{b:'leones',h:'¿de qué?'},{x:' para que no me hicieran daño.»'}]},

/* ─────────── P&R 39 ─────────── */
{cap:'pr39',t:'mc',q:'¿Cuál es el título del capítulo 39 de Profetas y Reyes?',
 o:['Cautivos en Babilonia','En la corte de Babilonia','El fiel en tierra extraña','En la corte del rey'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿por qué razón principal rechazó Daniel la comida del rey?',
 o:["Era comida de extranjeros y su pueblo no la acostumbraba en Judá","Había sido ofrecida a los ídolos y violaba las leyes de Dios","Estaba reservada al rey y compartirla se castigaba con la muerte","Los sabios de Babilonia le habían advertido que estaba envenenada"],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué relación hay entre los hábitos físicos y la mente?',
 o:['Ninguna relación','Los hábitos temperantes favorecen la claridad mental y espiritual','Solo la oración afecta el intelecto','El cuerpo y la mente son independientes'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿cuál era el mayor peligro para los jóvenes hebreos?',
 o:['La persecución abierta','La tentación de ceder poco a poco en sus principios','El clima de Babilonia','La falta de alimentos'],a:1},
{cap:'pr39',t:'tf',q:'Según P&R cap. 39, Daniel se negó a la comida del rey de forma rebelde y desafiante.',
 a:false,e:'Falso. Elena de White destaca que fue firme y cortés a la vez, y propuso una prueba razonable.'},

/* ─────────── P&R 40 ─────────── */
{cap:'pr40',t:'mc',q:'¿Cuál es el título del capítulo 40 de Profetas y Reyes?',
 o:['La gran imagen','El sueño de Nabucodonosor','El misterio revelado','La piedra y el monte'],a:1},
{cap:'pr40',t:'mc',q:'Según P&R cap. 40, ¿a qué recurrieron primero Daniel y sus compañeros ante la sentencia?',
 o:['A la estrategia política','A la oración','A los libros de los sabios','A pedir clemencia al rey'],a:1},
{cap:'pr40',t:'mc',q:'Según P&R cap. 40, ¿qué representa la piedra cortada sin manos?',
 o:['La caída de Babilonia','Cristo y el establecimiento de su reino eterno','La restauración de Israel','El fin del imperio griego'],a:1},
{cap:'pr40',t:'tf',q:'Según P&R cap. 40, la sucesión de los imperios muestra que la historia es gobernada por Dios.',
 a:true,e:'Verdadero. La imagen revela que Dios gobierna el reino de los hombres y dirige el curso de la historia.'},

/* ─────────── P&R 41 ─────────── */
{cap:'pr41',t:'mc',q:'¿Cuál es el título del capítulo 41 de Profetas y Reyes?',
 o:['El horno de fuego','La imagen de oro','Los tres hebreos fieles','La prueba de la fe'],a:0},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿quién era el cuarto personaje del horno?',
 o:['Un ángel creado','El Espíritu Santo','El Hijo de Dios mismo','El profeta Elías'],a:2},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿qué muestra la frase «y si no» de los tres jóvenes?',
 o:['Que dudaban del poder de Dios','Que su obediencia no dependía de recibir el milagro','Que negociaban con el rey','Que esperaban morir'],a:1},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿para qué es un modelo la experiencia del horno?',
 o:['Solo para casos de idolatría literal','Para la crisis final cuando se exija adoración contraria a Dios','Para los conflictos políticos','No tiene aplicación moderna'],a:1},
{cap:'pr41',t:'tf',q:'Según P&R cap. 41, Dios libró a los tres jóvenes evitando que entraran al horno.',
 a:false,e:'Falso. No los libró DE la prueba: el Hijo de Dios estuvo con ellos DENTRO del horno.'},

/* ─────────── P&R 42 ─────────── */
{cap:'pr42',t:'mc',q:'¿Cuál es el título del capítulo 42 de Profetas y Reyes?',
 o:['Nabucodonosor humillado','El orgullo del rey','La verdadera grandeza','El rey entre las bestias'],a:2},
{cap:'pr42',t:'mc',q:'Según P&R cap. 42, ¿cuál fue el pecado principal de Nabucodonosor?',
 o:['La idolatría','El orgullo, al atribuirse la gloria que pertenecía a Dios','La crueldad con los cautivos','El saqueo del templo'],a:1},
{cap:'pr42',t:'mc',q:'Según P&R cap. 42, ¿cuánto tiempo de gracia recibió el rey antes del juicio?',
 o:['Siete días','Un mes','Un año completo','Tres años'],a:2},
{cap:'pr42',t:'tf',q:'Según P&R cap. 42, Nabucodonosor murió sin reconocer nunca la soberanía de Dios.',
 a:false,e:'Falso. Fue restaurado y terminó siendo adorador del Dios verdadero; su testimonio final es uno de los más poderosos de la Biblia.'},

/* ─────────── P&R 43 ─────────── */
{cap:'pr43',t:'mc',q:'¿Cuál es el título del capítulo 43 de Profetas y Reyes?',
 o:['La fiesta de Belsasar','La escritura en la pared','El vigía invisible','El último rey'],a:2},
{cap:'pr43',t:'mc',q:'Según P&R cap. 43, ¿por qué Belsasar no tenía excusa?',
 o:['Porque era un rey justo','Porque conocía la experiencia de Nabucodonosor y aun así se rebeló','Porque los profetas le hablaron en persona','Porque había leído las Escrituras'],a:1},
{cap:'pr43',t:'mc',q:'Según P&R cap. 43, ¿qué representó usar los vasos sagrados en el banquete?',
 o:['Un descuido de protocolo','Una costumbre normal de la época','Un desafío deliberado a Dios y la cima de su impiedad','Un gesto de generosidad'],a:2},
{cap:'pr43',t:'tf',q:'Según P&R cap. 43, mayor conocimiento implica mayor responsabilidad delante de Dios.',
 a:true,e:'Verdadero. Belsasar tenía más luz que Nabucodonosor, y por eso su culpa fue mayor.'},

/* ─────────── P&R 44 ─────────── */
{cap:'pr44',t:'mc',q:'¿Cuál es el título del capítulo 44 de Profetas y Reyes?',
 o:['Daniel el profeta fiel','El profeta y el rey','En el foso de los leones','Fidelidad hasta el fin'],a:2},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿qué caracterizaba la oración de Daniel?',
 o:['Que oraba solo en las crisis','Que era la fuente diaria de su fortaleza','Que oraba para ser visto','Que era una formalidad religiosa'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿por qué sus enemigos no hallaron falta en Daniel?',
 o:['Porque el rey lo protegía','Porque su vida pública y privada eran igual de intachables','Porque era muy poderoso','Porque escondía bien sus faltas'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿qué enseña el ejemplo de Daniel a los jóvenes?',
 o:['Que deben evitar los cargos públicos','Que pueden ser testigos fieles de Dios en cualquier posición','Que la fidelidad siempre trae milagros visibles','Que deben apartarse de la sociedad'],a:1},
{cap:'pr44',t:'tf',q:'Según P&R cap. 44, Daniel era un hombre joven cuando fue echado al foso de los leones.',
 a:false,e:'Falso. Tenía más de ochenta años. Lo que decidió de joven (Daniel 1) fue lo que lo sostuvo de anciano.'},

];

/* Preguntas adicionales — segunda tanda, para estudio profundo. */
const BANCO_EXTRA = [

/* DANIEL 1 */
{cap:'d1',t:'mc',q:'Según Daniel 1:4, ¿qué debían aprender los jóvenes escogidos?',
 o:['Las artes de la guerra','Las letras y la lengua de los caldeos','La astrología babilónica','La administración del reino'],a:1},
{cap:'d1',t:'mc',q:'¿Qué hizo Dios por Daniel ante el jefe de los eunucos? (Daniel 1:9)',
 o:['Le envió un sueño','Puso a Daniel en gracia y en buena voluntad ante él','Le habló por medio de un ángel','Lo hizo enfermar'],a:1},
{cap:'d1',t:'mc',q:'Según Daniel 1:8, ¿dónde tomó Daniel su decisión de no contaminarse?',
 o:['En público, delante del rey','Propuso en su corazón','Por consejo de sus compañeros','Después de consultar a un sacerdote'],a:1},
{cap:'d1',t:'mc',q:'¿Qué hizo Melsar al comprobar el resultado de la prueba? (Daniel 1:16)',
 o:["Informó al rey del resultado y pidió que se cambiara la orden","Se llevaba la porción de comida y el vino, y les daba legumbres","Repartió la porción del rey entre los otros muchachos del palacio","Extendió la prueba de las legumbres a todos los jóvenes cautivos"],a:1},
{cap:'d1',t:'tf',q:'Los jóvenes escogidos debían ser de aquellos en quienes no hubiera tacha alguna. (Daniel 1:4)',
 a:true,e:'Verdadero. Ésa es la primera condición que menciona Daniel 1:4.'},

/* DANIEL 2 */
{cap:'d2',t:'mc',q:'¿Qué amenazó el rey a los caldeos si no revelaban el sueño? (Daniel 2:5)',
 o:['Prisión perpetua','Destierro','Ser hechos pedazos y sus casas convertidas en estercoleros','Perder sus cargos'],a:2},
{cap:'d2',t:'mc',q:'¿Qué declaró Daniel ante el rey sobre el origen de la revelación? (Daniel 2:28)',
 o:['Que él era el más sabio de todos','Que hay un Dios en los cielos que revela los misterios','Que lo dedujo de los astros','Que se lo dijo un ángel en secreto'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:43, ¿por qué el hierro y el barro no se unen?',
 o:['Porque el barro es débil','Porque no se unirán el uno con el otro, como el hierro no se mezcla con el barro','Porque están separados por el tiempo','Porque uno destruye al otro'],a:1},
{cap:'d2',t:'tf',q:'Daniel pidió a sus compañeros que oraran pidiendo misericordias del Dios del cielo sobre el misterio. (Daniel 2:18)',
 a:true,e:'Verdadero. Daniel 2:18 lo dice textualmente.'},

/* DANIEL 3 */
{cap:'d3',t:'mc',q:'¿Cuántas veces se repite la lista de instrumentos en Daniel 3?',
 o:['Una vez','Dos veces','Tres veces','Cuatro veces (vv. 5, 7, 10 y 15)'],a:3},
{cap:'d3',t:'mc',q:'Según Daniel 3:19, ¿qué le pasó al rostro de Nabucodonosor?',
 o:['Palideció de miedo','Se demudó contra Sadrac, Mesac y Abed-nego','Sonrió con desprecio','Se llenó de lágrimas'],a:1},
{cap:'d3',t:'mc',q:'¿Quiénes se juntaron para ver que el fuego no los había dañado? (Daniel 3:27)',
 o:['Solo el rey','El pueblo de Babilonia','Los sátrapas, gobernadores, capitanes y consejeros del rey','Los sacerdotes del templo'],a:2},
{cap:'d3',t:'mc',q:'Según Daniel 3:29, ¿qué reconoció Nabucodonosor sobre el Dios de los hebreos?',
 o:['Que era uno más entre los dioses','Que no hay dios que pueda librar como él','Que era el dios de una nación pequeña','Que su poder era limitado'],a:1},
{cap:'d3',t:'tf',q:'Después del milagro, Nabucodonosor engrandeció a los tres jóvenes en la provincia de Babilonia. (Daniel 3:30)',
 a:true,e:'Verdadero. Daniel 3:30 cierra el capítulo con esa promoción.'},

/* DANIEL 4 */
{cap:'d4',t:'mc',q:'Según Daniel 4:12, ¿qué había debajo y en las ramas del árbol?',
 o:['Solo pastores','Las bestias del campo debajo y las aves del cielo en sus ramas','Ejércitos acampados','Ciudades enteras'],a:1},
{cap:'d4',t:'mc',q:'¿Cuál era el propósito declarado del juicio sobre el rey? (Daniel 4:17)',
 o:['Castigar su crueldad','Para que conozcan que el Altísimo gobierna el reino de los hombres','Vengar a los cautivos','Destruir Babilonia'],a:1},
{cap:'d4',t:'mc',q:'¿Qué dijo Nabucodonosor justo antes de que cayera el juicio? (Daniel 4:30)',
 o:['«Que venga el juicio de los dioses»','«¿No es ésta la gran Babilonia que yo edifiqué?»','«Nadie puede tocar mi reino»','«Los dioses me han bendecido»'],a:1},
{cap:'d4',t:'tf',q:'Después de su restauración, a Nabucodonosor le fue añadida mayor grandeza. (Daniel 4:36)',
 a:true,e:'Verdadero. Fue restituido en su reino y «mayor grandeza me fue añadida».'},

/* DANIEL 5 */
{cap:'d5',t:'mc',q:'¿Quiénes bebieron en los vasos del templo? (Daniel 5:3)',
 o:['Solo el rey','El rey, sus príncipes, sus mujeres y sus concubinas','Los sacerdotes de Babilonia','Los embajadores extranjeros'],a:1},
{cap:'d5',t:'mc',q:'¿A qué dioses alabaron durante el banquete? (Daniel 5:4)',
 o:['Solo a Marduc','A los dioses de oro, plata, bronce, hierro, madera y piedra','A los dioses del cielo','A los antepasados del rey'],a:1},
{cap:'d5',t:'mc',q:'Según Daniel 5:6, ¿qué le ocurrió al rey al ver la escritura?',
 o:['Se desmayó','Se demudó su rostro, se debilitaron sus lomos y sus rodillas daban la una contra la otra','Se enfureció','Huyó de la sala'],a:1},
{cap:'d5',t:'tf',q:'Belsasar cumplió lo prometido y vistió a Daniel de púrpura antes de morir. (Daniel 5:29)',
 a:true,e:'Verdadero. Daniel 5:29 dice que lo vistieron de púrpura y fue proclamado tercer señor del reino.'},

/* DANIEL 6 */
{cap:'d6',t:'mc',q:'¿Qué buscaban los gobernadores para acusar a Daniel? (Daniel 6:4)',
 o:['Testigos falsos','Ocasión de acusarlo en lo relacionado con el reino','Documentos secretos','Testimonios de sus enemigos'],a:1},
{cap:'d6',t:'mc',q:'¿Qué concluyeron sus enemigos que era la única vía para acusarlo? (Daniel 6:5)',
 o:['Sobornar a un testigo','Hallar algo en relación con la ley de su Dios','Acusarlo de robo','Convencer al rey de destituirlo'],a:1},
{cap:'d6',t:'mc',q:'¿Hasta cuándo trabajó el rey Darío para librar a Daniel? (Daniel 6:14)',
 o:['Hasta el mediodía','Hasta la puesta del sol','Toda la noche','Solo unos minutos'],a:1},
{cap:'d6',t:'mc',q:'¿Por qué no se halló lesión alguna en Daniel? (Daniel 6:23)',
 o:['Porque los leones estaban saciados','Porque había confiado en su Dios','Porque el foso era poco profundo','Porque lo sacaron rápido'],a:1},
{cap:'d6',t:'mc',q:'Según el decreto de Darío, ¿cómo se describe a Dios? (Daniel 6:26)',
 o:['El más grande entre los dioses','El Dios viviente que permanece por todos los siglos','El dios de los hebreos','Un dios poderoso entre otros'],a:1},
{cap:'d6',t:'tf',q:'Los acusadores de Daniel fueron echados al foso junto con sus hijos y sus mujeres. (Daniel 6:24)',
 a:true,e:'Verdadero. Daniel 6:24 lo dice, y añade que los leones se apoderaron de ellos.'},

/* TRANSVERSALES — comparación entre capítulos */
{cap:'d5',t:'mc',q:'¿Cuál rey terminó alabando, engrandeciendo y glorificando al Rey del cielo?',
 o:['Belsasar','Nabucodonosor','Darío','Joacim'],a:1},
{cap:'d6',t:'mc',q:'¿Cuál rey emitió un decreto para que todos temieran al Dios de Daniel?',
 o:['Nabucodonosor','Belsasar','Darío','Ciro'],a:2},
{cap:'d1',t:'mc',q:'¿Bajo cuántos reinados distintos sirvió Daniel según el libro?',
 o:["Dos: Nabucodonosor y Ciro el persa","Tres: Nabucodonosor, Belsasar y Darío","Cinco: Nabucodonosor, Beltsasar, Belsasar, Darío y Ciro","Cuatro: Nabucodonosor, Belsasar, Darío y Ciro"],a:3},
{cap:'d2',t:'tf',q:'Beltsasar y Belsasar son la misma persona.',
 a:false,e:'Falso. Beltsasar es el nombre babilónico de DANIEL (1:7); Belsasar es el REY del capítulo 5.'},

];

BANCO.push(...BANCO_EXTRA);

/* Completar el versículo — segunda tanda */
BANCO.push(
{cap:'d1',t:'fill',ins:'Daniel 1:8 (RV1995) — Completa:',
 p:[{x:'«Daniel propuso en su '},{b:'corazón',h:'¿dónde?'},{x:' no '},{b:'contaminarse',h:'¿qué no hacer?'},{x:' con la porción de la comida del rey.»'}]},
{cap:'d1',t:'fill',ins:'Daniel 1:17 (RV1995) — Completa:',
 p:[{x:'«...y Daniel tuvo entendimiento en toda '},{b:'visión',h:'¿en qué?'},{x:' y '},{b:'sueños',h:'¿y qué más?'},{x:'.»'}]},
{cap:'d2',t:'fill',ins:'Daniel 2:28 (RV1995) — Completa:',
 p:[{x:'«Pero hay un Dios en los '},{b:'cielos',h:'¿dónde?'},{x:' que revela los '},{b:'misterios',h:'¿qué revela?'},{x:'.»'}]},
{cap:'d2',t:'fill',ins:'Daniel 2:44 (RV1995) — Completa:',
 p:[{x:'«...el Dios del cielo levantará un reino que no será jamás '},{b:'destruido',h:'¿qué no será?'},{x:'... pero él permanecerá para '},{b:'siempre',h:'¿hasta cuándo?'},{x:'.»'}]},
{cap:'d3',t:'fill',ins:'Daniel 3:18 (RV1995) — Completa la frase clave:',
 p:[{x:'«Y si '},{b:'no',h:'una palabra'},{x:', has de saber, oh rey, que no serviremos a tus '},{b:'dioses',h:'¿a quiénes?'},{x:' ni tampoco adoraremos la estatua que has levantado.»'}]},
{cap:'d4',t:'fill',ins:'Daniel 4:34 (RV1995) — Completa:',
 p:[{x:'«...yo Nabucodonosor alcé mis '},{b:'ojos',h:'¿qué alzó?'},{x:' al '},{b:'cielo',h:'¿hacia dónde?'},{x:', y mi razón me fue devuelta.»'}]},
{cap:'d5',t:'fill',ins:'Daniel 5:26 (RV1995) — Completa:',
 p:[{x:'«MENE: '},{b:'Contó',h:'¿qué hizo Dios?'},{x:' Dios tu reino, y le ha puesto '},{b:'fin',h:'¿qué le puso?'},{x:'.»'}]},
{cap:'d5',t:'fill',ins:'Daniel 5:28 (RV1995) — Completa:',
 p:[{x:'«PERES: Tu reino ha sido '},{b:'roto',h:'¿qué le pasó?'},{x:', y dado a los '},{b:'medos',h:'¿a quiénes?'},{x:' y a los persas.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:4 (RV1995) — Completa:',
 p:[{x:'«...porque él era '},{b:'fiel',h:'¿cómo era?'},{x:', y ningún '},{b:'error',h:'¿ni qué? (RV1995)'},{x:' ni falta hallaron en él.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:26 (RV1995) — Completa:',
 p:[{x:'«Porque él es el Dios '},{b:'viviente',h:'¿qué Dios?'},{x:' y permanece por todos los '},{b:'siglos',h:'¿por cuánto?'},{x:'.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:23 (RV1995) — Completa:',
 p:[{x:'«...pero ninguna '},{b:'lesión',h:'¿qué no se halló?'},{x:' se halló en él, porque había '},{b:'confiado',h:'¿qué había hecho?'},{x:' en su Dios.»'}]},
);

/* ─── Ampliación 22-ago: derivadas de citas RV1995 ya verificadas
   en contenido.js y de afirmaciones auditadas de P&R ─── */
BANCO.push(
{cap:'d2',t:'fill',ins:'Daniel 2:35 (RV1995) — Completa:',
 p:[{x:'«...fueron desmenuzados... como '},{b:'tamo',h:'¿como qué?'},{x:' de las eras del verano...» «...un gran '},{b:'monte',h:'¿qué se hizo la piedra?'},{x:' que llenó toda la tierra.»'}]},
{cap:'d3',t:'fill',ins:'Daniel 3:17 (RV1995) — Completa:',
 p:[{x:'«Nuestro Dios, a quien '},{b:'servimos',h:'¿qué hacemos ante él?'},{x:', puede librarnos del horno de fuego ardiente; y de tus manos, rey, nos '},{b:'librará',h:'¿qué hará?'},{x:'.»'}]},
{cap:'d4',t:'fill',ins:'Daniel 4:27 (RV1995) — Completa el consejo de Daniel al rey:',
 p:[{x:'«...redime tus pecados con '},{b:'justicia',h:'¿con qué?'},{x:', y tus iniquidades haciendo '},{b:'misericordias',h:'¿haciendo qué?'},{x:' con los oprimidos...»'}]},
{cap:'d4',t:'fill',ins:'Daniel 4:30 (RV1995) — Completa la jactancia del rey:',
 p:[{x:'«¿No es ésta la gran '},{b:'Babilonia',h:'¿qué ciudad?'},{x:' que yo edifiqué... con la fuerza de mi poder y para gloria de mi '},{b:'majestad',h:'¿para gloria de qué?'},{x:'?»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:5 (RV1995) — Completa lo que dijeron los enemigos:',
 p:[{x:'«No hallaremos contra este Daniel '},{b:'motivo',h:'¿qué no hallarán? (RV1995)'},{x:' alguno para acusarlo, si no lo hallamos contra él en relación con la '},{b:'ley',h:'¿con qué de su Dios?'},{x:' de su Dios.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:27 (RV1995) — Completa:',
 p:[{x:'«Él salva y '},{b:'libra',h:'salva y ¿qué más?'},{x:', y hace señales y '},{b:'maravillas',h:'señales y ¿qué?'},{x:' en el cielo y en la tierra.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:26 (RV1995) — Completa el final del versículo:',
 p:[{x:'«su reino no será jamás '},{b:'destruido',h:'¿qué no será?'},{x:' y su dominio perdurará hasta el '},{b:'fin',h:'¿hasta cuándo?'},{x:'.»'}]},
{cap:'pr39',t:'tf',q:'Según P&R cap. 39, el vino de la mesa del rey embotaba las facultades mentales y debilitaba el dominio propio.',
 a:true,e:'Verdadero. Es una de las razones por las que rechazaron la comida y el vino del rey.'},
{cap:'pr40',t:'tf',q:'Según P&R cap. 40, la piedra cortada sin manos representa a Cristo y el establecimiento de su reino eterno.',
 a:true,e:'Verdadero. La piedra destruye todos los reinos terrenales y permanece para siempre.'},
{cap:'pr41',t:'tf',q:'Según P&R cap. 41, los tres jóvenes condicionaron su obediencia a que Dios les garantizara el milagro.',
 a:false,e:'Falso. La frase «y si no» muestra que obedecieron sin condicionar su lealtad al resultado.'},
{cap:'pr42',t:'tf',q:'Según P&R cap. 42, Dios le concedió a Nabucodonosor un año completo para arrepentirse antes del juicio.',
 a:true,e:'Verdadero. El juicio solo cayó cuando la jactancia salió de su boca.'},
{cap:'pr43',t:'tf',q:'Según P&R cap. 43, Belsasar pecó por ignorancia porque no conocía la historia de Nabucodonosor.',
 a:false,e:'Falso. Conocía el orgullo, la humillación y la restauración de Nabucodonosor, y aun así eligió el mal.'},
{cap:'pr44',t:'tf',q:'Según P&R cap. 44, cuando llegó el decreto Daniel siguió orando como solía hacerlo antes, sin cambiar nada.',
 a:true,e:'Verdadero. No oró más para desafiar, ni menos para esconderse.'},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué efecto tenía el vino de la mesa del rey?',
 o:['Daba fuerza para el estudio','Embotaba las facultades mentales y debilitaba el dominio propio','Era saludable en pequeñas cantidades','Solo se servía en las fiestas'],a:1},
{cap:'pr40',t:'mc',q:'Según P&R cap. 40, ¿qué representa cada metal de la imagen?',
 o:['Un rey de Babilonia','Un imperio sucesivo en la historia','Una virtud del carácter','Una época de la iglesia'],a:1},
{cap:'pr42',t:'mc',q:'Según P&R cap. 42, ¿cuándo cayó el juicio sobre Nabucodonosor?',
 o:['Apenas Daniel interpretó el sueño','Cuando la jactancia salió de su boca','Al cumplirse siete años del sueño','Cuando atacó Jerusalén'],a:1},
{cap:'pr43',t:'mc',q:'Según P&R cap. 43, ¿qué acto colmó la medida de la impiedad de Belsasar?',
 o:['Burlarse de Daniel','Usar los vasos del templo para beber vino y alabar a los ídolos','Encarcelar a los sabios','Negarse a leer la escritura'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿qué encontraron los enemigos de Daniel al investigar su vida?',
 o:['Pequeñas faltas en su trabajo','Nada: su vida pública y privada eran igual de intachables','Errores solo en su juventud','Que descuidaba su cargo por orar'],a:1}
);

/* ─── Ampliación 22-ago (2): precisión RV1995 y distinciones finas.
   Todas verificadas contra el texto RV1995 y el índice de P&R. ─── */
BANCO.push(
{cap:'d1',t:'mc',q:'Según la RV1995, ¿cómo pareció el rostro de los cuatro jóvenes al cabo de los diez días? (Daniel 1:15)',
 o:['Más rozagante y más robusto','Mejor y más robusto','Más sano y más fuerte','Mejor y más hermoso'],a:1},
{cap:'d1',t:'tf',q:'La RV1995 dice que el rostro de los jóvenes pareció «más rozagante» que el de los otros muchachos. (Daniel 1:15)',
 a:false,e:'Falso. «Más rozagante» es de la RV1960. La RV1995 dice «mejor y más robusto».'},
{cap:'d2',t:'mc',q:'Según la RV1995, ¿en qué serían convertidas las casas de los sabios si no declaraban el sueño? (Daniel 2:5)',
 o:['En muladares','En estercoleros','En ruinas','En sepulcros'],a:1},
{cap:'d3',t:'mc',q:'Según la RV1995, ¿cómo describió Nabucodonosor el aspecto del cuarto hombre del horno? (Daniel 3:25)',
 o:['Semejante al Hijo de Dios','Semejante a un ángel del cielo','Semejante a un hijo de los dioses','Semejante a un varón de fuego'],a:2},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿quién era en realidad ese cuarto personaje que el rey vio en el horno?',
 o:['Un ángel de alto rango','El Hijo de Dios mismo','El profeta Ezequiel','Una visión sin persona real'],a:1},
{cap:'d3',t:'tf',q:'Daniel 3:25 y Profetas y Reyes 41 se contradicen sobre quién era el cuarto varón del horno.',
 a:false,e:'Falso. Daniel 3:25 registra lo que dijo Nabucodonosor, un rey pagano: «un hijo de los dioses». P&R 41 revela que era el Hijo de Dios. Una cosa es lo que el rey vio y dijo; la otra, lo que la inspiración identifica.'},
{cap:'d3',t:'mc',q:'Según la RV1995, ¿cómo quedaron las ropas de los tres jóvenes al salir del horno? (Daniel 3:27)',
 o:['Chamuscadas en los bordes','Intactas, sin siquiera olor de fuego','Quemadas, aunque su cuerpo ileso','Cubiertas de ceniza'],a:1},
{cap:'d3',t:'mc',q:'Según la RV1995, ¿en qué sería convertida la casa del que hablara blasfemia contra el Dios de los tres jóvenes? (Daniel 3:29)',
 o:['En un muladar','En un estercolero','En un campo baldío','En propiedad del rey'],a:1},
{cap:'d6',t:'mc',q:'Según la RV1995, ¿qué no hallaron en Daniel sus acusadores? (Daniel 6:4)',
 o:['Ningún vicio ni falta','Ningún error ni falta','Ninguna ocasión ni pecado','Ninguna mancha ni sombra'],a:1},
{cap:'d6',t:'mc',q:'Según la RV1995, ¿qué dijeron los enemigos que no hallarían contra Daniel? (Daniel 6:5)',
 o:['Ocasión alguna','Motivo alguno para acusarlo','Falta alguna de trabajo','Testigo alguno'],a:1},
{cap:'d6',t:'mc',q:'Según la RV1995, ¿de qué habitación estaban abiertas las ventanas cuando Daniel oraba? (Daniel 6:10)',
 o:['De su cámara','De su habitación','Del salón del trono','Del patio de su casa'],a:1},
{cap:'d6',t:'tf',q:'Según la RV1995, Daniel oraba con las ventanas de su habitación abiertas hacia Jerusalén. (Daniel 6:10)',
 a:true,e:'Verdadero. La RV1995 dice «habitación»; la RV1960 dice «cámara». La dirección es la misma: Jerusalén.'},
{cap:'d4',t:'mc',q:'Según la RV1995, ¿cómo le dijo Daniel al rey que tratara sus pecados? (Daniel 4:27)',
 o:['Que los confesara ante los sacerdotes','Que redimiera sus pecados con justicia y sus iniquidades haciendo misericordias con los oprimidos','Que ofreciera sacrificios en el templo','Que ayunara y se vistiera de luto'],a:1},
{cap:'d5',t:'mc',q:'Según la RV1995, ¿qué significa PERES? (Daniel 5:28)',
 o:['Tu reino ha sido dividido entre tus hijos','Tu reino ha sido roto y dado a los medos y a los persas','Tu reino ha sido pesado y hallado falto','Tu reino ha sido contado y terminado'],a:1},
{cap:'pr42',t:'mc',q:'¿Con qué capítulo de Daniel va el capítulo 42 de Profetas y Reyes, «La verdadera grandeza»?',
 o:['Daniel 3','Daniel 4','Daniel 5','Daniel 6'],a:1},
{cap:'pr43',t:'mc',q:'¿Con qué capítulo de Daniel va el capítulo 43 de Profetas y Reyes, «El vigía invisible»?',
 o:['Daniel 4','Daniel 5','Daniel 6','Daniel 2'],a:1},
{cap:'pr40',t:'tf',q:'El capítulo 40 de Profetas y Reyes se titula «La imagen de oro».',
 a:false,e:'Falso. El capítulo 40 se titula «El sueño de Nabucodonosor». La imagen de oro del capítulo 3 se trata en el capítulo 41, «El horno de fuego».'},
{cap:'pr41',t:'tf',q:'El capítulo 41 de Profetas y Reyes se titula «La imagen de oro y el horno de fuego».',
 a:false,e:'Falso. Se titula solamente «El horno de fuego». Ese título largo circula en varias guías, pero no es el del libro.'},
{cap:'d1',t:'fill',ins:'Daniel 1:4 (RV1995) — Completa el requisito de los jóvenes:',
 p:[{x:'«...muchachos en quienes no hubiera '},{b:'tacha',h:'¿qué no debía haber?'},{x:' alguna, de buen parecer, '},{b:'instruidos',h:'¿cómo, en toda sabiduría?'},{x:' en toda sabiduría, sabios en ciencia...»'}]},
{cap:'d4',t:'fill',ins:'Daniel 4:15 (RV1995) — Completa:',
 p:[{x:'«Mas la cepa de sus raíces dejaréis en la tierra, con atadura de '},{b:'hierro',h:'¿de qué metal?'},{x:' y de '},{b:'bronce',h:'¿y de qué otro?'},{x:' entre la hierba del campo...»'}]}
);

/* ─── Ampliación 22-ago (3): bloques que no tenían ninguna pregunta.
   Todas verificadas contra el texto RV1995 antes de escribirlas. ─── */
BANCO.push(
/* ── Daniel 2: la interpretación reino por reino (2:36-45) ── */
{cap:'d2',t:'mc',q:'Según Daniel 2:37, ¿qué le dijo Daniel a Nabucodonosor que era él?',
 o:['El más sabio de los reyes','Rey de reyes, a quien el Dios del cielo ha dado reino, poder, fuerza y majestad','El elegido de los dioses de Babilonia','Señor de toda la tierra para siempre'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:39, ¿cómo describió Daniel al reino que se levantaría después de Nabucodonosor?',
 o:['Más fuerte que el tuyo','Inferior al tuyo','Semejante al tuyo','Más rico que el tuyo'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:40, ¿con qué comparó Daniel la fuerza del cuarto reino?',
 o:['Con el bronce que resiste','Con el hierro que desmenuza y rompe todas las cosas','Con la piedra que no se mueve','Con el oro que no se corroe'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:41, ¿qué significan los pies y los dedos en parte de barro cocido y en parte de hierro?',
 o:['Un reino de artesanos','Un reino dividido','Un reino de dos reyes','Un reino sin ejército'],a:1},
{cap:'d2',t:'mc',q:'¿Qué hizo el rey Nabucodonosor después de oír la interpretación? (Daniel 2:46)',
 o:['Se enojó y calló a Daniel','Se postró sobre su rostro y se humilló ante Daniel','Mandó destruir la estatua de su sueño','Reunió otra vez a sus magos'],a:1},
{cap:'d2',t:'mc',q:'¿Qué confesó Nabucodonosor acerca del Dios de Daniel? (Daniel 2:47)',
 o:['Que era un dios más entre muchos','Que era Dios de dioses, Señor de los reyes y el que revela los misterios','Que era el dios de los hebreos solamente','Que era más fuerte que Marduc'],a:1},
{cap:'d2',t:'tf',q:'Según Daniel 2:21, Dios muda los tiempos y las edades, quita reyes y pone reyes.',
 a:true,e:'Verdadero. Daniel 2:21 lo dice así, y es la base de toda la profecía de los imperios.'},
{cap:'d2',t:'fill',ins:'Daniel 2:21 (RV1995) — Completa:',
 p:[{x:'«Él muda los '},{b:'tiempos',h:'¿qué muda?'},{x:' y las edades, quita reyes y pone '},{b:'reyes',h:'¿pone qué?'},{x:'.»'}]},
{cap:'d2',t:'fill',ins:'Daniel 2:22 (RV1995) — Completa:',
 p:[{x:'«Él revela lo '},{b:'profundo',h:'¿qué revela?'},{x:' y lo escondido, conoce lo que está en tinieblas y con él mora la '},{b:'luz',h:'¿qué mora con él?'},{x:'.»'}]},

/* ── Daniel 3: la acusación y el desafío del rey (3:6-20, 26-28) ── */
{cap:'d3',t:'mc',q:'Según Daniel 3:6, ¿qué le pasaría a quien no se postrara y adorara la estatua?',
 o:['Sería desterrado del reino','Sería echado dentro de un horno de fuego ardiente','Perdería su cargo','Sería entregado a los leones'],a:1},
{cap:'d3',t:'mc',q:'¿Quiénes acusaron maliciosamente a los judíos ante el rey? (Daniel 3:8)',
 o:['Los sátrapas persas','Algunos hombres caldeos','Los sacerdotes de Marduc','Los capitanes del ejército'],a:1},
{cap:'d3',t:'mc',q:'Según Daniel 3:15, ¿qué preguntó desafiante Nabucodonosor a los tres jóvenes?',
 o:['¿Quién os ha enseñado a desobedecer?','¿Y qué dios será el que os libre de mis manos?','¿No teméis al rey de Babilonia?','¿Dónde está vuestro Dios ahora?'],a:1},
{cap:'d3',t:'mc',q:'Según Daniel 3:16, ¿qué le respondieron los tres jóvenes al rey?',
 o:['Que necesitaban tiempo para pensarlo','Que no era necesario que le respondieran sobre ese asunto','Que obedecerían por respeto al rey','Que consultarían a Daniel primero'],a:1},
{cap:'d3',t:'mc',q:'¿A quiénes ordenó el rey que ataran a los tres jóvenes? (Daniel 3:20)',
 o:['A los sacerdotes del templo','A hombres muy vigorosos de su ejército','A los sátrapas de la provincia','A los guardias del palacio'],a:1},
{cap:'d3',t:'mc',q:'¿Cómo llamó Nabucodonosor a los tres jóvenes cuando los mandó salir del horno? (Daniel 3:26)',
 o:['Hijos de Judá','Siervos del Dios Altísimo','Amigos del rey','Varones de fe'],a:1},
{cap:'d3',t:'tf',q:'Según Daniel 3:28, los tres jóvenes entregaron sus cuerpos antes que servir y adorar a otro dios que su Dios.',
 a:true,e:'Verdadero. Daniel 3:28 lo dice así, y además que Dios envió su ángel y libró a sus siervos que confiaron en él.'},

/* ── Daniel 4: el árbol, el vigilante santo y la sentencia ── */
{cap:'d4',t:'mc',q:'Según Daniel 4:13, ¿quién descendía del cielo en la visión del rey?',
 o:['Un ángel con espada','Un vigilante y santo','El profeta Daniel','Una voz sin figura'],a:1},
{cap:'d4',t:'mc',q:'Según Daniel 4:14, ¿qué clamaba fuertemente el vigilante?',
 o:['«Arrepiéntete, oh rey»','«Derribad el árbol y cortad sus ramas»','«Guardad el árbol para siempre»','«Venga el juicio sobre Babilonia»'],a:1},
{cap:'d4',t:'mc',q:'Según Daniel 4:17, ¿para qué era la sentencia de los vigilantes?',
 o:['Para castigar a Babilonia','Para que los vivientes conozcan que el Altísimo gobierna el reino de los hombres','Para probar la fe de Daniel','Para cumplir el sueño de la estatua'],a:1},
{cap:'d4',t:'mc',q:'¿Cómo reaccionó Daniel al oír el sueño del árbol? (Daniel 4:19)',
 o:['Se alegró por el rey','Quedó atónito casi una hora y sus pensamientos lo turbaban','Se negó a interpretarlo','Pidió que llamaran a los magos'],a:1},
{cap:'d4',t:'tf',q:'Cuando Daniel oyó el sueño del árbol lo interpretó de inmediato, sin turbarse. (Daniel 4:19)',
 a:false,e:'Falso. Quedó atónito casi una hora y sus pensamientos lo turbaban, porque la sentencia era contra el rey.'},
{cap:'d4',t:'fill',ins:'Daniel 4:17 (RV1995) — Completa:',
 p:[{x:'«...para que conozcan los vivientes que el '},{b:'Altísimo',h:'¿quién gobierna?'},{x:' gobierna el reino de los '},{b:'hombres',h:'¿el reino de quiénes?'},{x:'.»'}]},

/* ── Daniel 5: el discurso de Daniel a Belsasar ── */
{cap:'d5',t:'mc',q:'¿Qué le respondió Daniel a Belsasar sobre los regalos que le ofrecía? (Daniel 5:17)',
 o:['Que los aceptaba con gratitud','Que sus dones fueran para él y diera sus recompensas a otros','Que los repartiera entre los pobres','Que los guardara hasta el otro día'],a:1},
{cap:'d5',t:'mc',q:'Según Daniel 5:20, ¿qué le pasó a Nabucodonosor cuando su corazón se ensoberbeció?',
 o:['Fue desterrado a Persia','Fue depuesto del trono de su reino y despojado de su gloria','Perdió a sus hijos','Fue entregado a los medos'],a:1},
{cap:'d5',t:'mc',q:'¿Cuál fue el reproche central de Daniel a Belsasar? (Daniel 5:22)',
 o:['Que no había leído las Escrituras','Que no había humillado su corazón sabiendo todo esto','Que no había consultado a los sabios','Que había perdido las batallas'],a:1},
{cap:'d5',t:'mc',q:'Según Daniel 5:23, ¿a qué clase de dioses dio alabanza Belsasar?',
 o:['A los dioses del cielo y de la tierra','A dioses de plata y oro, de bronce, de hierro, de madera y de piedra, que ni ven ni oyen ni saben','A los dioses de los medos y persas','A los dioses de sus padres solamente'],a:1},
{cap:'d5',t:'tf',q:'Según Daniel 5:23, Belsasar nunca honró al Dios en cuya mano está su vida.',
 a:true,e:'Verdadero. Daniel 5:23 termina así: «pero nunca honraste al Dios en cuya mano está tu vida y de quien son todos tus caminos».'},

/* ── Daniel 6: cómo armaron la trampa, y el foso ── */
{cap:'d6',t:'mc',q:'Según Daniel 6:7, ¿quiénes dijeron haber acordado el edicto contra la oración?',
 o:["Los tres gobernadores del reino y los ciento veinte sátrapas de las provincias","Todos los gobernadores del reino, magistrados, sátrapas, príncipes y capitanes","Los sacerdotes de Babilonia junto con los magos, astrólogos y adivinos del rey","La reina, los príncipes de Media y los capitanes del ejército de Persia"],a:1},
{cap:'d6',t:'mc',q:'Según Daniel 6:8, ¿por qué el edicto no podía ser revocado?',
 o:['Porque lo había jurado el rey','Conforme a la ley de Media y de Persia, que no puede ser abrogada','Porque estaba escrito en piedra','Porque lo aprobaron los sátrapas'],a:1},
{cap:'d6',t:'mc',q:'¿Qué le dijo el rey a Daniel al echarlo al foso? (Daniel 6:16)',
 o:["«Que el Dios de tus padres te juzgue por haber quebrantado mi edicto»","«El Dios tuyo, a quien tú continuamente sirves, él te libre»","«Nada puedo hacer por ti: la ley de Media y de Persia no se abroga»","«Mañana al amanecer vendré a ver si tu Dios te ha podido librar»"],a:1},
{cap:'d6',t:'mc',q:'¿Cómo llamó el rey Darío a Daniel al llegar al foso de mañana? (Daniel 6:20)',
 o:['«Daniel, mi amigo fiel»','«Daniel, siervo del Dios viviente»','«Daniel, profeta de Judá»','«Daniel, gobernador del reino»'],a:1},
{cap:'d6',t:'tf',q:'Darío llamó a Daniel con voz alegre al llegar al foso. (Daniel 6:20)',
 a:false,e:'Falso. RV1995 dice que lo llamó a gritos «con voz triste».'},
{cap:'d6',t:'fill',ins:'Daniel 6:20 (RV1995) — Completa lo que dijo el rey:',
 p:[{x:'«Daniel, siervo del Dios '},{b:'viviente',h:'¿qué Dios?'},{x:', el Dios tuyo, a quien tú '},{b:'continuamente',h:'¿cómo le sirves?'},{x:' sirves, ¿te ha podido librar de los leones?»'}]},

/* ── Daniel 1: los versículos que faltaban ── */
{cap:'d1',t:'mc',q:'¿Cuáles eran los nombres hebreos de los cuatro jóvenes? (Daniel 1:6)',
 o:['Daniel, Ananías, Misael y Azarías','Daniel, Sadrac, Mesac y Abed-nego','Daniel, Josué, Esdras y Nehemías','Daniel, Aspenaz, Melsar y Arioc'],a:0},
{cap:'d1',t:'mc',q:'¿Qué temía el jefe de los eunucos si Daniel no comía la comida del rey? (Daniel 1:10)',
 o:["Que el rey lo acusara de haber robado la comida y el vino de la mesa real","Que el rey le quitara la cabeza al verlos de peor aspecto que los otros muchachos","Que los otros muchachos se quejaran ante Aspenaz y pidieran el mismo trato","Que Daniel enfermara y no pudiera presentarse delante del rey a los tres años"],a:1},
{cap:'d1',t:'tf',q:'Al cumplirse el tiempo, el rey no halló entre todos los jóvenes ninguno como Daniel, Ananías, Misael y Azarías. (Daniel 1:19)',
 a:true,e:'Verdadero. Daniel 1:19 dice que el rey habló con ellos y no fue hallado entre todos ninguno como ellos, y por eso estuvieron delante del rey.'}
);

/* ─── Ampliación 22-ago (4): cerrar el alcance oficial versículo por
   versículo. Cada una verificada contra el texto RV1995 con
   tools/verificar.js antes de quedar. ─── */
BANCO.push(
/* ── Daniel 1: 13, 14, 18 ── */
{cap:'d1',t:'mc',q:'¿Qué le pidió Daniel a Melsar que hiciera al terminar la prueba? (Daniel 1:13)',
 o:["Que informara al rey del resultado antes de que se cumplieran los tres años","Que comparara sus rostros con los de los muchachos que comían de la comida del rey","Que extendiera la prueba a todos los jóvenes del palacio por otros diez días","Que les diera la porción del rey si su aspecto empeoraba en los diez días"],a:1},
{cap:'d1',t:'tf',q:'Melsar aceptó la propuesta de Daniel y probó con ellos durante diez días. (Daniel 1:14)',
 a:true,e:'Verdadero. RV1995: «Consintió, pues, con ellos en esto, y probó con ellos durante diez días».'},
{cap:'d1',t:'mc',q:'¿Quién llevó a los cuatro jóvenes delante de Nabucodonosor al cumplirse el plazo? (Daniel 1:18)',
 o:['Melsar','El jefe de los eunucos','El capitán de la guardia','Los magos del reino'],a:1},

/* ── Daniel 2: 2 al 15 ── */
{cap:'d2',t:'mc',q:'¿A quiénes mandó llamar el rey para que le declararan sus sueños? (Daniel 2:2)',
 o:['Solo a los caldeos','A los magos, astrólogos, encantadores y caldeos','A los sacerdotes del templo','A los sátrapas de las provincias'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:3, ¿qué le dijo el rey a los sabios sobre su sueño?',
 o:['Que ya lo había olvidado por completo','Que había tenido un sueño y su espíritu se había turbado por saberlo','Que el sueño anunciaba una guerra','Que soñó con una estatua de oro'],a:1},
{cap:'d2',t:'mc',q:'¿Con qué palabras le respondieron los caldeos al rey? (Daniel 2:4)',
 o:['«Perdónanos, oh rey»','«¡Rey, para siempre vive! Cuenta el sueño a tus siervos»','«Nadie puede saber eso»','«Danos siete días»'],a:1},
{cap:'d2',t:'mc',q:'¿Qué les ofreció el rey si le declaraban el sueño y su interpretación? (Daniel 2:6)',
 o:['La mitad de su reino','Dones, favores y gran honra','Tierras y esclavos','El perdón de sus deudas'],a:1},
{cap:'d2',t:'tf',q:'Los caldeos volvieron a pedirle al rey que él les contara el sueño primero. (Daniel 2:7)',
 a:true,e:'Verdadero. Insistieron: «Cuente el rey el sueño a sus siervos, y le daremos la interpretación».'},
{cap:'d2',t:'mc',q:'¿De qué acusó el rey a los sabios cuando insistieron? (Daniel 2:8)',
 o:['De burlarse de él','De poner dilaciones porque veían que el asunto se le había ido','De estar aliados con sus enemigos','De no haber estudiado'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:10, ¿qué le contestaron los caldeos al rey?',
 o:['Que necesitaban más tiempo','Que no hay hombre sobre la tierra que pueda declarar el asunto del rey','Que el sueño no tenía significado','Que buscarían a un profeta hebreo'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:11, ¿quiénes decían los caldeos que podrían declarar el asunto?',
 o:['Solo los reyes','Solo los dioses','Solo los ancianos','Solo los sacerdotes de Babilonia'],a:1},
{cap:'d2',t:'mc',q:'¿Qué mandó el rey cuando nadie pudo declararle el sueño? (Daniel 2:12)',
 o:['Encarcelar a los caldeos','Que mataran a todos los sabios de Babilonia','Desterrarlos del reino','Quitarles sus bienes'],a:1},
{cap:'d2',t:'tf',q:'Cuando se publicó el edicto de muerte contra los sabios, también buscaron a Daniel. (Daniel 2:13)',
 a:true,e:'Verdadero. RV1995: «buscaron también a Daniel», aunque él no había estado entre los consultados.'},
{cap:'d2',t:'mc',q:'¿Qué le preguntó Daniel a Arioc cuando lo buscó? (Daniel 2:15)',
 o:['Quién lo había acusado','Cuál era la causa de que el edicto se publicara tan apresuradamente','Dónde estaban sus compañeros','Si podía hablar con el rey'],a:1},

/* ── Daniel 3: 2 al 14, 23 y 24 ── */
{cap:'d3',t:'mc',q:'¿A quiénes mandó reunir el rey para la dedicación de la estatua? (Daniel 3:2)',
 o:["A los sátrapas, magistrados, sacerdotes, magos, astrólogos y todos los caldeos del reino","A los sátrapas, magistrados, capitanes, oidores, tesoreros, consejeros, jueces y todos los gobernadores","A los sátrapas, capitanes, tesoreros y consejeros, pero no a los jueces ni a los gobernadores","A los príncipes, capitanes y gobernadores de las provincias, y a todo el pueblo de Babilonia"],a:1},
{cap:'d3',t:'tf',q:'Todos los funcionarios convocados sí se reunieron para la dedicación de la estatua. (Daniel 3:3)',
 a:true,e:'Verdadero. RV1995: «Se reunieron, pues, los sátrapas, magistrados, capitanes...».'},
{cap:'d3',t:'mc',q:'¿A quiénes se dirigió el pregonero en alta voz? (Daniel 3:4)',
 o:['A los sátrapas del reino','A los pueblos, naciones y lenguas','A los soldados del ejército','A los sacerdotes de Marduc'],a:1},
{cap:'d3',t:'tf',q:'Al oír la música, todos los pueblos se postraron y adoraron la estatua de oro. (Daniel 3:7)',
 a:true,e:'Verdadero. Todos, menos Sadrac, Mesac y Abed-nego, que son acusados en el versículo siguiente.'},
{cap:'d3',t:'mc',q:'¿Cómo empezaron los caldeos su acusación ante el rey? (Daniel 3:9)',
 o:['«Oh rey, hay traidores»','«¡Rey, para siempre vive!»','«Perdona nuestra osadía»','«Escucha, oh gran Nabucodonosor»'],a:1},
{cap:'d3',t:'mc',q:'Según Daniel 3:12, ¿qué recordaron los acusadores sobre los tres jóvenes?',
 o:["Que el rey mismo les había permitido no adorar la estatua de oro de Dura","Que el rey mismo los había puesto sobre los negocios de la provincia de Babilonia","Que eran los mismos que habían interpretado el sueño de la gran imagen","Que llevaban nombres babilónicos y por eso debían adorar a los dioses del rey"],a:1},
{cap:'d3',t:'mc',q:'¿Con qué ánimo mandó el rey traer a los tres jóvenes? (Daniel 3:13)',
 o:['Con calma y curiosidad','Con ira y con enojo','Con tristeza','Con burla'],a:1},
{cap:'d3',t:'mc',q:'¿Qué les preguntó el rey al tenerlos delante? (Daniel 3:14)',
 o:["¿Es verdad que os postrasteis ante la estatua y luego negasteis haberlo hecho?","¿Es verdad que vosotros no honráis a mi dios ni adoráis la estatua de oro que he levantado?","¿Quién de vosotros dio la orden de no obedecer el edicto que yo mismo promulgué?","¿No sabéis que fui yo quien os puso sobre los negocios de la provincia de Babilonia?"],a:1},
{cap:'d3',t:'tf',q:'Los tres jóvenes cayeron atados dentro del horno de fuego ardiente. (Daniel 3:23)',
 a:true,e:'Verdadero. Entraron atados; después el rey los vio sueltos caminando en medio del fuego.'},
{cap:'d3',t:'mc',q:'¿Cómo reaccionó el rey al mirar dentro del horno? (Daniel 3:24)',
 o:['Se alegró','Se espantó y se levantó apresuradamente','Mandó apagar el fuego','Llamó a Daniel'],a:1}
);

/* ─── Ampliación 22-ago (5): últimos versículos del alcance oficial. ─── */
BANCO.push(
/* ── Daniel 2: 23 al 33, y 49 ── */
{cap:'d2',t:'mc',q:'Según Daniel 2:23, ¿por qué le dio Daniel gracias al Dios de sus padres?',
 o:['Porque lo libró de la muerte','Porque le había dado sabiduría y fuerza','Porque le devolvió a su familia','Porque castigó a los caldeos'],a:1},
{cap:'d2',t:'mc',q:'¿Qué le pidió Daniel a Arioc antes de entrar ante el rey? (Daniel 2:24)',
 o:['Que lo dejara ver a sus amigos','Que no mataran a los sabios de Babilonia','Que le diera más tiempo','Que lo protegiera del rey'],a:1},
{cap:'d2',t:'mc',q:'¿Cómo presentó Arioc a Daniel ante el rey? (Daniel 2:25)',
 o:['Como el más sabio de Babilonia','Como un hombre de los deportados de Judá','Como un profeta enviado por Dios','Como su propio consejero'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:27, ¿quiénes NO podían revelar el misterio que el rey demandaba?',
 o:['Solo los magos','Ni sabios ni astrólogos, ni magos ni adivinos','Solo los adivinos extranjeros','Los sacerdotes del templo'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:29, ¿dónde estaba el rey cuando le vinieron los pensamientos sobre el futuro?',
 o:['En el trono','En su cama','En el campo de Dura','En el templo'],a:1},
{cap:'d2',t:'tf',q:'Daniel dijo que el misterio le fue revelado porque él tenía más sabiduría que los demás. (Daniel 2:30)',
 a:false,e:'Falso. Dijo exactamente lo contrario: «no porque en mí haya más sabiduría que en los demás».'},
{cap:'d2',t:'mc',q:'Según Daniel 2:31, ¿cómo describió Daniel la imagen del sueño?',
 o:['Pequeña pero brillante','Muy grande y su gloria muy sublime','Hecha de piedra','Semejante a un hombre común'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:33, ¿de qué eran las piernas de la imagen?',
 o:['De bronce','De hierro','De plata','De barro cocido'],a:1},
{cap:'d2',t:'mc',q:'¿Qué obtuvo Daniel del rey para sus tres compañeros? (Daniel 2:49)',
 o:['Que volvieran a Judá','Que los pusiera sobre los negocios de la provincia de Babilonia','Que los eximieran del servicio','Que estudiaran con los magos'],a:1},
{cap:'d2',t:'fill',ins:'Daniel 2:23 (RV1995) — Completa:',
 p:[{x:'«A ti, Dios de mis padres, te doy '},{b:'gracias',h:'¿qué le da?'},{x:' y te alabo, porque me has dado '},{b:'sabiduría',h:'¿qué le dio?'},{x:' y fuerza.»'}]},

/* ── Daniel 3: 10 y 11 ── */
{cap:'d3',t:'mc',q:'Al acusar a los tres jóvenes, ¿qué le recordaron los caldeos al rey sobre su propia ley? (Daniel 3:10)',
 o:["Que su padre había dado esa misma ley y nadie se había atrevido a romperla","Que él mismo había dado la ley de postrarse al oír los instrumentos","Que la ley de Media y de Persia no permitía revocar un edicto ya firmado","Que él mismo había puesto a los tres hebreos sobre la provincia de Babilonia"],a:1},
{cap:'d3',t:'mc',q:'Según Daniel 3:11, ¿qué decía la ley que le pasaría al que no se postrara?',
 o:['Que perdería su cargo','Que sería echado dentro de un horno de fuego ardiente','Que sería desterrado','Que pagaría una multa'],a:1},

/* ── Daniel 6: 6 al 15, 21, 25 y 28 ── */
{cap:'d6',t:'mc',q:'¿Cómo saludaron los gobernadores y sátrapas al rey al presentarle el edicto? (Daniel 6:6)',
 o:['«Oh rey, escúchanos»','«¡Rey Darío, para siempre vive!»','«Señor de Media y Persia»','«Gran rey de Babilonia»'],a:1},
{cap:'d6',t:'tf',q:'El rey Darío firmó el edicto y la prohibición. (Daniel 6:9)',
 a:true,e:'Verdadero. RV1995: «Firmó, pues, el rey Darío el edicto y la prohibición».'},
{cap:'d6',t:'mc',q:'¿Cómo encontraron a Daniel los que lo espiaban? (Daniel 6:11)',
 o:['Escribiendo cartas','Orando y rogando en presencia de su Dios','Reuniendo a los judíos','Escondido en su casa'],a:1},
{cap:'d6',t:'mc',q:'Según Daniel 6:13, ¿de qué acusaron a Daniel delante del rey?',
 o:["De haber pedido al rey que firmara el edicto para después burlarse de él","De no respetar al rey ni acatar el edicto, y hacer su petición tres veces al día","De orar en secreto con las ventanas cerradas para que nadie lo pudiera ver","De aconsejar a los otros gobernadores que tampoco cumplieran el edicto real"],a:1},
{cap:'d6',t:'mc',q:'¿Qué le recordaron al rey cuando él quería salvar a Daniel? (Daniel 6:15)',
 o:["Que el pueblo de Media y de Persia se levantaría si perdonaba a un cautivo","Que es ley de Media y de Persia que ningún edicto que el rey confirme puede ser abrogado","Que Daniel era de los hijos de los cautivos de Judá y no le debía respeto","Que los leones ya estaban preparados y la piedra del foso estaba sellada"],a:1},
{cap:'d6',t:'mc',q:'¿Qué le respondió Daniel al rey desde el foso? (Daniel 6:21)',
 o:['«Sácame de aquí, oh rey»','«Oh rey, vive para siempre»','«¿Por qué me hiciste esto?»','«Los leones duermen»'],a:1},
{cap:'d6',t:'mc',q:'¿A quiénes escribió el rey Darío después de sacar a Daniel del foso? (Daniel 6:25)',
 o:["A los gobernadores y sátrapas de las ciento veinte provincias del reino","A todos los pueblos, naciones y lenguas que moraban en toda la tierra","A los sacerdotes de Babilonia y a los magos que servían en su palacio","A los cautivos de Judá que quedaban en las provincias de Media y Persia"],a:1},
{cap:'d6',t:'mc',q:'¿Durante los reinados de qué reyes prosperó Daniel? (Daniel 6:28)',
 o:['Nabucodonosor y Belsasar','Darío y Ciro el persa','Joacim y Darío','Belsasar y Ciro'],a:1},
{cap:'d6',t:'tf',q:'Daniel prosperó durante los reinados de Darío y de Ciro, el persa. (Daniel 6:28)',
 a:true,e:'Verdadero. Es el cierre del capítulo 6 y conecta con Daniel 1:21, que menciona el año primero de Ciro.'}
);

/* ─── Cierre del alcance: los últimos versículos sin pregunta. ─── */
BANCO.push(
{cap:'d2',t:'mc',q:'Según Daniel 2:9, ¿qué exigió el rey para comprobar que los sabios podían interpretar?',
 o:['Que jurasen por sus dioses','Que le contaran el sueño, para saber que podían darle su interpretación','Que trajeran testigos','Que escribieran la respuesta'],a:1},
{cap:'d2',t:'mc',q:'¿Qué le preguntó el rey a Daniel al tenerlo delante? (Daniel 2:26)',
 o:['¿De qué pueblo eres?','¿Podrás tú hacerme conocer el sueño que vi, y su interpretación?','¿Cuánto quieres por decírmelo?','¿Quién te envió?'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:38, ¿qué le había entregado Dios en las manos a Nabucodonosor?',
 o:['Solo la ciudad de Jerusalén','Los hijos de hombres, las bestias del campo y las aves del cielo, dondequiera que habitan','El oro de todas las naciones','La sabiduría de los caldeos'],a:1},
{cap:'d6',t:'mc',q:'¿Qué le preguntaron al rey antes de acusar a Daniel? (Daniel 6:12)',
 o:['Si conocía a Daniel','Si no había confirmado el edicto de los treinta días','Si quería cambiar la ley','Si Daniel era su amigo'],a:1}
);

BANCO.push(
{cap:'d2',t:'mc',q:'¿Con qué frase cerró Daniel el relato del sueño antes de interpretarlo? (Daniel 2:36)',
 o:['«Así lo dice el Señor»','«Éste es el sueño. También la interpretación de él diremos en presencia del rey»','«Nadie más pudo verlo»','«Guárdalo en tu corazón, oh rey»'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:42, ¿cómo sería el reino de los dedos de hierro y barro cocido?',
 o:['Totalmente fuerte','En parte fuerte y en parte frágil','Totalmente frágil','El más grande de todos'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:43, ¿por qué medio se mezclarían y sin embargo no se unirían?',
 o:['Por medio de guerras','Por medio de alianzas humanas','Por medio del comercio','Por medio de la religión'],a:1},
{cap:'d2',t:'mc',q:'Según Daniel 2:45, ¿qué desmenuzó la piedra que se desprendió del monte?',
 o:['Solo los pies de barro','El hierro, el bronce, el barro, la plata y el oro','La cabeza de oro únicamente','Todo el monte'],a:1},
{cap:'d2',t:'fill',ins:'Daniel 2:43 (RV1995) — Completa:',
 p:[{x:'«Así como viste el hierro mezclado con barro, así se mezclarán por medio de '},{b:'alianzas',h:'¿por medio de qué?'},{x:' humanas; pero no se unirán el uno con el otro, como el hierro no se mezcla con el '},{b:'barro',h:'¿con qué no se mezcla?'},{x:'.»'}]}
);

/* ─── Profetas y Reyes 39, 41 y 44: equilibrar el peso, porque son 3 de las
   7 unidades del alcance oficial. Salen del contenido ya auditado en
   contenido.js. Camilo debe cotejarlas con su edición de IADPA. ─── */
BANCO.push(
/* ── P&R 39 ── */
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué clase de carnes incluía la comida del rey?',
 o:['Solo carnes de res','Carnes que la ley de Dios declaraba inmundas','Únicamente aves','Carnes preparadas por sacerdotes hebreos'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿cómo se interpretaba participar de la comida del rey?',
 o:['Como un simple acto de cortesía','Como homenaje a los dioses de Babilonia','Como una obligación militar','Como parte del entrenamiento físico'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué actitud tuvo Daniel al pedir el cambio de alimentación?',
 o:['Se negó sin explicar nada','Fue firme y cortés a la vez, y propuso una prueba razonable','Amenazó con dejar el palacio','Pidió que otro hablara por él'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué preparó a Daniel para las pruebas mayores?',
 o:['Su educación en Babilonia','La fidelidad en las cosas pequeñas','El favor del rey','Su origen del linaje real'],a:1},
{cap:'pr39',t:'tf',q:'Según P&R cap. 39, Daniel tomó su decisión sobre la comida del rey en el momento en que se la sirvieron.',
 a:false,e:'Falso. Su decisión fue tomada de antemano, no improvisada bajo presión. Esa es la enseñanza central del capítulo.'},
{cap:'pr39',t:'tf',q:'Según P&R cap. 39, el desarrollo intelectual de los cuatro jóvenes fue resultado solo del estudio.',
 a:false,e:'Falso. Fue resultado de la obediencia, no solo del estudio: Dios recompensó su fidelidad con salud, vigor y sabiduría superiores.'},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué efecto tiene la alimentación sencilla sobre la mente?',
 o:['Ninguno comprobable','Mantiene la mente despejada para discernir la voluntad de Dios','La hace más lenta pero más tranquila','Solo afecta el cuerpo'],a:1},

/* ── P&R 41 ── */
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿de qué NO los libró Dios a los tres jóvenes?',
 o:['De la muerte','De la prueba: estuvo con ellos dentro de ella','Del fuego','Del rey'],a:1},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿qué significa que no negociaron con Dios?',
 o:['Que no oraron antes','Que no condicionaron su lealtad al milagro','Que no le pidieron nada al rey','Que no hablaron entre ellos'],a:1},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿ante quién fue testimonio el milagro del horno?',
 o:['Ante los sacerdotes de Babilonia','Ante el rey más poderoso de la tierra','Ante el pueblo de Judá','Ante los otros cautivos'],a:1},
{cap:'pr41',t:'tf',q:'Según P&R cap. 41, ningún poder humano puede vencer a quienes permanecen fieles.',
 a:true,e:'Verdadero. Es una de las conclusiones del capítulo, junto con que la fidelidad puede costar la vida y Dios libera a los suyos.'},
{cap:'pr41',t:'tf',q:'Según P&R cap. 41, la experiencia del horno solo aplica a casos de idolatría con estatuas.',
 a:false,e:'Falso. Es un modelo de fidelidad ante cualquier presión para desobedecer a Dios, en cualquier época y circunstancia.'},

/* ── P&R 44 ── */
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿qué buscaron los enemigos de Daniel al investigarlo?',
 o:['Errores de traducción en sus escritos','Corrupción, y no hallaron nada','Testigos falsos','Deudas impagadas'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿cuándo se construyó el carácter de Daniel?',
 o:['En la crisis del foso','Día a día, antes de la crisis','Cuando llegó a Babilonia','Al final de su vida'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿qué hizo Daniel cuando llegó el decreto?',
 o:['Oró más fuerte para desafiar al rey','No cambió nada: siguió como solía hacerlo antes','Oró en secreto para no ser visto','Dejó de orar por unos días'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿hasta dónde llegó el alcance del testimonio de Daniel?',
 o:['Solo al palacio del rey','A todos los pueblos, naciones y lenguas del imperio','Solo a los cautivos de Judá','A los sátrapas de su provincia'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿en qué convirtió la liberación de Daniel al rey Darío?',
 o:['En un rey más severo','En proclamador del Dios verdadero','En enemigo de los judíos','En un rey débil'],a:1},
{cap:'pr44',t:'tf',q:'Según P&R cap. 44, Daniel fue fiel solo en lo religioso, no en su trabajo de gobierno.',
 a:false,e:'Falso. Fue fiel en su trabajo como funcionario del gobierno, no solo en lo religioso: su vida pública y privada eran igual de intachables.'},
{cap:'pr44',t:'tf',q:'Según P&R cap. 44, Daniel tenía más de ochenta años cuando fue echado al foso.',
 a:true,e:'Verdadero. Lo que decidió de joven en Daniel 1 fue lo que lo sostuvo de anciano en Daniel 6.'}
);


/* ─── Ampliación 8-sep: el reglamento del campamento quedó en Daniel 1, 3 y 6,
   así que estos tres suben a unas 60 preguntas cada uno. Todo verificado contra
   el texto RV1995 (files/rv1995-daniel-N.txt, de la edición RVR1995). Fuera las
   de diferencias entre versiones; adentro las de conteo de versículos y más de
   completar, que es la sección más difícil del examen real. ─── */
BANCO.push(
{cap:'d1',t:'mc',nv:1,q:'¿Cuántos versículos tiene el capítulo 1 de Daniel?',
 o:['18','21','24','28'],a:1},
{cap:'d1',t:'mc',nv:1,q:'¿Cuántos capítulos tiene el libro de Daniel?',
 o:['6','10','12','14'],a:2},
{cap:'d1',t:'mc',nv:1,q:'¿De qué linaje debían ser los muchachos que Aspenaz debía traer? (Daniel 1:3)',
 o:['Del linaje de los sacerdotes','Del linaje real de los príncipes','De cualquier familia de Israel','De los hijos de los eunucos'],a:1},
{cap:'d1',t:'mc',nv:1,q:'¿A qué tierra fueron llevados los utensilios de la casa de Dios? (Daniel 1:2)',
 o:['A tierra de Sinar','A tierra de Egipto','A tierra de Media','A tierra de Persia'],a:0},
{cap:'d1',t:'mc',nv:1,q:'Según Daniel 1:2, ¿quién entregó a Joacim en manos de Nabucodonosor?',
 o:['El ejército de Babilonia','El Señor','Los príncipes de Judá','Aspenaz'],a:1},
{cap:'d1',t:'mc',nv:1,q:'¿Qué porción diaria les señaló el rey a los jóvenes? (Daniel 1:5)',
 o:['Pan y agua del palacio','De la comida del rey y del vino que él bebía','Legumbres y agua','Carne de los sacrificios'],a:1},
{cap:'d1',t:'mc',nv:1,q:'¿Cuántos jóvenes de los hijos de Judá se nombran en Daniel 1:6?',
 o:['Tres','Cuatro','Seis','Diez'],a:1},
{cap:'d1',t:'mc',nv:1,q:'¿Quién les puso los nombres babilónicos a los cuatro jóvenes? (Daniel 1:7)',
 o:['El rey Nabucodonosor','El jefe de los eunucos','Melsar','Los magos de Babilonia'],a:1},
{cap:'d1',t:'mc',nv:1,q:'¿Para qué debían ser idóneos los muchachos escogidos? (Daniel 1:4)',
 o:['Para el ejército del rey','Para estar en el palacio del rey','Para el servicio del templo','Para gobernar provincias'],a:1},
{cap:'d1',t:'mc',nv:2,q:'¿Qué le pidió Daniel al jefe de los eunucos? (Daniel 1:8)',
 o:['Que lo dejara volver a Judá','Que no se le obligara a contaminarse','Que le diera un maestro hebreo','Que lo pusiera sobre los otros jóvenes'],a:1},
{cap:'d1',t:'mc',nv:2,q:'¿Qué temía el jefe de los eunucos que el rey viera en los rostros de los jóvenes? (Daniel 1:10)',
 o:['Que estuvieran más pálidos que los otros muchachos','Que estuvieran más gordos','Que estuvieran tristes','Que estuvieran enfermos de fiebre'],a:0},
{cap:'d1',t:'mc',nv:2,q:'En el libro de Daniel, ¿quién es Beltsasar?',
 o:['El rey del banquete del capítulo 5','El nombre babilónico de Daniel','El jefe de los eunucos','Un rey de Media'],a:1},
{cap:'d1',t:'tf',q:'Beltsasar es el nombre babilónico de Daniel, y Belsasar es un rey distinto. (Daniel 1:7)',
 a:true,e:'Verdadero. Se parecen a propósito: Beltsasar es Daniel (1:7); Belsasar es el rey del banquete del capítulo 5.'},
{cap:'d1',t:'tf',q:'Los utensilios de la casa de Dios fueron puestos en la casa del tesoro del dios de Nabucodonosor. (Daniel 1:2)',
 a:true,e:'Verdadero. Daniel 1:2 dice que los colocó «en la casa del tesoro de su dios».'},
{cap:'d1',t:'tf',q:'La prueba que propuso Daniel duró tres años. (Daniel 1:12)',
 a:false,e:'Falso. La prueba fue de DIEZ días (1:12). Los TRES años eran el tiempo de educación (1:5). El examen cruza esas dos cifras.'},
{cap:'d1',t:'tf',q:'Dios les dio conocimiento e inteligencia a los cuatro, y a Daniel además entendimiento en toda visión y sueños. (Daniel 1:17)',
 a:true,e:'Verdadero. El don de visiones y sueños se menciona solo para Daniel.'},
{cap:'d1',t:'fill',ins:'Daniel 1:2 (RV1995) — Completa:',
 p:[{x:'«El Señor entregó en sus manos a '},{b:'Joacim',h:'¿a quién?'},
    {x:', rey de Judá, y parte de los '},{b:'utensilios',h:'¿qué cosas?'},
    {x:' de la casa de Dios...»'}]},
{cap:'d1',t:'fill',ins:'Daniel 1:5 (RV1995) — Completa:',
 p:[{x:'«Y les señaló el rey una porción diaria de la '},{b:'comida',h:'¿de qué?'},
    {x:' del rey y del '},{b:'vino',h:'¿y de qué más?'},
    {x:' que él bebía; y que los educara durante '},{b:'tres',h:'¿cuántos?'},{x:' años...»'}]},
{cap:'d1',t:'fill',ins:'Daniel 1:7 (RV1995) — Completa los cuatro nombres:',
 p:[{x:'«A estos el jefe de los eunucos puso nombres: a Daniel, '},{b:'Beltsasar',h:'¿cómo?'},
    {x:'; a Ananías, '},{b:'Sadrac',h:'¿cómo?'},{x:'; a Misael, '},{b:'Mesac',h:'¿cómo?'},
    {x:'; y a Azarías, '},{b:'Abed-nego',h:'¿cómo?'},{x:'.»'}]},
{cap:'d1',t:'fill',ins:'Daniel 1:9 (RV1995) — Completa:',
 p:[{x:'«Puso Dios a Daniel en '},{b:'gracia',h:'¿en qué?'},{x:' y en buena '},
    {b:'voluntad',h:'¿y en qué más?'},{x:' con el jefe de los eunucos.»'}]},
{cap:'d1',t:'fill',ins:'Daniel 1:12 (RV1995) — Completa lo que pidió Daniel:',
 p:[{x:'«Te ruego que hagas la prueba con tus siervos durante '},{b:'diez',h:'¿cuántos?'},
    {x:' días: que nos den '},{b:'legumbres',h:'¿qué comida?'},{x:' para comer y '},
    {b:'agua',h:'¿qué bebida?'},{x:' para beber.»'}]},
{cap:'d1',t:'fill',ins:'Daniel 1:19 (RV1995) — Completa los cuatro nombres hebreos:',
 p:[{x:'«...no se hallaron entre todos ellos otros como '},{b:'Daniel',h:'¿quién?'},
    {x:', '},{b:'Ananías',h:'¿quién?'},{x:', '},{b:'Misael',h:'¿quién?'},{x:' y '},
    {b:'Azarías',h:'¿quién?'},{x:'...»'}]},
{cap:'d1',t:'fill',ins:'Daniel 1:21 (RV1995) — Completa:',
 p:[{x:'«Así continuó Daniel hasta el año '},{b:'primero',h:'¿cuál?'},{x:' del rey '},
    {b:'Ciro',h:'¿quién?'},{x:'.»'}]}
);


/* ─── Ampliación 8-sep: Daniel 3, uno de los tres del reglamento nuevo. ─── */
BANCO.push(
{cap:'d3',t:'mc',nv:1,q:'¿Cuántos versículos tiene el capítulo 3 de Daniel?',
 o:['24','27','30','33'],a:2},
{cap:'d3',t:'mc',nv:1,q:'¿De qué material era la estatua que hizo Nabucodonosor? (Daniel 3:1)',
 o:['De bronce','De oro','De plata','De hierro y barro'],a:1},
{cap:'d3',t:'mc',nv:1,q:'¿Quién hizo levantar la estatua de oro? (Daniel 3:1)',
 o:['El rey Nabucodonosor','Los sátrapas de Babilonia','Los caldeos','El rey Darío'],a:0},
{cap:'d3',t:'mc',nv:1,q:'¿Cuántos hombres cayeron atados dentro del horno de fuego ardiente? (Daniel 3:23)',
 o:['Dos','Tres','Cuatro','Siete'],a:1},
{cap:'d3',t:'mc',nv:2,q:'¿Sobre qué había puesto el rey a Sadrac, Mesac y Abed-nego? (Daniel 3:12)',
 o:['Sobre el ejército','Sobre los negocios de la provincia de Babilonia','Sobre los magos y astrólogos','Sobre el tesoro del rey'],a:1},
{cap:'d3',t:'mc',nv:2,q:'¿De qué dos cosas dijeron los tres jóvenes que su Dios podía librarlos? (Daniel 3:17)',
 o:['Del horno de fuego ardiente y de las manos del rey','Del horno y de los leones','De la muerte y del destierro','Del rey y de los caldeos'],a:0},
{cap:'d3',t:'mc',nv:2,q:'Según Daniel 3:28, ¿qué dijo Nabucodonosor que Dios había enviado?',
 o:['Un viento del norte','Su ángel','Una nube','Un profeta'],a:1},
{cap:'d3',t:'tf',q:'En Daniel 3 los tres jóvenes aparecen con sus nombres babilónicos: Sadrac, Mesac y Abed-nego.',
 a:true,e:'Verdadero. Sus nombres hebreos eran Ananías, Misael y Azarías (1:6-7).'},
{cap:'d3',t:'tf',q:'Daniel también fue echado al horno de fuego con sus tres compañeros.',
 a:false,e:'Falso. Daniel no aparece en el capítulo 3. Los echados al horno fueron Sadrac, Mesac y Abed-nego.'},
{cap:'d3',t:'tf',q:'La estatua de oro medía sesenta codos de altura y seis codos de anchura. (Daniel 3:1)',
 a:true,e:'Verdadero. Sesenta de alto por seis de ancho, levantada en el campo de Dura.'},
{cap:'d3',t:'fill',ins:'Daniel 3:1 (RV1995) — Completa:',
 p:[{x:'«El rey Nabucodonosor hizo una estatua de '},{b:'oro',h:'¿de qué material?'},
    {x:', cuya altura era de '},{b:'sesenta',h:'¿cuántos codos?'},{x:' codos y la anchura de '},
    {b:'seis',h:'¿cuántos codos?'},{x:' codos; la levantó en el campo de '},
    {b:'Dura',h:'¿dónde?'},{x:', en la provincia de Babilonia.»'}]},
{cap:'d3',t:'fill',ins:'Daniel 3:6 (RV1995) — Completa la amenaza del pregonero:',
 p:[{x:'«y cualquiera que no se postre y adore, inmediatamente será echado dentro de un '},
    {b:'horno',h:'¿dónde?'},{x:' de fuego '},{b:'ardiente',h:'¿cómo?'},{x:'.»'}]},
{cap:'d3',t:'fill',ins:'Daniel 3:19 (RV1995) — Completa:',
 p:[{x:'«...y ordenó que el horno se calentara '},{b:'siete',h:'¿cuántas veces?'},
    {x:' veces más de lo '},{b:'acostumbrado',h:'¿más de lo qué?'},{x:'.»'}]},
{cap:'d3',t:'fill',ins:'Daniel 3:26 (RV1995) — Completa lo que dijo el rey:',
 p:[{x:'«Sadrac, Mesac y Abed-nego, siervos del Dios '},{b:'Altísimo',h:'¿del Dios qué?'},
    {x:', salid y '},{b:'venid',h:'¿y qué?'},{x:'.»'}]},
{cap:'d3',t:'fill',ins:'Daniel 3:28 (RV1995) — Completa:',
 p:[{x:'«Bendito sea el Dios de Sadrac, Mesac y Abed-nego, que envió su '},
    {b:'ángel',h:'¿a quién?'},{x:' y libró a sus '},{b:'siervos',h:'¿a quiénes?'},
    {x:' que confiaron en él...»'}]},
{cap:'d3',t:'fill',ins:'Daniel 3:30 (RV1995) — Completa:',
 p:[{x:'«Entonces el rey '},{b:'engrandeció',h:'¿qué hizo?'},
    {x:' a Sadrac, Mesac y Abed-nego en la provincia de '},{b:'Babilonia',h:'¿dónde?'},{x:'.»'}]}
);


/* ─── Ampliación 8-sep: Daniel 6, el tercero del reglamento nuevo. ─── */
BANCO.push(
{cap:'d6',t:'mc',nv:1,q:'¿Cuántos versículos tiene el capítulo 6 de Daniel?',
 o:['24','26','28','31'],a:2},
{cap:'d6',t:'mc',nv:1,q:'¿Qué pusieron sobre la puerta del foso de los leones? (Daniel 6:17)',
 o:['Una reja de hierro','Una piedra','Un sello de cera','Una puerta de bronce'],a:1},
{cap:'d6',t:'mc',nv:2,q:'¿Para qué puso Darío tres gobernadores sobre los sátrapas? (Daniel 6:2)',
 o:['Para cobrar más tributo','Para que el rey no fuera perjudicado','Para vigilar a Daniel','Para dirigir el ejército'],a:1},
{cap:'d6',t:'mc',nv:2,q:'¿Qué les pasó a los acusadores de Daniel antes de llegar al fondo del foso? (Daniel 6:24)',
 o:["Los leones se apoderaron de ellos y quebraron todos sus huesos","Los leones no los tocaron y el rey los mandó sacar del foso","El rey se arrepintió y los perdonó antes de que llegaran al fondo","Escaparon del foso y huyeron a las provincias de Media y Persia"],a:0},
{cap:'d6',t:'tf',q:'El rey pensó en poner a Daniel sobre todo el reino. (Daniel 6:3)',
 a:true,e:'Verdadero. Por eso lo buscaron sus enemigos: Daniel era superior a los sátrapas y gobernadores.'},
{cap:'d6',t:'tf',q:'Darío selló la piedra del foso con su anillo y con el anillo de sus príncipes. (Daniel 6:17)',
 a:true,e:'Verdadero, «para que el acuerdo acerca de Daniel no se cambiara».'},
{cap:'d6',t:'fill',ins:'Daniel 6:1 (RV1995) — Completa:',
 p:[{x:'«Pareció bien a '},{b:'Darío',h:'¿a qué rey?'},{x:' constituir sobre el reino '},
    {b:'ciento veinte',h:'¿cuántos?'},{x:' sátrapas que gobernaran en todo el reino.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:3 (RV1995) — Completa:',
 p:[{x:'«Pero Daniel mismo era '},{b:'superior',h:'¿cómo era?'},
    {x:' a estos sátrapas y gobernadores, porque había en él un '},
    {b:'espíritu',h:'¿un qué?'},{x:' superior...»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:7 (RV1995) — Completa el edicto:',
 p:[{x:'«...ordenando que cualquiera que en el espacio de '},{b:'treinta',h:'¿cuántos días?'},
    {x:' días demande petición de cualquier dios u hombre fuera de ti, rey, sea echado al foso de los '},
    {b:'leones',h:'¿de qué?'},{x:'.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:16 (RV1995) — Completa lo que el rey dijo a Daniel:',
 p:[{x:'«El Dios tuyo, a quien tú continuamente '},{b:'sirves',h:'¿qué haces?'},{x:', él te '},
    {b:'libre',h:'¿qué haga?'},{x:'.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:18 (RV1995) — Completa:',
 p:[{x:'«Luego el rey se fue a su palacio, y se acostó en '},{b:'ayunas',h:'¿cómo?'},
    {x:'; no trajeron ante él instrumentos '},{b:'musicales',h:'¿qué cosa?'},
    {x:', y se le fue el '},{b:'sueño',h:'¿qué se le fue?'},{x:'.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:24 (RV1995) — Completa:',
 p:[{x:'«...cuando los leones se apoderaron de ellos y '},{b:'quebraron',h:'¿qué hicieron?'},
    {x:' todos sus '},{b:'huesos',h:'¿qué cosa?'},{x:'.»'}]},
{cap:'d6',t:'fill',ins:'Daniel 6:28 (RV1995) — Completa:',
 p:[{x:'«Daniel prosperó durante los reinados de '},{b:'Darío',h:'¿qué rey?'},{x:' y de '},
    {b:'Ciro',h:'¿qué rey?'},{x:', el persa.»'}]}
);


/* ─── Ampliación 8-sep: Profetas y Reyes 39, 41 y 44, los tres que entran al
   reglamento del campamento. Verificado contra el PDF oficial de EGW Writings
   (files/profetas-y-reyes.pdf, edición 1957). OJO: el libro cita la Biblia en
   una Valera anterior a la de 1995, así que estas citas van rotuladas como de
   P&R, nunca como RV1995. Aquí están también las primeras preguntas de
   completar del libro: antes no había ninguna. ─── */
BANCO.push(
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿a quién ordenó Nabucodonosor traer a los muchachos del linaje real?',
 o:['A Melsar, el sirviente','A Aspenaz, príncipe de sus eunucos','A los magos de Babilonia','A los capitanes del ejército'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿por qué les cambiaron los nombres a los cuatro jóvenes?',
 o:['Porque sus nombres hebreos eran difíciles','Por otros que conmemoraban divinidades caldeas','Para que nadie supiera que eran cautivos','Porque el rey no sabía hebreo'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué esperaba lograr el rey gradualmente con los nombres nuevos y las costumbres paganas?',
 o:["Que aprendieran las letras y la lengua de los caldeos más rápido","Inducirlos a renunciar a su religión y participar en el culto babilónico","Que olvidaran a sus padres y no quisieran volver a la tierra de Judá","Prepararlos para servir en el ejército de Babilonia como oficiales"],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué historia sobre la intemperancia conocían los jóvenes hebreos?',
 o:['La de Nadab y Abihú','La de Sansón','La de Elí y sus hijos','La de Noé'],a:0},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿a quién apeló Daniel después de que el príncipe de los eunucos vaciló?',
 o:['Al rey directamente','A Melsar','A los otros jóvenes','A los sabios del reino'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué temía Melsar al conceder la prueba?',
 o:['Que los jóvenes se enfermaran','Que esa concesión pudiera desagradar al rey','Que los otros muchachos se quejaran','Que Daniel lo denunciara'],a:1},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿quién les había inculcado a los jóvenes hábitos de estricta templanza?',
 o:['Sus padres','Aspenaz','Los sacerdotes de Babilonia','Melsar'],a:0},
{cap:'pr39',t:'mc',q:'Según P&R cap. 39, ¿qué promesa se cumplió para los cuatro jóvenes?',
 o:['«Yo honraré a los que me honran»','«No temas, yo estoy contigo»','«Pedid y se os dará»','«El justo por la fe vivirá»'],a:0},
{cap:'pr39',t:'tf',q:'Según P&R cap. 39, los jóvenes hebreos decidieron singularizarse para llamar la atención.',
 a:false,e:'Falso. «No decidieron singularizarse, aunque preferirían eso antes que deshonrar a Dios.»'},
{cap:'pr39',t:'tf',q:'Según P&R cap. 39, fue la fidelidad en las cosas pequeñas lo que dio carácter a toda su vida.',
 a:true,e:'Verdadero. «Honraron a Dios en los deberes más insignificantes, tanto como en las mayores responsabilidades.»'},
{cap:'pr39',t:'fill',ins:'Profetas y Reyes, cap. 39 — Completa la frase del libro:',
 p:[{x:'«Fué la '},{b:'fidelidad',h:'¿qué cosa?'},
    {x:' en las cosas pequeñas lo que dió '},{b:'carácter',h:'¿qué le dio?'},
    {x:' a toda su vida.»'}]},
{cap:'pr39',t:'fill',ins:'Profetas y Reyes, cap. 39 — Completa la frase sobre el carácter:',
 p:[{x:'«Un carácter noble no es el resultado de la '},{b:'casualidad',h:'¿de qué?'},
    {x:'... Es resultado de la '},{b:'disciplina',h:'¿de qué?'},{x:' propia...»'}]},

{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿en qué se diferenció la imagen de Dura de la que el rey vio en su sueño?',
 o:["Era de oro solo en la cabeza, igual que la imagen del sueño de Daniel 2","Era toda de oro, sin el descenso de valores de la cabeza a los pies","Era de hierro y barro cocido, para representar el reino que vendría después","Era del mismo tamaño del sueño, pero levantada en Jerusalén y no en Dura"],a:1},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿quiénes le propusieron al rey hacer la imagen?',
 o:['Los sabios de su reino','Los caldeos acusadores','Daniel','Los sacerdotes de Egipto'],a:0},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿qué quería simbolizar el rey al hacerla toda de oro?',
 o:["Su propia riqueza y el poder de los sabios de su reino","A Babilonia como reino eterno, indestructible y todopoderoso","Al dios de Babilonia, más poderoso que el Dios de los hebreos","La unidad de los pueblos, naciones y lenguas de su imperio"],a:1},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿cómo sabía el rey qué aspecto tendría el Hijo de Dios?',
 o:["Porque en el sueño de la gran imagen había visto al Hijo de Dios en el monte","Porque los cautivos hebreos le habían hablado de Cristo, el Redentor que iba a venir","Porque los sabios de Babilonia guardaban escritos sobre el Dios de los hebreos","Porque Daniel le había mostrado el rostro del Hijo de Dios en una visión"],a:1},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿qué fue lo único que se quemó de los tres jóvenes?',
 o:['Sus turbantes','Solo sus ligaduras','Sus mantos','El cabello de sus cabezas'],a:1},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿qué promesa recordaron los tres jóvenes en la hora de su prueba?',
 o:['Isaías 43:2, sobre pasar por el fuego sin quemarse','El Salmo 23','La promesa de la tierra prometida','Génesis 12:2'],a:0},
{cap:'pr41',t:'mc',q:'Según P&R cap. 41, ¿contra quiénes se despertará en forma especial la ira del hombre en el tiempo final?',
 o:['Contra los ricos','Contra los que santifican el sábado del cuarto mandamiento','Contra los gobernantes','Contra los que estudian profecía'],a:1},
{cap:'pr41',t:'tf',q:'Según P&R cap. 41, Nabucodonosor se excedió de su derecho al obligar a sus súbditos a confesar la misma fe que él.',
 a:true,e:'Verdadero. Hacer una confesión pública era correcto; obligar a otros a hacerla no: no tenía más derecho a eso que a mandar quemar a quien no adorara la imagen.'},
{cap:'pr41',t:'tf',q:'Según P&R cap. 41, Dios obliga a los hombres a obedecerle.',
 a:false,e:'Falso. «Nunca compele Dios a los hombres a obedecer. Deja a todos libres para elegir a quien quieren servir.»'},
{cap:'pr41',t:'tf',q:'Según P&R cap. 41, cuando los tres fueron arrojados al horno el Salvador se les reveló en persona y anduvieron juntos en medio del fuego.',
 a:true,e:'Verdadero. Por eso el rey vio cuatro y no tres.'},
{cap:'pr41',t:'fill',ins:'Profetas y Reyes, cap. 41 — Completa la frase del libro:',
 p:[{x:'«Nunca compele Dios a los hombres a '},{b:'obedecer',h:'¿a qué?'},
    {x:'. Deja a todos libres para '},{b:'elegir',h:'¿para qué?'},{x:' a quien quieren servir.»'}]},
{cap:'pr41',t:'fill',ins:'Profetas y Reyes, cap. 41 — Completa la promesa que recordaron (Isaías 43:2):',
 p:[{x:'«Cuando pasares por el '},{b:'fuego',h:'¿por qué?'},
    {x:', no te quemarás, ni la '},{b:'llama',h:'¿qué cosa?'},{x:' arderá en ti.»'}]},

{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿qué despertaron en los principales del reino los honores otorgados a Daniel?',
 o:['Su admiración','Los celos','Su respeto','Su miedo a los leones'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿a qué apelaron los príncipes para que Darío firmara el decreto?',
 o:['A su vanidad','A su temor de Dios','A su amistad con Daniel','A la ley de Media y Persia'],a:0},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿quién había desempeñado un papel importante en la conspiración contra Daniel?',
 o:['El rey Darío','Satanás','Los magos de Babilonia','Ciro el persa'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿por qué temían los malos ángeles la influencia de Daniel?',
 o:['Porque interpretaba sueños','Porque debilitaba el dominio que ejercían sobre los gobernantes','Porque era muy anciano','Porque conocía la ley de Media'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿cuántas veces vieron los príncipes ir a Daniel a su cámara en un solo día?',
 o:['Una vez','Dos veces','Tres veces','Siete veces'],a:2},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿qué vio el rey en seguida al oír la acusación contra Daniel?',
 o:['Que Daniel era culpable','La trampa que habían tendido a su siervo fiel','Que debía cambiar la ley','Que los leones tenían hambre'],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿por qué permitió Dios que echaran a Daniel al foso?',
 o:["Para que Daniel aprendiera a confiar y no volviera a exponerse ante los sátrapas","Para recalcar tanto más su liberación y que la derrota de sus enemigos fuera más completa","Porque la ley de Media y de Persia no podía ser abrogada ni por el rey ni por el Cielo","Para que el rey Darío quedara escarmentado y no volviera a firmar edictos sin pensarlos"],a:1},
{cap:'pr44',t:'mc',q:'Según P&R cap. 44, ¿qué revela la vida de Daniel sobre un hombre de negocios?',
 o:['Que debe seguir una política de conveniencias','Que puede ser un hombre instruido por Dios a cada paso','Que no debe mezclarse en el gobierno','Que la política corrompe siempre'],a:1},
{cap:'pr44',t:'tf',q:'Según P&R cap. 44, Daniel procuró ocultar su oración para que sus enemigos no lo vieran.',
 a:false,e:'Falso. «No procuraba ocultar su acto.» Oró con las ventanas abiertas, según su costumbre.'},
{cap:'pr44',t:'tf',q:'Según P&R cap. 44, en el foso de los leones Daniel fue el mismo que cuando actuaba delante del rey.',
 a:true,e:'Verdadero. Es la lección del capítulo: el que se apoya en Dios es igual en la prueba y en la prosperidad.'},
{cap:'pr44',t:'fill',ins:'Profetas y Reyes, cap. 44 — Completa la frase del libro:',
 p:[{x:'«...ninguna '},{b:'potencia',h:'¿qué cosa?'},
    {x:' terrenal tiene derecho a interponerse entre el '},{b:'alma',h:'¿entre qué?'},
    {x:' y Dios.»'}]},
{cap:'pr44',t:'fill',ins:'Profetas y Reyes, cap. 44 — Completa la frase sobre la prueba:',
 p:[{x:'«Un hombre cuyo corazón se apoya en Dios será en la hora de su '},
    {b:'prueba',h:'¿de qué?'},{x:' el mismo que en la '},{b:'prosperidad',h:'¿que en qué?'},{x:'...»'}]}
);

module.exports = { BANCO };
