/* Tarjetas de memorización. frente → reverso.
   cap sirve para filtrar por categoría igual que el banco de preguntas. */

const TARJETAS = [
  // Daniel 1
  {cap:'d1', f:'Nombre babilónico de <b>Daniel</b>', r:'Beltsasar'},
  {cap:'d1', f:'Nombre babilónico de <b>Ananías</b>', r:'Sadrac'},
  {cap:'d1', f:'Nombre babilónico de <b>Misael</b>', r:'Mesac'},
  {cap:'d1', f:'Nombre babilónico de <b>Azarías</b>', r:'Abed-nego'},
  {cap:'d1', f:'¿Quién era <b>Aspenaz</b>?', r:'El jefe de los eunucos (1:3)'},
  {cap:'d1', f:'¿Quién era <b>Melsar</b>?', r:'El sirviente puesto sobre Daniel y sus tres compañeros (1:11, 16)'},
  {cap:'d1', f:'Años de educación de los jóvenes', r:'TRES años (1:5)'},
  {cap:'d1', f:'Días que duró la prueba', r:'DIEZ días (1:12)'},
  {cap:'d1', f:'Qué pidieron comer y beber', r:'Legumbres para comer y agua para beber (1:12)'},
  {cap:'d1', f:'Cómo apareció su rostro a los diez días', r:'«Mejor y más robusto» que el de los otros muchachos (1:15)'},
  {cap:'d1', f:'Cuántas veces mejores que los magos', r:'DIEZ veces mejores (1:20)'},
  {cap:'d1', f:'Don que recibió solo Daniel', r:'Entendimiento en toda visión y sueños (1:17)'},
  {cap:'d1', f:'Hasta cuándo continuó Daniel', r:'Hasta el año primero del rey Ciro (1:21)'},
  {cap:'d1', f:'Año del reinado de Joacim en que cae Jerusalén', r:'El TERCER año (1:1)'},

  // Daniel 2
  {cap:'d2', f:'Año del reinado en que Nabucodonosor soñó', r:'El SEGUNDO año (2:1)'},
  {cap:'d2', f:'¿Quién era <b>Arioc</b>?', r:'El capitán de la guardia del rey (2:14)'},
  {cap:'d2', f:'Cómo se le reveló el misterio a Daniel', r:'En visión de noche (2:19)'},
  {cap:'d2', f:'Material de la <b>cabeza</b>', r:'Oro fino → Babilonia'},
  {cap:'d2', f:'Material del <b>pecho y brazos</b>', r:'Plata → Medo-Persia'},
  {cap:'d2', f:'Material del <b>vientre y muslos</b>', r:'Bronce → Grecia'},
  {cap:'d2', f:'Material de las <b>piernas</b>', r:'Hierro → Roma'},
  {cap:'d2', f:'Material de los <b>pies</b>', r:'Hierro y barro cocido → reinos divididos'},
  {cap:'d2', f:'Dónde hirió la piedra a la imagen', r:'En sus pies de hierro y de barro cocido (2:34)'},
  {cap:'d2', f:'En qué se convirtió la piedra', r:'En un gran monte que llenó toda la tierra (2:35)'},
  {cap:'d2', f:'Cargo que recibió Daniel', r:'Gobernador de la provincia de Babilonia y principal de los gobernadores sobre los sabios (2:48)'},

  // Daniel 3
  {cap:'d3', f:'Medidas de la estatua de oro', r:'SESENTA codos de alto por SEIS de ancho (3:1)'},
  {cap:'d3', f:'Dónde se levantó la estatua', r:'En el campo de Dura, provincia de Babilonia (3:1)'},
  {cap:'d3', f:'Los seis instrumentos, en orden (RV1995)', r:'Bocina, flauta, CÍTARA, arpa, salterio y zampoña (3:5). La RV1960 dice «tamboril» en el tercer lugar'},
  {cap:'d3', f:'Instrumento que NO aparece en Daniel 3', r:'La trompeta'},
  {cap:'d3', f:'Cuántas veces más caliente el horno', r:'SIETE veces más de lo acostumbrado (3:19)'},
  {cap:'d3', f:'Con qué ropa entraron al horno', r:'Con sus mantos, sus calzados, sus turbantes y sus vestidos (3:21)'},
  {cap:'d3', f:'Qué les pasó a los que los echaron', r:'La llama del fuego los mató (3:22)'},
  {cap:'d3', f:'Cuántos vio el rey en el horno', r:'CUATRO varones sueltos (3:25)'},
  {cap:'d3', f:'Cómo describió Nabucodonosor al cuarto del horno', r:'«Semejante a un hijo de los dioses» (3:25, RV1995). P&R 41: era el Hijo de Dios mismo'},
  {cap:'d3', f:'Las cuatro cosas que no sufrieron daño (3:27)', r:'El fuego no tuvo poder sobre sus cuerpos, ni aun el cabello se había quemado, sus ropas quedaron intactas, y ni siquiera olor de fuego tenían'},
  {cap:'d3', f:'La frase clave de los tres jóvenes', r:'«Y si no, has de saber, oh rey, que no serviremos a tus dioses ni tampoco adoraremos la estatua que has levantado» (3:18) (3:18)'},

  // Daniel 4
  {cap:'d4', f:'Hasta dónde llegaba el árbol', r:'Hasta el cielo; se veía hasta los confines de la tierra (4:11)'},
  {cap:'d4', f:'Con qué quedó atada la cepa', r:'Con atadura de hierro y de bronce (4:15, 23)'},
  {cap:'d4', f:'Cuántos tiempos pasarían sobre el rey', r:'SIETE tiempos (4:25)'},
  {cap:'d4', f:'Cuánto tiempo de gracia tuvo', r:'DOCE meses, un año completo (4:29)'},
  {cap:'d4', f:'Cómo le creció el cabello', r:'Como plumas de águila (4:33)'},
  {cap:'d4', f:'Cómo quedaron sus uñas', r:'Como las de las aves (4:33)'},
  {cap:'d4', f:'Qué hizo para recuperar la razón', r:'Alzó sus ojos al cielo (4:34)'},
  {cap:'d4', f:'El consejo de Daniel al rey', r:'Redimir sus pecados con justicia y sus iniquidades haciendo misericordias para con los oprimidos (4:27)'},

  // Daniel 5
  {cap:'d5', f:'Cuántos convidados en el banquete', r:'MIL príncipes (5:1)'},
  {cap:'d5', f:'De dónde eran los vasos que usó', r:'Del templo que estaba en Jerusalén (5:2)'},
  {cap:'d5', f:'Frente a qué apareció la escritura', r:'Delante del candelero (5:5)'},
  {cap:'d5', f:'El texto exacto de la pared', r:'MENE, MENE, TEKEL, UPARSIN (5:25)'},
  {cap:'d5', f:'Qué significa <b>MENE</b>', r:'Contó Dios tu reino, y le ha puesto fin (5:26)'},
  {cap:'d5', f:'Qué significa <b>TEKEL</b>', r:'Pesado has sido en balanza, y fuiste hallado falto (5:27)'},
  {cap:'d5', f:'Qué significa <b>PERES</b>', r:'Tu reino ha sido roto, y dado a los medos y a los persas (5:28)'},
  {cap:'d5', f:'Las tres cosas ofrecidas', r:'Vestido de púrpura, collar de oro y ser el TERCER señor del reino (5:7)'},
  {cap:'d5', f:'Quién recordó a Daniel al rey', r:'La reina (5:10-12)'},
  {cap:'d5', f:'Edad de Darío al recibir el reino', r:'SESENTA Y DOS años (5:31)'},

  // Daniel 6
  {cap:'d6', f:'Cuántos sátrapas puso Darío', r:'CIENTO VEINTE (6:1)'},
  {cap:'d6', f:'Cuántos gobernadores sobre ellos', r:'TRES, y Daniel era uno de ellos (6:2)'},
  {cap:'d6', f:'Por qué sobresalía Daniel', r:'Porque había en él un espíritu superior (6:3)'},
  {cap:'d6', f:'Por qué no hallaron falta en él', r:'Porque él era fiel, y ningún error ni falta hallaron en él (6:4)'},
  {cap:'d6', f:'Cuántos días duraba el edicto', r:'TREINTA días (6:7)'},
  {cap:'d6', f:'Cuántas veces al día oraba', r:'TRES veces al día (6:10)'},
  {cap:'d6', f:'Hacia dónde daban sus ventanas', r:'Hacia Jerusalén (6:10)'},
  {cap:'d6', f:'La frase final de Daniel 6:10', r:'«...como solía hacerlo antes»'},
  {cap:'d6', f:'Con qué se selló la piedra del foso', r:'Con el anillo del rey y con el de sus príncipes (6:17)'},
  {cap:'d6', f:'Qué hizo el rey esa noche', r:'Se acostó en ayunas; no trajeron ante él instrumentos musicales, y se le fue el sueño (6:18)'},
  {cap:'d6', f:'Cuándo fue el rey al foso', r:'Se levantó muy de mañana y fue apresuradamente al foso (6:19)'},
  {cap:'d6', f:'Qué respondió Daniel desde el foso', r:'«Mi Dios envió su ángel, el cual cerró la boca de los leones» (6:22)'},

  // P&R
  {cap:'pr39', f:'Título del capítulo <b>39</b> de P&R', r:'«En la corte de Babilonia»'},
  {cap:'pr39', f:'Por qué rechazaron la comida del rey', r:'Había sido ofrecida a los ídolos y violaba las leyes de Dios'},
  {cap:'pr39', f:'Qué relación hay entre cuerpo y mente', r:'Los hábitos físicos temperantes favorecen la claridad mental y espiritual'},
  {cap:'pr40', f:'Título del capítulo <b>40</b> de P&R', r:'«El sueño de Nabucodonosor»'},
  {cap:'pr40', f:'A qué recurrieron ante la sentencia de muerte', r:'A la oración, antes que a cualquier estrategia humana'},
  {cap:'pr41', f:'Título del capítulo <b>41</b> de P&R', r:'«El horno de fuego»'},
  {cap:'pr41', f:'Quién era el cuarto del horno según E. de White', r:'El Hijo de Dios mismo'},
  {cap:'pr41', f:'Qué muestra la frase «y si no»', r:'Que la obediencia no dependía de recibir el milagro'},
  {cap:'pr42', f:'Título del capítulo <b>42</b> de P&R', r:'«La verdadera grandeza»'},
  {cap:'pr42', f:'Pecado principal de Nabucodonosor', r:'El orgullo: se atribuyó la gloria que pertenecía a Dios'},
  {cap:'pr43', f:'Título del capítulo <b>43</b> de P&R', r:'«El vigía invisible»'},
  {cap:'pr43', f:'Por qué Belsasar no tenía excusa', r:'Conocía la experiencia de Nabucodonosor y aun así se rebeló'},
  {cap:'pr44', f:'Título del capítulo <b>44</b> de P&R', r:'«En el foso de los leones»'},
  {cap:'pr44', f:'Qué caracterizaba la oración de Daniel', r:'Era la fuente diaria de su fortaleza, no una emergencia'},
  {cap:'pr44', f:'Qué edad tenía Daniel en el foso', r:'Más de ochenta años'},
];


/* ─── Ampliación 8-sep: más tarjetas para los tres capítulos del reglamento
   nuevo (Daniel 1, 3 y 6), con dos formas que no existían: el VERSÍCULO CLAVE
   (frente la referencia, reverso el texto exacto) y la CIFRA. Todo el texto
   entre comillas viene verificado del RV1995. ─── */
TARJETAS.push(
  // Daniel 1
  {cap:'d1', f:'¿Quién entregó a Joacim en manos de Nabucodonosor?', r:'<b>El Señor</b> (1:2). No fue el ejército: el texto lo dice así'},
  {cap:'d1', f:'Tierra a donde llevaron los utensilios', r:'Tierra de <b>Sinar</b>, a la casa del tesoro de su dios (1:2)'},
  {cap:'d1', f:'Linaje de los muchachos escogidos', r:'Del <b>linaje real de los príncipes</b> (1:3)'},
  {cap:'d1', f:'Qué debía enseñarles Aspenaz', r:'Las <b>letras y la lengua de los caldeos</b> (1:4)'},
  {cap:'d1', f:'Para qué debían ser idóneos', r:'Para <b>estar en el palacio del rey</b> (1:4)'},
  {cap:'d1', f:'Beltsasar o Belsasar', r:'<b>Beltsasar</b> es Daniel (1:7). <b>Belsasar</b> es el rey del banquete del capítulo 5. Dos personas distintas'},
  {cap:'d1', f:'Cuántos versículos tiene Daniel 1', r:'<b>21</b> versículos'},
  {cap:'d1', f:'Cuántos capítulos tiene el libro de Daniel', r:'<b>12</b> capítulos. El campamento cubre 1, 3 y 6'},
  {cap:'d1', f:'Versículo clave <b>1:8</b>', r:'«Daniel propuso en su corazón no contaminarse con la porción de la comida del rey ni con el vino que él bebía»'},
  {cap:'d1', f:'Versículo clave <b>1:17</b>', r:'«Dios les dio conocimiento e inteligencia en todas las letras y ciencias; y Daniel tuvo entendimiento en toda visión y sueños»'},
  // Daniel 3
  {cap:'d3', f:'De qué material era la estatua', r:'De <b>oro</b> (3:1)'},
  {cap:'d3', f:'Quién hizo levantar la estatua', r:'El rey <b>Nabucodonosor</b> (3:1)'},
  {cap:'d3', f:'Sobre qué estaban puestos los tres jóvenes', r:'Sobre los <b>negocios de la provincia de Babilonia</b> (3:12)'},
  {cap:'d3', f:'De qué dijeron que Dios podía librarlos', r:'Del <b>horno de fuego ardiente</b> y de <b>las manos del rey</b> (3:17)'},
  {cap:'d3', f:'Quién NO aparece en Daniel 3', r:'<b>Daniel</b>. Los tres del horno son Sadrac, Mesac y Abed-nego'},
  {cap:'d3', f:'Cómo llamó el rey a los tres al sacarlos', r:'«Siervos del <b>Dios Altísimo</b>» (3:26)'},
  {cap:'d3', f:'Qué dijo Nabucodonosor que Dios envió', r:'Su <b>ángel</b>, que libró a sus siervos que confiaron en él (3:28)'},
  {cap:'d3', f:'Qué hizo el rey con los tres al final', r:'Los <b>engrandeció</b> en la provincia de Babilonia (3:30)'},
  {cap:'d3', f:'Cuántos versículos tiene Daniel 3', r:'<b>30</b> versículos'},
  {cap:'d3', f:'Versículo clave <b>3:17</b>', r:'«Nuestro Dios, a quien servimos, puede librarnos del horno de fuego ardiente; y de tus manos, rey, nos librará»'},
  // Daniel 6
  {cap:'d6', f:'Para qué puso Darío tres gobernadores', r:'Para que <b>el rey no fuera perjudicado</b> (6:2)'},
  {cap:'d6', f:'Qué pensó el rey hacer con Daniel', r:'<b>Ponerlo sobre todo el reino</b> (6:3)'},
  {cap:'d6', f:'Qué pusieron sobre la puerta del foso', r:'Una <b>piedra</b>, sellada con el anillo del rey y con el de sus príncipes (6:17)'},
  {cap:'d6', f:'Qué les pasó a los acusadores', r:'Fueron echados al foso con sus hijos y sus mujeres; los leones <b>quebraron todos sus huesos</b> (6:24)'},
  {cap:'d6', f:'A quiénes escribió Darío al final', r:'A <b>todos los pueblos, naciones y lenguas</b>: «Paz os sea multiplicada» (6:25)'},
  {cap:'d6', f:'Cuántos versículos tiene Daniel 6', r:'<b>28</b> versículos'},
  {cap:'d6', f:'Versículo clave <b>6:10</b>', r:'«se arrodillaba tres veces al día, oraba y daba gracias delante de su Dios como solía hacerlo antes»'},
  {cap:'d6', f:'Versículo clave <b>6:22</b>', r:'«Mi Dios envió su ángel, el cual cerró la boca de los leones para que no me hicieran daño»'},
  {cap:'d6', f:'Versículo clave <b>6:26</b>', r:'«su reino no será jamás destruido y su dominio perdurará hasta el fin»'},
  {cap:'d6', f:'Reyes en cuyos reinados prosperó Daniel', r:'<b>Darío</b> y <b>Ciro</b>, el persa (6:28)'}
);


/* ─── Ampliación 8-sep: tarjetas de P&R 39, 41 y 44, los tres que entran al
   reglamento. Pasan de 3 a 8 por capítulo, con FRASE CLAVE del libro. ─── */
TARJETAS.push(
  {cap:'pr39', f:'A quién ordenó el rey traer a los jóvenes', r:'A <b>Aspenaz</b>, príncipe de sus eunucos'},
  {cap:'pr39', f:'Por qué les cambiaron los nombres', r:'Por otros que <b>conmemoraban divinidades caldeas</b>: era el primer paso para que renunciaran a su fe'},
  {cap:'pr39', f:'Qué historia sobre la intemperancia conocían', r:'La de <b>Nadab y Abihú</b>, descrita en el Pentateuco'},
  {cap:'pr39', f:'Quién les inculcó la templanza', r:'Sus <b>padres</b>, desde temprano en la vida'},
  {cap:'pr39', f:'Frase clave de P&R 39', r:'«Fué la fidelidad en las <b>cosas pequeñas</b> lo que dió carácter a toda su vida»'},
  {cap:'pr41', f:'En qué se diferenció la imagen de Dura', r:'Era <b>toda de oro</b>. En el sueño había descenso de valores desde la cabeza hasta los pies'},
  {cap:'pr41', f:'Quiénes propusieron hacer la imagen', r:'Los <b>sabios del reino</b>, aprovechando la frase «tú eres aquella cabeza de oro»'},
  {cap:'pr41', f:'Qué fue lo único que se quemó', r:'Solo <b>sus ligaduras</b>'},
  {cap:'pr41', f:'Qué promesa recordaron en la prueba', r:'Isaías 43:2: «Cuando pasares por el fuego, no te quemarás»'},
  {cap:'pr41', f:'Frase clave de P&R 41', r:'«Nunca compele Dios a los hombres a <b>obedecer</b>. Deja a todos libres para elegir a quien quieren servir»'},
  {cap:'pr44', f:'Qué despertaron los honores de Daniel', r:'Los <b>celos</b> de los principales del reino'},
  {cap:'pr44', f:'A qué apelaron para que Darío firmara', r:'A su <b>vanidad</b>: le dijeron que el edicto acrecentaría su honor y autoridad'},
  {cap:'pr44', f:'Quién estaba detrás de la conspiración', r:'<b>Satanás</b>, por medio de los príncipes envidiosos'},
  {cap:'pr44', f:'Cuántas veces lo vieron orar', r:'<b>Tres veces</b> en un solo día: lo vigilaron todo el día'},
  {cap:'pr44', f:'Frase clave de P&R 44', r:'«...ninguna potencia terrenal tiene derecho a interponerse entre el <b>alma</b> y Dios»'}
);


/* Daniel 7 (v54): tarjetas basicas de repaso rapido, no exhaustivas. */
TARJETAS.push(
  {cap:'d7', f:'En qué año tuvo Daniel esta visión', r:'El año primero de <b>Belsasar</b> (7:1), unos 553 a.C.'},
  {cap:'d7', f:'Cuántas bestias salen del mar', r:'<b>Cuatro</b>: león, oso, leopardo y una cuarta sin nombre'},
  {cap:'d7', f:'Qué reino es el león con alas', r:'<b>Babilonia</b>'},
  {cap:'d7', f:'Qué reino es el oso alzado de un costado', r:'<b>Medo-Persia</b>'},
  {cap:'d7', f:'Qué reino es el leopardo de cuatro cabezas', r:'<b>Grecia</b>'},
  {cap:'d7', f:'Por qué el leopardo tiene cuatro cabezas', r:'Por los <b>cuatro generales</b> que se repartieron el imperio de Alejandro tras Ipso (301 a.C.)'},
  {cap:'d7', f:'Qué reino es la cuarta bestia, la que no se parece a ningún animal', r:'<b>Roma</b>'},
  {cap:'d7', f:'Cuántos cuernos tiene la cuarta bestia', r:'<b>Diez</b> (7:24)'},
  {cap:'d7', f:'Cuántos cuernos arranca el cuerno pequeño', r:'<b>Tres</b> (7:8, 24)'},
  {cap:'d7', f:'Qué tres tribus arrianas fueron eliminadas', r:'<b>Hérulos (493), vándalos (534) y ostrogodos (538)</b>'},
  {cap:'d7', f:'Cuánto es «tiempo, tiempos y medio tiempo»', r:'<b>3 años y medio</b>, o 1.260 días proféticos (7:25)'},
  {cap:'d7', f:'A cuántos años equivalen esos 1.260 días', r:'<b>1.260 años: del 538 al 1798</b>, con la regla de día por año (Ezequiel 4:6)'},
  {cap:'d7', f:'Qué pasó en 1798 con el papa', r:'El general francés <b>Berthier</b> arrestó a Pío VI y lo llevó al exilio'},
  {cap:'d7', f:'Quién se sienta a juzgar en la visión', r:'El <b>Anciano de días</b> (7:9)'},
  {cap:'d7', f:'A quién se le entrega el reino al final del juicio', r:'A <b>los santos del Altísimo</b>, para siempre (7:18, 27)'},
  {cap:'d7', f:'Cuántas veces se repite la escena del juicio en el capítulo', r:'<b>Cuatro veces</b>: 7:9-14, 7:18, 7:22 y 7:26-27'},
  {cap:'d7', f:'A qué corresponde el cuerno pequeño en la estatua de Daniel 2', r:'A los <b>pies de hierro y barro</b>: Europa dividida, sin volver a unirse'}
);

TARJETAS.push(
{cap:'d8', f:'¿En qué año de qué rey tuvo Daniel la visión del capítulo 8?', r:'Año tercero de Belsasar, 551 a.C. (dos años después de Daniel 7).'},
{cap:'d8', f:'¿Dónde estaba Daniel en la visión?', r:'Junto al río Ulay, en Susa, provincia de Elam (futura capital de invierno de Medo-Persia).'},
{cap:'d8', f:'¿Qué representa el carnero de dos cuernos?', r:'Medo-Persia (Daniel 8:20); el cuerno más alto, que despuntó después, es Persia.'},
{cap:'d8', f:'¿Qué representa el macho cabrío?', r:'Grecia (Yaván), Daniel 8:21.'},
{cap:'d8', f:'¿Qué representa el cuerno grande del macho cabrío?', r:'El primer rey de Grecia, Alejandro Magno (Daniel 8:21).'},
{cap:'d8', f:'¿En qué tres batallas Alejandro derrotó a los persas?', r:'Río Gránico (334 a.C.), Iso (333 a.C.) y Arbela/Gaugamela (331 a.C.).'},
{cap:'d8', f:'¿Qué representan los cuatro cuernos que salen tras romperse el grande?', r:'Los cuatro reinos en que se repartió el imperio de Alejandro: Casandro, Lisímaco, Seleuco y Tolomeo.'},
{cap:'d8', f:'¿A qué edad murió Alejandro Magno y en qué año?', r:'A los 32 años, en el 323 a.C.'},
{cap:'d8', f:'¿De dónde sale el cuerno pequeño de Daniel 8, según el hebreo del pasaje?', r:'De uno de los cuatro "vientos" (puntos cardinales), no de uno de los cuatro cuernos griegos: por eso apunta a un poder que crece desde afuera, Roma.'},
{cap:'d8', f:'¿Qué tres cosas hace el cuerno pequeño de Daniel 8?', r:'Crece hacia el sur, el oriente y la Tierra del Esplendor; abole el sacrificio continuo (tamid); hace caer el lugar del santuario.'},
{cap:'d8', f:'¿Por qué el cuerno pequeño de Daniel 8 no puede ser Antíoco Epífanes?', r:'Antíoco aparece hacia la mitad de la dinastía seléucida, no "al término" del reino helénico como pide el texto; murió en 164 a.C., casi 200 años antes de que Jesús hablara de esta profecía como futura (Mateo 24:15); y los cuernos representan reinos, no reyes individuales.'},
{cap:'d8', f:'¿Qué territorios conquistó Roma que cumplen "creció mucho hacia el sur, el oriente y la Tierra del Esplendor"?', r:'Macedonia (168 a.C.), Siria (65 a.C.), Palestina (63 a.C.) y Egipto (30 a.C.).'},
{cap:'d8', f:'¿Qué significa la palabra hebrea tamid?', r:'"Continuo" o "permanente"; en el santuario se aplicaba al holocausto diario, las lámparas y el pan siempre presentes. En Daniel 8 representa el ministerio permanente de Cristo como Sumo Sacerdote.'},
{cap:'d8', f:'¿Cuánto duran las "2.300 tardes y mañanas" de Daniel 8:14, con la regla de día por año?', r:'2.300 años.'},
{cap:'d8', f:'¿Qué significa la palabra hebrea nitsdaq, traducida "reivindicado" o "purificado"?', r:'Está emparentada con "justificar"; señala el Día de la Expiación, el día de juicio del santuario del Antiguo Testamento.'},
{cap:'d8', f:'¿En qué decreto y año comienzan las 2.300 años, y en qué año terminan?', r:'En el decreto de Artajerjes I para restaurar Jerusalén, año 457 a.C. (Esdras 7); terminan en el año 1844.'},
{cap:'d8', f:'¿Qué pasó en 1844 según esta interpretación?', r:'Comenzó el juicio investigador en el santuario celestial (no el regreso visible de Cristo, que era lo que esperaba el movimiento de William Miller).'},
{cap:'d8', f:'¿A qué enfoca cada visión de Daniel según su tema central?', r:'Daniel 2: a Cristo Rey. Daniel 7: a Cristo Juez. Daniel 8-9: a Cristo Sumo Sacerdote.'},
);
TARJETAS.push(
{cap:'d9', f:'¿Qué estaba leyendo Daniel cuando entendió que los 70 años de exilio estaban por cumplirse?', r:'Los libros del profeta Jeremías (Jeremías 25:11-12; 29:10), Daniel 9:2.'},
{cap:'d9', f:'¿Qué hizo Daniel al entender esto?', r:'Oró con ayuno, cilicio y ceniza, confesando el pecado de su pueblo (Daniel 9:3-19).'},
{cap:'d9', f:'¿Qué le trae Gabriel a Daniel en respuesta a su oración?', r:'No los 70 años de Jeremías, sino "setenta semanas" (490 años) reservadas para su pueblo y su ciudad santa (Daniel 9:24).'},
{cap:'d9', f:'¿A cuántos años equivalen las setenta semanas de Daniel 9:24?', r:'490 años (70 semanas × 7 días = 490, con la regla de día por año).'},
{cap:'d9', f:'¿Qué decreto y en qué año marca el inicio de las setenta semanas?', r:'El decreto de Artajerjes I para restaurar Jerusalén, año 457 a.C. (Esdras 7).'},
{cap:'d9', f:'¿En qué tres bloques se dividen las setenta semanas?', r:'Siete semanas (49 años, 457-408 a.C.); sesenta y dos semanas (434 años, 408 a.C.-27 d.C.); una última semana (7 años, 27-34 d.C.).'},
{cap:'d9', f:'¿Qué significa la palabra "Mesías"?', r:'"Ungido". En tiempos bíblicos se ungía con aceite a reyes, sacerdotes y profetas para consagrarlos.'},
{cap:'d9', f:'¿Cuándo y cómo fue ungido Jesús como el Mesías Príncipe?', r:'En su bautismo en el río Jordán, hacia fines del año 27 d.C., ungido por el Espíritu Santo (Mateo 3:16-17).'},
{cap:'d9', f:'¿Qué pasó "a la mitad de la semana" final, según Daniel 9:27?', r:'El Mesías hizo cesar el sacrificio y la ofrenda: Jesús fue crucificado en la primavera del año 31 d.C., tres años y medio después de su bautismo.'},
{cap:'d9', f:'¿Qué significa "se quitará la vida al Mesías, mas no por sí" (Daniel 9:26)?', r:'Que Jesús murió no por sus propios pecados sino por los de la humanidad.'},
{cap:'d9', f:'¿En qué año terminan las setenta semanas (490 años) y qué evento marcó ese cierre?', r:'En el año 34 d.C., con el apedreamiento de Esteban (Hechos 7), el primer mártir cristiano.'},
{cap:'d9', f:'¿Qué pasó poco después del año 34 d.C. con la predicación del evangelio?', r:'Se extendió abiertamente a los gentiles (conversión de Cornelio, Hechos 10; misión de Pablo, Hechos 22:21), sin dejar de incluir a los judíos.'},
{cap:'d9', f:'¿Cómo se relacionan los 2.300 años de Daniel 8 y las 490 años de Daniel 9?', r:'Comparten el mismo punto de partida (457 a.C.); las 490 años son la primera parte de los 2.300. Restando: 2.300 − 490 = 1.810 años después del 34 d.C.'},
{cap:'d9', f:'Sumando 1.810 años al 34 d.C., ¿a qué año se llega?', r:'Al año 1844, el mismo punto que Daniel 8:14 señala para la purificación del santuario celestial.'},
{cap:'d9', f:'¿Por qué Daniel 9 es la continuación directa de Daniel 8?', r:'Porque Gabriel había sido interrumpido en Daniel 8:27 antes de explicar cuándo empezaban las 2.300 tardes y mañanas; en Daniel 9 retoma exactamente ese punto y da el dato que faltaba, el decreto del 457 a.C.'},
);
TARJETAS.push(
{cap:'d10', f:'¿Cuándo y dónde ocurre la visión de Daniel 10?', r:'En la primavera del año tercero de Ciro (hacia el 535 a.C.), junto al río Tigris.'},
{cap:'d10', f:'¿Por qué ayunaba Daniel tres semanas?', r:'Por la reconstrucción del templo de Jerusalén, que enfrentaba fuerte oposición de los pueblos vecinos (Esdras 4).'},
{cap:'d10', f:'¿Con qué otra visión bíblica coincide en detalle la descripción del Ser glorioso de Daniel 10?', r:'Con la descripción que Juan hace de Jesús glorificado en Apocalipsis 1:13-16.'},
{cap:'d10', f:'¿Quién es el "Príncipe del reino de Persia" que resiste al ángel 21 días?', r:'Un ángel maligno identificado con el Imperio Persa, no el rey Ciro.'},
{cap:'d10', f:'¿Quién viene a ayudar y vence esa resistencia?', r:'Miguel, "uno de los Primeros Príncipes" (Daniel 10:13).'},
{cap:'d10', f:'¿Qué significa el nombre "Miguel" en hebreo?', r:'Es una pregunta: "¿Quién es semejante a Dios?"'},
{cap:'d10', f:'¿Qué título le da Judas 9 a Miguel?', r:'"El arcángel", es decir, el jefe de los ángeles; en las Escrituras solo hay uno.'},
{cap:'d10', f:'¿Qué evidencia bíblica identifica a Miguel con Jesucristo?', r:'1 Tesalonicenses 4:16 y Juan 5:28-29 atribuyen la resurrección de los muertos tanto a "la voz del arcángel" como a "la voz del Hijo de Dios"; y Daniel 12:1 llama a Miguel "el gran Príncipe que defiende a los hijos de tu pueblo".'},
{cap:'d10', f:'¿Qué corrige la traducción Reina-Valera de Daniel 10:13 sobre quién es el Ser resplandeciente de la visión?', r:'Aclara que Miguel vino a ayudar a Gabriel y que el Ser glorioso de la visión no era Gabriel sino Miguel mismo, es decir, Jesús.'},
{cap:'d10', f:'¿Qué patrón de vida de Daniel corona el capítulo 10?', r:'Su vida de oración constante: oró ante el peligro de muerte (cap. 2), dio gracias frente a los leones (cap. 6), confesó el pecado de su pueblo (cap. 9) y ahora ayuna tres semanas por su pueblo.'},
{cap:'d10', f:'¿Cuándo empezó a ser oída la oración de Daniel, según el ángel?', r:'Desde el primer día en que oró y se humilló, aunque la respuesta visible tardó tres semanas por la resistencia angélica invisible (Daniel 10:12-13).'},
);
TARJETAS.push(
{cap:'d11', f:'¿Quién es el cuarto rey persa que "acumulará más riquezas que todos" e incita contra Grecia? (Daniel 11:2)', r:'Jerjes I (486-465 a.C.), que lanzó la gran invasión persa de Grecia.'},
{cap:'d11', f:'¿En qué se divide el reino de Alejandro tras su muerte, según Daniel 11:4?', r:'Se reparte "a los cuatro vientos del cielo": el mismo reparto entre cuatro generales que describe Daniel 8.'},
{cap:'d11', f:'¿A qué dos reinos se refieren "rey del sur" y "rey del norte" en Daniel 11?', r:'Egipto (dinastía ptolemaica) y Siria (dinastía seléucida), los dos reinos entre los que quedó Palestina.'},
{cap:'d11', f:'¿Qué matrimonio anuncia Daniel 11:6 y cómo termina?', r:'El matrimonio de Berenice (hija de Tolomeo II) con Antíoco II; termina en tragedia cuando Laodicea, la primera esposa repudiada, hace asesinar a Antíoco, a Berenice y a su hijo.'},
{cap:'d11', f:'¿Quién es Antíoco III "el Grande" y qué batalla gana en 198 a.C.?', r:'Rey seléucida (223-187 a.C.); gana la batalla de Panias y toma el control de Palestina.'},
{cap:'d11', f:'¿Qué potencia nueva aparece en Daniel 11:30 como "naves de Quitim" que detienen a Antíoco III?', r:'Roma.'},
{cap:'d11', f:'¿Quién es el "Príncipe de la alianza" del versículo 22, quebrantado en la profecía?', r:'Jesucristo, no un sumo sacerdote humano como Onías III.'},
{cap:'d11', f:'¿A qué período histórico corresponde la persecución de "los doctos" en Daniel 11:33?', r:'A los 1.260 años (538-1798) de persecución medieval y de la Reforma: valdenses, lolardos, husitas, luteranos, anabaptistas, hugonotes.'},
{cap:'d11', f:'¿A qué poder identifica la lectura adventista con "el rey que se engreirá por encima de todo dios" (vv. 36-38)?', r:'Al papado medieval, por reclamar prerrogativas que corresponden solo a Dios (perdonar pecados, cambiar los mandamientos) y desarrollar un culto opulento en oro y piedras preciosas.'},
{cap:'d11', f:'¿Con qué actitud tratan los comentaristas adventistas, incluida Elena de White, los versículos 40-45 de Daniel 11?', r:'Con especial cautela: evitan parafrasearlos con precisión, porque los eventos exactos de su cumplimiento final no se conocen del todo por anticipado.'},
{cap:'d11', f:'¿Con qué otro pasaje de Daniel es paralelo el final del "rey del norte" en Daniel 11:45?', r:'Con el fin del cuerno pequeño de Daniel 7:11, 26, que también "llega a su fin" sin ayuda en el juicio celestial.'},
);
TARJETAS.push(
{cap:'d12', f:'¿Qué marca la aparición de Miguel en Daniel 12:1?', r:'Que el juicio celestial de Daniel 7:9-14 y 8:14 ha concluido, y Jesús se levanta para venir a la tierra.'},
{cap:'d12', f:'¿En qué se diferencia la tribulación final de Daniel 12:1 de la tribulación anterior de Mateo 24:9?', r:'En la anterior los santos son entregados a la muerte; en la tribulación final los santos son librados de la muerte.'},
{cap:'d12', f:'¿Es la resurrección de Daniel 12:2 la resurrección general de todos los muertos?', r:'No: es una resurrección especial y limitada, que incluye a algunos justos recién fallecidos y a quienes participaron en la crucifixión de Jesús.'},
{cap:'d12', f:'¿Quiénes son "los doctos" que "brillarán como el fulgor del firmamento" (Daniel 12:3)?', r:'Los que estudiaron las profecías de Daniel hasta comprenderlas, las compartieron con otros y se dejaron purificar por ellas.'},
{cap:'d12', f:'¿Qué significa "sella el libro hasta el tiempo del Fin" (Daniel 12:4)?', r:'No todo el libro quedaba sellado (Babilonia, Media-Persia y Grecia ya estaban identificadas sin misterio); lo sellado eran los acontecimientos del tiempo del fin, que se comprenderían plenamente más cerca de su cumplimiento.'},
{cap:'d12', f:'¿A qué período corresponde "un tiempo, tiempos y medio tiempo" de Daniel 12:7?', r:'A los mismos 1.260 años (538-1798) que señala Daniel 7:25.'},
{cap:'d12', f:'¿Qué pregunta de Daniel no respondió Miguel, y qué nos enseña eso?', r:'"¿Cuál será la última de estas cosas?"; enseña que la profecía se da con propósitos prácticos, no para satisfacer la curiosidad.'},
{cap:'d12', f:'¿Qué diferencia hay entre el libro "cerrado y sellado" de Daniel 12 y el mismo Ser que aparece en Apocalipsis 10?', r:'En Apocalipsis 10 el libro aparece abierto, y el ángel jura que "ya no habrá más dilación": queda abierto para los últimos días.'},
{cap:'d12', f:'¿Qué dos plazos de días menciona Daniel 12:11-12?', r:'1.290 días y 1.335 días, contados desde que sea abolido el sacrificio perpetuo e instalada la abominación desoladora.'},
{cap:'d12', f:'¿Qué reconoce Maxwell sobre el cumplimiento exacto de los 1.290 y 1.335 días?', r:'Que, al no darse un acontecimiento específico que marque su inicio o cierre, no es posible aún establecer con certeza cómo se cumplirán.'},
{cap:'d12', f:'¿Cuál es la promesa personal de despedida para Daniel en el versículo 13?', r:'"Vete a descansar; te levantarás para recibir tu suerte al Fin de los días": Daniel dormiría hasta la resurrección y tendría asegurado su lugar entre los santos.'},

  {cap:'pr40', f:'Por qué el rey no les contó el sueño a sus sabios de entrada', r:'Al despertar no pudo recordar los detalles, así que primero les pidió que lo adivinaran'},
  {cap:'pr40', f:'Qué probaba el rey al ofrecer riquezas y amenazar de muerte a la vez', r:'Si sus sabios de verdad podían hacer lo que decían que podían'},
  {cap:'pr40', f:'Qué representa cada metal de la imagen', r:'Un imperio sucesivo en la historia, en orden descendente de valor'},
  {cap:'pr40', f:'Qué muestra la sucesión de imperios de la imagen', r:'Que los reinos se levantan y caen conforme al propósito divino: Dios gobierna la historia'},
  {cap:'pr40', f:'Qué representa la piedra cortada sin manos', r:'A Cristo y el establecimiento de su reino eterno, que destruye los reinos terrenales'},
  {cap:'pr40', f:'A quién apuntó siempre Daniel al interpretar el sueño', r:'A Dios, como la fuente de toda sabiduría, nunca a sí mismo'},

  {cap:'pr42', f:'Qué título le da la Inspiración a Nabucodonosor pese a ser idólatra (Ezequiel 26:7)', r:'"Rey de reyes"'},
  {cap:'pr42', f:'Tesis detrás del título «La verdadera grandeza»', r:'La grandeza del rey no estaba en su imperio, sino en lo que reconocía'},
  {cap:'pr42', f:'Qué olvidó Nabucodonosor sobre su poder y su reino', r:'Que eran un don de Dios, no un logro propio'},
  {cap:'pr42', f:'Cuánto tiempo de gracia recibió antes del juicio', r:'Un año completo para arrepentirse'},
  {cap:'pr42', f:'Qué le fue devuelto al reconocer la soberanía de Dios', r:'Su razón y su reino'},
  {cap:'pr42', f:'Cómo terminó Nabucodonosor, según su testimonio final', r:'Como adorador del Dios verdadero: uno de los testimonios más poderosos de un rey gentil en la Biblia'},

  {cap:'pr43', f:'Cómo resuelve P&R que Daniel 5 llame "padre" a Nabucodonosor si era abuelo de Belsasar', r:'En el lenguaje bíblico "padre" incluye al antepasado, como "hijo de David" a alguien de generaciones después'},
  {cap:'pr43', f:'Cuánto tiempo había pasado entre el cautiverio de Daniel y los sucesos de Daniel 5', r:'Más de sesenta años'},
  {cap:'pr43', f:'Cómo describe P&R a los sucesores de Nabucodonosor', r:'Sucesores imprudentes: una disolución gradual pero segura del imperio'},
  {cap:'pr43', f:'Qué sabía Belsasar sobre su abuelo y aun así no aprendió', r:'Que Dios lo había desterrado de la sociedad de los hombres, y que después se había convertido y sanado'},
  {cap:'pr43', f:'Qué dejó que le borrara a Belsasar las lecciones que ya conocía', r:'El amor por los placeres y la glorificación propia'},
  {cap:'pr43', f:'Qué enseña el capítulo sobre el pecado que llega a su colmo', r:'Que cuando se colma la medida del pecado, no hay demora en el juicio'},

  {cap:'d9', f:'¿Quién emitió el decreto de 457 a.C., y en qué libro bíblico se registra?', r:'Artajerjes I, en su séptimo año de reinado, registrado en Esdras 7'},
  {cap:'d9', f:'¿Qué autoridad le dio ese decreto a Esdras?', r:'Autoridad civil y judicial para reorganizar la nación judía'},
  {cap:'d9', f:'¿En qué basa Daniel su pedido en la oración de Daniel 9:18?', r:'No en los méritos de su pueblo, sino en las grandes misericordias de Dios'},
  {cap:'d9', f:'¿Qué actitud muestra Daniel en su oración, comparada con Daniel 6:4?', r:'Se identificaba con las faltas de su nación aun siendo personalmente irreprochable'},

  {cap:'d10', f:'¿De qué se abstuvo Daniel durante las tres semanas de ayuno?', r:'De alimentos suculentos, carne y vino'},
  {cap:'d10', f:'¿A qué edad fue Daniel llevado cautivo, y a cuál se acercaba en Daniel 10?', r:'Cautivo a los 17 años; se acercaba a los noventa'},
  {cap:'d10', f:'¿Con qué pasaje de Pablo se compara la guerra invisible de Daniel 10?', r:'Efesios 6:12: "no tenemos lucha contra sangre y carne..."'},
  {cap:'d10', f:'¿Qué lección práctica deja que la respuesta tardara tres semanas en manifestarse?', r:'Que una oración sin respuesta inmediata no significa una oración no escuchada'},

  {cap:'d11', f:'¿Quién es "un rey valeroso" cuyo imperio se reparte entre cuatro generales?', r:'Alejandro Magno'},
  {cap:'d11', f:'¿Quién es la última reina de la dinastía ptolemaica?', r:'Cleopatra VI'},
  {cap:'d11', f:'¿Qué distingue a "rey del norte" después de la derrota de Antíoco III frente a Roma?', r:'Deja de referirse solo a Siria y pasa a describir a Roma'},
  {cap:'d11', f:'¿Qué dijo Jesús en Mateo 24:15 sobre la abominación desoladora?', r:'Que todavía era futura en su tiempo, casi dos siglos después de Antíoco Epífanes'},

  {cap:'d12', f:'¿Qué otra cosa ocurriría, según Daniel 12:4, mientras "muchos andaban errantes"?', r:'La ciencia (el conocimiento) se aumentaría'},
  {cap:'d12', f:'¿Qué dice el ángel de Apocalipsis 10:6 que no dice el de Daniel 12:7?', r:'Que "ya no habrá más dilación"'},
  {cap:'d12', f:'¿A quiénes, además de algunos justos, incluye la resurrección especial de Daniel 12:2?', r:'A quienes participaron directamente en la crucifixión de Jesús'},
  {cap:'d12', f:'¿En qué seis puntos resume Maxwell el mensaje final del libro de Daniel?', r:'Dios conoce el futuro; dirige el destino de los imperios; el juicio ya está en sesión; puede librarnos de toda dificultad; Cristo anhela que su alianza prevalezca; y no concibe la eternidad sin nosotros'},

  {cap:'d10', f:'¿En torno a quién giran realmente los capítulos 10 a 12, y no en torno a un ángel intermediario?', r:'En torno a Jesucristo mismo (Miguel), glorificado antes de recorrer la historia hasta el fin'},
  {cap:'d10', f:'¿Cuál fue el último acto registrado de Daniel en el libro?', r:'Un ayuno de tres semanas, seguido de la visión más larga y detallada de los doce capítulos'},

  {cap:'d12', f:'Según el primer punto del resumen de Maxwell, ¿qué sabe Dios?', r:'El pasado, el presente y el futuro; nada lo sorprende'},
  {cap:'d12', f:'Según el cuarto punto del resumen de Maxwell, ¿de qué nos librará pronto Dios?', r:'De la muerte misma, igual que ya libra de leones y hornos de fuego'},
  {cap:'d11', f:'¿Qué batalla de 217 a.C. usó elefantes de guerra de ambos bandos?', r:'La batalla de Rafia, en las guerras sirias entre Egipto y Siria'},
  {cap:'d11', f:'¿Qué batalla de 198 a.C. terminó con 103 años de dominio ptolemaico sobre Judea?', r:'La batalla de Panias, que dio paso al dominio seléucida'},
  {cap:'d11', f:'¿Qué edicto de 538 marcó, según la lectura histórica, el inicio de los 1.260 años?', r:'El Edicto de Justiniano, que reconoció al papa como cabeza de todas las iglesias'},
  {cap:'d11', f:'¿Qué emperador se humilló ante el papa en Canossa en 1077?', r:'Enrique IV, del Sacro Imperio Romano Germánico, ante el papa Gregorio VII'},
  {cap:'d11', f:'¿Quién coronó a Carlomagno como emperador en la Navidad del año 800?', r:'El papa León III'},
  {cap:'d11', f:'¿Qué evento de 1798 se asocia con el fin de los 1.260 años de predominio papal?', r:'La captura del papa Pío VI por tropas francesas'},
  {cap:'d11', f:'¿Qué invento de 1455 multiplicó la difusión de la Biblia?', r:'La imprenta de tipos móviles de Johannes Gutenberg'},
  {cap:'d11', f:'¿Qué evento de 1789-1798 le dio al papado la "herida de muerte" que cierra los 1.260 años?', r:'La Revolución Francesa'},
  {cap:'d11', f:'¿A quién identifica la lectura histórica con "el amado de las mujeres" de Daniel 11:37?', r:'Al Mesías, el Redentor que toda mujer de Israel esperaba dar a luz'},
  {cap:'d11', f:'¿En qué año se declaró el dogma de la infalibilidad papal?', r:'1870, y fue reafirmado por el Concilio Vaticano II en 1964'},
  {cap:'d1', f:'¿Cuántos utensilios del templo terminó reuniendo Nabucodonosor?', r:'5.469, en tres viajes a Jerusalén'},
  {cap:'d1', f:'¿Qué significa el nombre "Daniel"?', r:'"Dios es mi juez"'},
  {cap:'d1', f:'¿Qué profeta, activo en Jerusalén cuando Daniel era niño, pudo haber sido su maestro?', r:'Jeremías'},
  {cap:'d2', f:'¿En qué venida de Cristo cae la Piedra de Daniel 2 sobre la estatua?', r:'En la segunda venida, todavía futura; en la primera estableció el "reino de la gracia"'},
  {cap:'d2', f:'¿Qué fenómeno astronómico deja fuera de lugar los signos del zodiaco moderno?', r:'La precesión de los equinoccios, desde los tiempos de Claudio Tolomeo (siglo II)'},
  {cap:'d2', f:'Menciona dos gobernantes que intentaron reunificar Europa, contradiciendo sin éxito Daniel 2:43', r:'Carlomagno y Napoleón (también Carlos V y Hitler)'},
  {cap:'d3', f:'¿Qué significa la frase "y si no" de Sadrac, Mesac y Abed-nego (3:17-18)?', r:'Que obedecerían a Dios sin importar si los libraba del horno o no'},
  {cap:'d3', f:'¿Qué soldado cristiano de la Segunda Guerra Mundial rescató a 75 heridos sin portar armas, en las barrancas de Maeda?', r:'Desmond Doss, único no combatiente condecorado con la Medalla de Honor del Congreso'},
  {cap:'d4', f:'¿Qué otros dos profetas servían al mismo tiempo que Daniel?', r:'Jeremías (en Judá y Egipto) y Ezequiel (junto al canal de Kebar, cerca de Babilonia)'},
  {cap:'d4', f:'¿Cuál es el límite práctico de la obediencia al Estado, según el ejemplo de Daniel?', r:'Se obedece hasta el punto donde una orden choca con un mandamiento explícito de Dios'},
  {cap:'d5', f:'¿Qué oficial arrojó al Éufrates la profecía de Jeremías atada a una piedra?', r:'Seraías, décadas antes de que Babilonia cayera'},
  {cap:'d5', f:'¿Qué emperador murió en Babilonia intentando reconstruirla como su capital?', r:'Alejandro Magno, en 323 a.C.'},
  {cap:'d5', f:'¿Por qué era Baltasar más culpable que Nabucodonosor, según Daniel 5:22?', r:'Sabía todo lo que le había pasado a Nabucodonosor y aun así no humilló su corazón'},
  {cap:'d6', f:'¿Cuántos años tenía Daniel aproximadamente cuando lo arrojaron al foso de los leones?', r:'Unos 84 años'},
  {cap:'d6', f:'¿Qué visión ya había recibido Daniel, años antes de esa noche en el foso, que explica su confianza?', r:'La visión de Daniel 7, con la promesa de que Dios derrota poderes mucho peores que un león'},
  {cap:'d7', f:'¿Qué figura eclesiástica ya llamaba "anticristo" al papado en el año 991, siglos antes de la Reforma?', r:'Arnulfo, obispo de Orleans, en un concilio francés'},
  {cap:'d7', f:'En el orden real del juicio de Daniel 7, ¿qué pasaje queda fuera de secuencia, como un paréntesis?', r:'Daniel 7:11-12, la destrucción de la bestia'},
  {cap:'d7', f:'¿Qué dos funciones cumple Cristo a la vez en el juicio celestial?', r:'Es Juez (Juan le delegó todo el juicio) y Abogado/Mediador de su pueblo (1 Juan 2:1; Hebreos 7:25)'},
  {cap:'d7', f:'¿Cuántos mártires cristianos calcula el historiador W. H. C. Frend bajo toda la Roma pagana (31-313 d.C.)?', r:'Cerca de cinco mil'},
  {cap:'d7', f:'¿Qué conflicto religioso del siglo XVII, entre cristianos, dejó más víctimas que toda la persecución de Roma pagana?', r:'La Guerra de los Treinta Años (1618-1648), más de ocho millones de víctimas'},
  {cap:'d8', f:'¿Qué arma de tecnología avanzada usó Alejandro Magno en sus batallas?', r:'La artillería de torsión: catapultas capaces de lanzar piedras de 26 kilos con gran precisión'},
  {cap:'d8', f:'¿Qué hizo el rey Darío III en cada una de sus tres derrotas frente a Alejandro?', r:'Perdió el ánimo, dio la vuelta y huyó, arrastrando la moral de todo su ejército'},
  {cap:'d8', f:'¿Con qué texto ilustra Maxwell el control de Dios sobre el corazón de los reyes?', r:'Proverbios 21:1: "el corazón del rey es como el agua del canal en mano de Yahvéh"'},
  {cap:'d8', f:'¿Cómo cumplió Alejandro la "vida prolongada durante un tiempo" de Daniel 7:12?', r:'Se casó con la princesa Roxana y promovió el matrimonio de diez mil soldados griegos con mujeres persas, fusionando las culturas'},
  {cap:'d9', f:'¿Qué tres pasajes del Antiguo Testamento había leído Daniel antes de su oración del capítulo 9?', r:'Levítico 26, la oración de Salomón (1 Reyes 8:46-53) y la carta de Jeremías a los exiliados (Jeremías 29)'},
  {cap:'d9', f:'¿Qué significa literalmente la palabra hebrea "jathak", traducida "fijadas" en Daniel 9:24?', r:'"Cortar" o "amputar"'},
  {cap:'d9', f:'¿Por qué el sentido de "cortar/amputar" de jathak prueba que los 2.300 días de Daniel 8:14 son simbólicos?', r:'Porque no se pueden "cortar" 490 años literales de solo 2.300 días literales (menos de 7 años)'},
  {cap:'d10', f:'¿Qué le dijo a Josué el "jefe del ejército de Yahvéh" antes del ataque a Jericó?', r:'Que se quitara las sandalias, porque el lugar donde estaba era sagrado (Josué 5:13-15)'},
  {cap:'d10', f:'¿Cómo se llama, en Éxodo 3, al mismo Ser que se identifica como "YO SOY EL QUE SOY"?', r:'"El Ángel de Yahvéh" (Éxodo 3:2), aunque es el propio Dios quien habla'},
  {cap:'d10', f:'¿Qué vio el siervo de Eliseo en Dotán cuando Dios le abrió los ojos?', r:'El monte lleno de caballos y carros de fuego alrededor de Eliseo (2 Reyes 6)'},
  {cap:'d10', f:'¿Qué frase de Eliseo resume la protección angélica invisible, la misma idea detrás de la guerra de Daniel 10?', r:'"No temas, que hay más con nosotros que con ellos"'},
  {cap:'d11', f:'¿Qué objeto famoso, hoy en el Museo Británico, ilustra el cumplimiento de Daniel 11:14?', r:'La Piedra Rosetta, con las concesiones del niño-rey Ptolomeo V a los egipcios rebelados'},
  {cap:'d12', f:'¿Qué dos anabautistas del siglo XVI cita Maxwell como ejemplo de los "doctos" de Daniel 12:3?', r:'Oswald Glait y Andreas Fischer, ejecutados por guardar el sábado bíblico tras estudiar Daniel 7:25'});

module.exports = { TARJETAS };
