# -*- coding: utf-8 -*-
MAPA = {}

MAPA['d1'] = {
1:'Tercer año del reinado de Joacim, rey de Judá: Nabucodonosor viene a Jerusalén y la sitia.',
2:'El Señor entrega a Joacim y parte de los utensilios de la casa de Dios. Los lleva a tierra de Sinar, a la casa del tesoro de su dios.',
3:'El rey manda a Aspenaz, jefe de los eunucos, traer jóvenes del linaje real de los príncipes.',
4:'Los seis requisitos: sin tacha, de buen parecer, instruidos en toda sabiduría, sabios en ciencia, de buen entendimiento, idóneos para el palacio. Les enseñarían las letras y la lengua de los caldeos.',
5:'Porción diaria de la comida y del vino del rey, y tres años de educación antes de presentarse.',
6:'Los cuatro de Judá: Daniel, Ananías, Misael y Azarías.',
7:'Los nombres nuevos: Daniel→Beltsasar, Ananías→Sadrac, Misael→Mesac, Azarías→Abed-nego.',
8:'Daniel «propuso en su corazón» no contaminarse, y lo pide, no lo exige.',
9:'Dios pone a Daniel en gracia y buena voluntad con el jefe de los eunucos.',
10:'El jefe teme: si el rey los ve más pálidos, lo condena a muerte a él.',
11:'Daniel acude a Melsar, el sirviente puesto sobre los cuatro.',
12:'La propuesta: diez días de prueba, legumbres para comer y agua para beber.',
13:'Que después compare los rostros y haga según vea.',
14:'Melsar consiente y prueba con ellos diez días.',
15:'A los diez días su rostro pareció «mejor y más robusto» que el de los otros.',
16:'Melsar se lleva la porción y el vino, y les da legumbres.',
17:'Dios da a los cuatro conocimiento e inteligencia en letras y ciencias; y a Daniel, además, entendimiento en toda visión y sueños.',
18:'Pasados los días, el jefe de los eunucos los lleva ante Nabucodonosor.',
19:'El rey habla con ellos y no halla otros como los cuatro; quedan a su servicio.',
20:'En todo asunto de sabiduría e inteligencia los halló diez veces mejores que todos los magos y astrólogos del reino.',
21:'Daniel continuó hasta el año primero del rey Ciro.',
}

MAPA['d2'] = {
1:'Segundo año del reinado de Nabucodonosor: tiene sueños, se turba su espíritu y se le va el sueño.',
2:'Llama a cuatro clases de sabios: magos, astrólogos, encantadores y caldeos.',
3:'El rey les dice que tuvo un sueño y que su espíritu está turbado por saberlo.',
4:'Los caldeos hablan en lengua aramea: «¡Rey, para siempre vive!». Piden que cuente el sueño.',
5:'La amenaza: si no dicen el sueño y su interpretación, serán hechos pedazos y sus casas convertidas en estercoleros.',
6:'La promesa opuesta: dones, favores y gran honra si lo dicen.',
7:'Los sabios insisten por segunda vez en que el rey cuente el sueño.',
8:'El rey los acusa de poner dilaciones.',
9:'Una sola sentencia para todos; dice que preparan «respuesta mentirosa y perversa» mientras pasa el tiempo.',
10:'La confesión de los caldeos: no hay hombre sobre la tierra que pueda declararlo, y ningún rey pidió jamás cosa semejante.',
11:'Solo podrían los dioses, «cuya morada no está entre los hombres».',
12:'El rey, con ira y gran enojo, manda matar a todos los sabios de Babilonia.',
13:'Se publica el edicto y buscan también a Daniel y a sus compañeros.',
14:'Daniel habla «sabia y prudentemente» a Arioc, capitán de la guardia del rey.',
15:'Pregunta la causa de tanta prisa, y Arioc se lo hace saber.',
16:'Daniel entra y pide al rey tiempo, prometiendo la interpretación.',
17:'Va a su casa y se lo cuenta a Ananías, Misael y Azarías.',
18:'Para que pidan misericordias del Dios del cielo sobre este misterio, y no perezcan con los otros sabios.',
19:'El secreto le es revelado a Daniel en visión de noche, y bendice al Dios del cielo.',
20:'Comienza la alabanza: «Sea bendito el nombre de Dios de siglos en siglos, porque suyos son el poder y la sabiduría».',
21:'«Él muda los tiempos y las edades, quita reyes y pone reyes»; da sabiduría a los sabios.',
22:'«Él revela lo profundo y lo escondido»; conoce lo que está en tinieblas y con él mora la luz.',
23:'Da gracias al Dios de sus padres por darle sabiduría y fuerza y revelarle el asunto.',
24:'Daniel pide a Arioc que no mate a los sabios y que lo lleve ante el rey.',
25:'Arioc lo presenta: «He hallado un hombre de los deportados de Judá».',
26:'El rey le pregunta, llamándolo Beltsasar, si podrá darle el sueño y su interpretación.',
27:'Daniel responde que ni sabios, ni astrólogos, ni magos, ni adivinos pueden revelarlo.',
28:'«Pero hay un Dios en los cielos que revela los misterios», y le hizo saber lo que ha de acontecer en los últimos días.',
29:'Al rey le vinieron pensamientos en su cama sobre lo por venir, y el que revela los misterios se lo mostró.',
30:'A Daniel le fue revelado no por tener más sabiduría, sino para que el rey conociera la interpretación.',
31:'La gran imagen: muy grande, de gloria muy sublime, en pie delante del rey, de aspecto terrible.',
32:'Cabeza de oro fino; pecho y brazos de plata; vientre y muslos de bronce.',
33:'Piernas de hierro; pies en parte de hierro y en parte de barro cocido.',
34:'Una piedra se desprende «sin que la cortara mano alguna» e hiere la imagen en los pies.',
35:'Todo queda como tamo de las eras del verano y el viento se lo lleva; la piedra se hace un gran monte que llena toda la tierra.',
36:'«Éste es el sueño»: Daniel pasa a la interpretación.',
37:'Nabucodonosor es «rey de reyes» porque el Dios del cielo le dio reino, poder, fuerza y majestad.',
38:'Le dio dominio sobre todo: «Tú eres aquella cabeza de oro».',
39:'Después de él, otro reino inferior (plata), y luego un tercer reino de bronce que dominará sobre toda la tierra.',
40:'El cuarto reino será fuerte como el hierro y lo desmenuzará todo.',
41:'Los pies y los dedos, de hierro y barro, son un reino dividido con algo de la fuerza del hierro.',
42:'Por eso el reino será «en parte fuerte y en parte frágil».',
43:'Se mezclarán por alianzas humanas, pero no se unirán, como el hierro no se mezcla con el barro.',
44:'«En los días de estos reyes» el Dios del cielo levantará un reino que no será jamás destruido ni dejado a otro pueblo.',
45:'La piedra cortada sin mano del monte confirma lo que ha de acontecer: «el sueño es verdadero, y fiel su interpretación».',
46:'Nabucodonosor se postra sobre su rostro, se humilla ante Daniel y manda ofrecerle presentes e incienso.',
47:'Su confesión: «Ciertamente el Dios vuestro es Dios de dioses, Señor de los reyes y el que revela los misterios».',
48:'Engrandece a Daniel: gobernador de toda la provincia de Babilonia y jefe supremo de todos los sabios.',
49:'A petición de Daniel, Sadrac, Mesac y Abed-nego quedan sobre los negocios de la provincia; Daniel, en la corte del rey.',
}
