# -*- coding: utf-8 -*-
MAPA = {}

MAPA['d3'] = {
1:'La estatua de oro: sesenta codos de altura y seis de anchura, levantada en el campo de Dura, provincia de Babilonia.',
2:'Convoca ocho clases de autoridades: sátrapas, magistrados, capitanes, oidores, tesoreros, consejeros, jueces y todos los gobernadores.',
3:'Se reúnen todos y quedan en pie delante de la estatua.',
4:'El pregonero anuncia en alta voz a «pueblos, naciones y lenguas».',
5:'Los seis instrumentos y «todo instrumento de música»: bocina, flauta, cítara, arpa, salterio y zampoña.',
6:'La pena: quien no se postre, «inmediatamente» será echado en un horno de fuego ardiente.',
7:'Al oír la música, todos los pueblos se postran y adoran.',
8:'Algunos hombres caldeos acusan «maliciosamente» a los judíos.',
9:'Se dirigen al rey con la fórmula: «¡Rey, para siempre vive!».',
10:'Le recuerdan su propia ley.',
11:'Y la pena del horno.',
12:'La acusación nombra a los tres: Sadrac, Mesac y Abed-nego, puestos sobre los negocios de la provincia. Tres cargos: no te han respetado, no adoran a tus dioses, no adoran la estatua.',
13:'Nabucodonosor, con ira y enojo, manda traerlos; los traen al instante.',
14:'Les pregunta si es verdad que no honran a su dios ni adoran la estatua.',
15:'Les da una segunda oportunidad y lanza el desafío: «¿y qué dios será el que os libre de mis manos?».',
16:'La respuesta: «No es necesario que te respondamos sobre este asunto».',
17:'«Nuestro Dios, a quien servimos, puede librarnos del horno... y de tus manos, rey, nos librará».',
18:'El «y si no»: aunque no los libre, no servirán a sus dioses ni adorarán la estatua. Es el versículo de la fe que no depende del resultado.',
19:'El rey se llena de ira, le cambia el aspecto del rostro y manda calentar el horno siete veces más de lo acostumbrado.',
20:'Ordena a hombres «muy vigorosos» de su ejército que los aten.',
21:'Son echados atados con sus mantos, calzados, turbantes y vestidos.',
22:'La llama mata a los hombres que los alzaron, porque la orden era apremiante y el horno estaba muy caliente.',
23:'Los tres caen atados dentro del horno.',
24:'El rey se espanta, se levanta apresuradamente y pregunta a su consejo si no echaron a tres hombres atados.',
25:'«Yo veo cuatro hombres sueltos... y el aspecto del cuarto es semejante a un hijo de los dioses».',
26:'Se acerca a la puerta y los llama «siervos del Dios Altísimo»; los tres salen.',
27:'Los testigos comprueban: el fuego no tuvo poder sobre sus cuerpos, ni un cabello quemado, las ropas intactas, «ni siquiera olor de fuego».',
28:'El rey bendice al Dios de ellos: envió su ángel y libró a los que confiaron en él y entregaron sus cuerpos antes que servir a otro dios.',
29:'Decreta que quien blasfeme contra ese Dios sea descuartizado y su casa convertida en estercolero.',
30:'El rey los engrandece en la provincia de Babilonia.',
}

MAPA['d4'] = {
1:'El capítulo es un decreto del propio rey: «Nabucodonosor, rey, a todos los pueblos, naciones y lenguas... Paz os sea multiplicada».',
2:'Dice que conviene declarar las señales y milagros que el Dios Altísimo hizo con él.',
3:'«Su reino, reino sempiterno; su señorío, de generación en generación».',
4:'Estaba «tranquilo en mi casa, floreciente en mi palacio»: el punto de partida es la prosperidad, no la crisis.',
5:'Un sueño lo espanta y las visiones de su cabeza lo turban.',
6:'Manda llamar a todos los sabios de Babilonia.',
7:'Vienen magos, astrólogos, caldeos y adivinos, y no pueden interpretarlo.',
8:'Entra Daniel, «cuyo nombre es Beltsasar, como el nombre de mi dios», en quien mora «el espíritu de los dioses santos».',
9:'Lo llama «jefe de los magos» y le pide la interpretación.',
10:'El sueño: un árbol en medio de la tierra, de gran altura.',
11:'Crecía y se hacía fuerte; su copa llegaba al cielo y se veía desde todos los confines de la tierra.',
12:'Follaje hermoso, fruto abundante, alimento para todos; bestias a su sombra y aves en sus ramas.',
13:'Desciende del cielo «un vigilante y santo».',
14:'La orden: derribar el árbol, cortar las ramas, quitar el follaje, dispersar el fruto, que huyan bestias y aves.',
15:'Pero la cepa de las raíces queda en la tierra, con atadura de hierro y de bronce, empapada del rocío del cielo.',
16:'«Su corazón de hombre sea cambiado y le sea dado corazón de bestia, y pasen sobre él siete tiempos».',
17:'El propósito: «para que conozcan los vivientes que el Altísimo gobierna el reino de los hombres» y lo da a quien quiere, aun al más humilde.',
18:'El rey pide a Beltsasar la interpretación, porque ninguno de sus sabios pudo.',
19:'Daniel queda atónito casi una hora. El rey lo anima, y Daniel responde: «el sueño sea para tus enemigos».',
20:'Retoma el árbol que crecía y se hacía fuerte.',
21:'Y su follaje, su fruto y los animales que lo habitaban.',
22:'La identificación directa: «tú mismo eres, oh rey».',
23:'Repite la orden del vigilante y los siete tiempos.',
24:'«Ésta es la interpretación... y la sentencia del Altísimo».',
25:'La sentencia: lo echarán de entre los hombres, vivirá con las bestias, comerá hierba como los bueyes, será bañado del rocío, y pasarán siete tiempos hasta que reconozca quién tiene el dominio.',
26:'La cepa dejada significa que el reino le quedará firme «después que reconozcas que es el cielo el que gobierna».',
27:'El consejo de Daniel: redimir sus pecados con justicia y sus iniquidades haciendo misericordias con los oprimidos.',
28:'«Todo esto vino sobre el rey Nabucodonosor»: el aviso no se cumplió de inmediato.',
29:'Al cabo de doce meses, paseando por el palacio real de Babilonia.',
30:'La frase que lo derriba: «¿No es ésta la gran Babilonia que yo edifiqué... con la fuerza de mi poder, y para gloria de mi majestad?».',
31:'Aún estaba la palabra en su boca cuando vino una voz del cielo: «El reino te ha sido quitado».',
32:'Se repite la sentencia de los siete tiempos.',
33:'«En la misma hora» se cumple: comía hierba, su pelo creció como plumas de águila y sus uñas como las de las aves.',
34:'«Al fin del tiempo» alza los ojos al cielo y su razón le es devuelta; bendice al Altísimo.',
35:'«Considerados como nada son los habitantes todos de la tierra»; nadie detiene su mano ni le dice «¿Qué haces?».',
36:'Le son devueltos la razón, la majestad, la dignidad y la grandeza, y le es añadida mayor grandeza.',
37:'El cierre del decreto: alaba al Rey del cielo, «porque todas sus obras son verdaderas y sus caminos justos; y él puede humillar a los que andan con soberbia».',
}
