# -*- coding: utf-8 -*-
MAPA = {}

MAPA['d5'] = {
1:'Belsasar hace un gran banquete a mil de sus príncipes, y bebe vino en presencia de los mil.',
2:'«Con el gusto del vino» manda traer los vasos de oro y plata que Nabucodonosor, su padre, trajo del templo de Jerusalén, para el rey, sus grandes, sus mujeres y sus concubinas.',
3:'Traen los vasos y beben de ellos los cuatro grupos.',
4:'Beben y alaban a los dioses de seis materiales: oro, plata, bronce, hierro, madera y piedra.',
5:'«En aquella misma hora»: los dedos de una mano de hombre escriben delante del candelabro, sobre lo encalado de la pared del palacio real.',
6:'La reacción física del rey: palideció, sus pensamientos lo turbaron, se debilitaron sus caderas y sus rodillas daban la una contra la otra.',
7:'Llama a magos, caldeos y adivinos y ofrece tres premios: púrpura, collar de oro y ser «el tercer señor en el reino».',
8:'Ninguno pudo leer la escritura ni dar la interpretación.',
9:'El rey se turba sobremanera y sus príncipes quedan perplejos.',
10:'Entra la reina, que no estaba en el banquete, y lo calma.',
11:'Recuerda al hombre en quien mora el espíritu de los dioses santos, a quien su padre constituyó jefe sobre magos, astrólogos, caldeos y adivinos.',
12:'Sus tres capacidades: interpretar sueños, descifrar enigmas y resolver dudas. Es Daniel, «al cual el rey puso por nombre Beltsasar».',
13:'Traen a Daniel; el rey le pregunta si es el de los hijos de la cautividad de Judá.',
14:'Reconoce lo que ha oído de él: luz, entendimiento y mayor sabiduría.',
15:'Admite que sabios y astrólogos no pudieron.',
16:'Le repite la oferta de los tres premios.',
17:'La respuesta de Daniel: «Tus dones sean para ti; da tus recompensas a otros». Igual leerá la escritura.',
18:'Empieza por la historia: el Altísimo dio a Nabucodonosor el reino, la grandeza, la gloria y la majestad.',
19:'Tenía poder de vida y muerte: mataba, daba vida, engrandecía y humillaba a quien le placía.',
20:'Pero al ensoberbecerse fue depuesto del trono y despojado de su gloria.',
21:'Vivió con los asnos monteses, comió hierba, se empapó del rocío, hasta reconocer que el Altísimo tiene dominio.',
22:'La acusación a Belsasar: «no has humillado tu corazón sabiendo todo esto».',
23:'Se ensoberbeció contra el Señor del cielo, usó los vasos de su Casa y alabó dioses «que ni ven ni oyen ni saben»; nunca honró al Dios «en cuya mano está tu vida».',
24:'Por eso Dios envió la mano que trazó la escritura.',
25:'La escritura: «Mene, Mene, Tekel, Uparsin».',
26:'«Mene»: Contó Dios tu reino y le ha puesto fin.',
27:'«Tekel»: Pesado has sido en balanza y hallado falto.',
28:'«Peres»: Tu reino ha sido roto y dado a los medos y a los persas.',
29:'Belsasar cumple lo prometido: púrpura, collar de oro y tercer señor del reino.',
30:'«La misma noche» fue muerto Belsasar, rey de los caldeos.',
31:'Darío de Media toma el reino a los sesenta y dos años.',
}

MAPA['d6'] = {
1:'Darío constituye ciento veinte sátrapas sobre el reino.',
2:'Y sobre ellos tres gobernadores, uno de los cuales era Daniel, para que el rey no fuera perjudicado.',
3:'Daniel era superior a todos «porque había en él un espíritu superior», y el rey pensó ponerlo sobre todo el reino.',
4:'Buscaron ocasión para acusarlo y no hallaron motivo ni falta, «porque él era fiel».',
5:'La conclusión de los enemigos: solo lo hallarán «en relación con la ley de su Dios».',
6:'Se juntan delante del rey con la fórmula: «¡Rey Darío, para siempre vive!».',
7:'La mentira: dicen que TODOS acordaron. El edicto: treinta días sin pedir a ningún dios u hombre fuera del rey, so pena del foso de los leones.',
8:'Le piden firmarlo para que no pueda ser revocado, «conforme a la ley de Media y de Persia».',
9:'Darío firma el edicto y la prohibición.',
10:'Daniel, sabiendo que estaba firmado, entra en su casa, con las ventanas abiertas hacia Jerusalén, y se arrodilla tres veces al día «como solía hacerlo antes». No cambió nada.',
11:'Los hombres se juntan y lo hallan orando y rogando.',
12:'Van ante el rey y primero le hacen confirmar el edicto, antes de acusar.',
13:'Entonces acusan: Daniel, «de los hijos de los cautivos de Judá», no respeta al rey y pide tres veces al día.',
14:'Al rey le pesa en gran manera y trabaja hasta la puesta del sol por librarlo.',
15:'Los hombres lo rodean y le recuerdan que la ley no puede ser abrogada.',
16:'Echan a Daniel al foso. El rey le dice: «El Dios tuyo, a quien tú continuamente sirves, él te libre».',
17:'Una piedra sobre la puerta, sellada con el anillo del rey y con el de sus príncipes.',
18:'El rey se acuesta en ayunas, sin instrumentos musicales, y se le va el sueño.',
19:'Se levanta muy de mañana y va apresuradamente al foso.',
20:'Llama «con voz triste»: «Daniel, siervo del Dios viviente... ¿te ha podido librar de los leones?».',
21:'Daniel responde: «¡Rey, vive para siempre!».',
22:'«Mi Dios envió su ángel, el cual cerró la boca de los leones»; fue hallado inocente ante Dios y ante el rey.',
23:'Sacan a Daniel sin ninguna lesión, «porque había confiado en su Dios».',
24:'Los acusadores, con sus hijos y mujeres, son echados al foso; los leones se apoderan de ellos antes de llegar al fondo.',
25:'Darío escribe a todos los pueblos, naciones y lenguas: «Paz os sea multiplicada».',
26:'Ordena que teman ante el Dios de Daniel, «porque él es el Dios viviente y permanece por todos los siglos».',
27:'«Él salva y libra, y hace señales y maravillas en el cielo y en la tierra».',
28:'Daniel prosperó durante los reinados de Darío y de Ciro, el persa.',
}
