# -*- coding: utf-8 -*-
MAPA = {}

MAPA['d7'] = {
1:'Primer año de Belsasar: Daniel tiene un sueño y visiones, lo escribe y relata «lo principal del asunto».',
2:'Los cuatro vientos del cielo combaten en el gran mar. Vientos = conflicto; mar = pueblos.',
3:'Cuatro bestias grandes, diferentes entre sí, suben del mar.',
4:'Primera: león con alas de águila. Le arrancan las alas, la levantan sobre los pies «a manera de hombre» y se le da corazón de hombre. Es Babilonia.',
5:'Segunda: semejante a un oso, alzada de un costado más que del otro, con tres costillas entre los dientes. «Levántate y devora mucha carne». Es Media-Persia.',
6:'Tercera: leopardo con cuatro alas de ave y cuatro cabezas; «le fue dado dominio». Es Grecia.',
7:'Cuarta: espantosa, terrible y en gran manera fuerte, con grandes dientes de hierro; devoraba, desmenuzaba y pisoteaba. Diferente de todas y con diez cuernos. Es Roma.',
8:'Entre los diez sale un cuerno pequeño; delante de él son arrancados tres. Tiene ojos como de hombre y una boca «que hablaba con gran insolencia».',
9:'La escena del juicio: tronos puestos y el Anciano de días sentado. Vestido blanco como la nieve, pelo como lana limpia, trono llama de fuego, ruedas de fuego ardiente.',
10:'Un río de fuego; «miles de miles lo servían, y millones de millones estaban delante de él». El Juez se sentó y los libros fueron abiertos.',
11:'Por las grandes insolencias del cuerno, matan a la bestia y su cuerpo es entregado al fuego.',
12:'A las otras bestias les quitan el dominio, pero les prolongan la vida «hasta cierto tiempo».',
13:'«Con las nubes del cielo venía uno como un hijo de hombre»; viene hasta el Anciano de días.',
14:'Le es dado dominio, gloria y reino; su dominio es eterno y su reino nunca será destruido.',
15:'A Daniel se le turba el espíritu «hasta lo más hondo de mi ser».',
16:'Se acerca a uno de los presentes y pregunta la verdad; recibe la interpretación.',
17:'«Estas cuatro grandes bestias son cuatro reyes que se levantarán en la tierra».',
18:'«Después recibirán el reino los santos del Altísimo... eternamente y para siempre».',
19:'Daniel quiere saber sobre la cuarta bestia: dientes de hierro y uñas de bronce.',
20:'Y sobre los diez cuernos y el otro ante el cual cayeron tres, que «parecía más grande que sus compañeros».',
21:'«Este cuerno hacía guerra contra los santos y los vencía».',
22:'Hasta que vino el Anciano de días, se hizo justicia a los santos y recibieron el reino.',
23:'La cuarta bestia es un cuarto reino, diferente de todos, que «a toda la tierra devorará, trillará y despedazará».',
24:'Los diez cuernos son diez reyes; tras ellos se levanta otro, diferente, «y derribará a tres reyes».',
25:'Las cuatro marcas del cuerno pequeño: hablará palabras contra el Altísimo, quebrantará a los santos, pensará en cambiar los tiempos y la Ley, y los tendrá en sus manos «hasta tiempo, tiempos y medio tiempo».',
26:'Se sentará el Juez y le quitarán su dominio, «para que sea destruido y arruinado hasta el fin».',
27:'El reino, el dominio y la majestad son dados al pueblo de los santos del Altísimo; su reino es eterno.',
28:'«Aquí fue el fin de sus palabras». Daniel se turba y su rostro se demuda, pero guarda el asunto en su corazón.',
}

MAPA['d8'] = {
1:'Año tercero de Belsasar: la segunda visión de Daniel, «después de aquella que había tenido antes» (la de Daniel 7).',
2:'El lugar: Susa, capital del reino, en la provincia de Elam, junto al río Ulai.',
3:'El carnero de dos cuernos: los dos altos, pero uno más alto que el otro, y «el más alto creció después».',
4:'Hiere hacia el poniente, el norte y el sur. Ninguna bestia podía pararse delante de él; hacía conforme a su voluntad y se engrandecía.',
5:'Un macho cabrío viene del poniente «sobre la faz de toda la tierra, sin tocar tierra», con un cuerno notable entre los ojos. La velocidad es el dato.',
6:'Corre contra el carnero «con la furia de su fuerza».',
7:'Lo hiere, le quiebra los dos cuernos, lo derriba y lo pisotea; nadie lo libra.',
8:'En su mayor fuerza el gran cuerno es quebrado y salen cuatro cuernos notables «hacia los cuatro vientos del cielo».',
9:'De uno de ellos sale un cuerno pequeño que crece mucho hacia el sur, el oriente y «la tierra gloriosa».',
10:'Crece hasta el ejército del cielo y echa por tierra parte del ejército y de las estrellas, y las pisotea.',
11:'Se engrandece frente al príncipe de los ejércitos; por él es quitado el sacrificio continuo (el tamid) y el lugar de su santuario es echado por tierra.',
12:'A causa de la prevaricación le es entregado el ejército junto con el sacrificio continuo; «echó por tierra la verdad e hizo cuanto quiso, y prosperó».',
13:'La pregunta de los dos santos: «¿Hasta cuándo durará la visión del sacrificio continuo, la prevaricación asoladora y la entrega del santuario y el ejército para ser pisoteados?».',
14:'La respuesta, el versículo eje del adventismo: «Hasta dos mil trescientas tardes y mañanas; luego el santuario será purificado».',
15:'Mientras procura comprenderla, se pone delante de él «uno con apariencia de hombre».',
16:'Una voz entre las riberas del Ulai ordena: «Gabriel, enseña a éste la visión». Es la primera vez que se nombra a Gabriel en la Biblia.',
17:'Daniel se asusta y se postra. «Entiende, hijo de hombre, que la visión es para el tiempo del fin».',
18:'Cae dormido en tierra sobre su rostro; Gabriel lo toca y lo hace estar en pie.',
19:'«Yo te enseñaré lo que ha de venir al fin de la ira; porque eso es para el tiempo del fin».',
20:'El carnero de dos cuernos: «los reyes de Media y de Persia». La interpretación la da el propio ángel.',
21:'El macho cabrío es «el rey de Grecia», y el cuerno grande «es el rey primero».',
22:'Los cuatro que suceden al cuerno quebrado: cuatro reinos de esa nación, «aunque no con la fuerza de él».',
23:'Al fin del reinado de estos, «cuando los transgresores lleguen al colmo», se levanta un rey «altivo de rostro y entendido en enigmas».',
24:'Su poder se fortalece «mas no con fuerza propia»; causa grandes ruinas y destruye a los fuertes y al pueblo de los santos.',
25:'Hace prosperar el engaño, se engrandece en su corazón y «sin aviso» destruye a muchos. Se levanta contra el Príncipe de los príncipes, «pero será quebrantado, aunque no por mano humana».',
26:'«La visión de las tardes y mañanas... es verdadera; y tú guarda la visión, porque es para muchos días».',
27:'Daniel queda quebrantado y enfermo algunos días; atendió los negocios del rey «pero estaba espantado a causa de la visión, y no la entendía». Queda sin explicar el versículo 14, y eso enlaza con Daniel 9.',
}
