# -*- coding: utf-8 -*-
MAPA = {}

MAPA['d9'] = {
1:'Primer año de Darío hijo de Asuero, de la nación de los medos, rey sobre el reino de los caldeos.',
2:'Daniel «miró atentamente en los libros» el número de años que Jehová habló a Jeremías: setenta años de desolación de Jerusalén. La profecía se estudia, no se adivina.',
3:'Vuelve su rostro a Dios con cuatro señales de humillación: oración y ruego, ayuno, ropas ásperas y ceniza.',
4:'Abre la confesión reconociendo al Dios «que guardas el pacto y la misericordia».',
5:'Cinco verbos en primera persona del plural: hemos pecado, cometido iniquidad, actuado impíamente, sido rebeldes, nos hemos apartado. Daniel se incluye.',
6:'No obedecieron a los profetas, que hablaron a reyes, príncipes, padres y a todo el pueblo.',
7:'«Tuya es, Señor, la justicia, y nuestra la confusión de rostro».',
8:'Repite la confusión de rostro: del pueblo, los reyes, los príncipes y los padres.',
9:'«De Jehová, nuestro Dios, es el tener misericordia y el perdonar».',
10:'No obedecieron la voz de Jehová ni anduvieron en sus leyes.',
11:'Todo Israel traspasó la Ley, y por eso cayó la maldición «escrita en la ley de Moisés».',
12:'Dios cumplió su palabra: «nunca fue hecho debajo del cielo nada semejante a lo que se ha hecho contra Jerusalén».',
13:'Vino todo el mal y aun así «no hemos implorado el favor de Jehová».',
14:'«Justo es Jehová, nuestro Dios, en todas sus obras»; el problema no fue de Dios.',
15:'Apela al éxodo: el Dios que sacó a su pueblo de Egipto «con mano poderosa».',
16:'Pide que se aparte su ira de Jerusalén, «tu santo monte».',
17:'«Haz que tu rostro resplandezca sobre tu santuario asolado». El santuario es el centro del ruego, y por eso la respuesta habla del santuario.',
18:'No ruega confiado en sus justicias «sino en tus muchas misericordias».',
19:'El clímax: «¡Oye, Señor! ¡Señor, perdona! ¡Presta oído, Señor, y hazlo! No tardes».',
20:'Aún estaba hablando, orando y confesando su pecado y el de su pueblo.',
21:'Llega Gabriel, «a quien había visto en la visión, al principio» (la de Daniel 8), volando con presteza, «como a la hora del sacrificio de la tarde».',
22:'«Daniel, ahora he salido para darte sabiduría y entendimiento».',
23:'«Al principio de tus ruegos fue dada la orden... porque tú eres muy amado. Entiende, pues, la orden, y entiende la visión». Viene a terminar de explicar Daniel 8.',
24:'«Setenta semanas están determinadas sobre tu pueblo y sobre tu santa ciudad». Seis propósitos: terminar la prevaricación, poner fin al pecado, expiar la iniquidad, traer la justicia perdurable, sellar la visión y la profecía, y ungir al Santo de los santos.',
25:'El punto de partida: «desde la salida de la orden para restaurar y edificar a Jerusalén hasta el Mesías Príncipe, habrá siete semanas y sesenta y dos semanas» (69 en total). Se reedificarían la plaza y el muro «en tiempos angustiosos».',
26:'Después de las sesenta y dos semanas «se quitará la vida al Mesías, y nada ya le quedará». El pueblo de un príncipe destruirá la ciudad y el santuario.',
27:'La semana setenta: «confirmará el pacto con muchos; a la mitad de la semana hará cesar el sacrificio y la ofrenda».',
}

MAPA['d10'] = {
1:'Tercer año de Ciro, rey de Persia. «La palabra era verdadera y el conflicto grande», y Daniel comprendió.',
2:'Daniel estuvo afligido «por espacio de tres semanas».',
3:'El ayuno: sin manjar delicado, sin carne ni vino, sin ungirse con perfume, hasta cumplir las tres semanas.',
4:'El día veinticuatro del primer mes, a la orilla del gran río Hidekel (el Tigris).',
5:'Un varón vestido de lino, ceñida su cintura «con oro de Ufaz».',
6:'La descripción en cinco rasgos: cuerpo como de berilo, rostro como un relámpago, ojos como antorchas de fuego, brazos y pies como bronce bruñido, y voz «como el estruendo de una multitud».',
7:'Solo Daniel vio la visión; los que estaban con él huyeron y se escondieron por un gran temor.',
8:'Quedó solo y sin fuerzas: «mis fuerzas se cambiaron en desfallecimiento».',
9:'Al oír el sonido de las palabras cayó sobre su rostro «en un profundo sueño».',
10:'Una mano lo toca y lo pone sobre sus rodillas y las palmas de sus manos.',
11:'«Daniel, varón muy amado»: la primera de las tres veces que se lo llaman en el libro. Se pone en pie temblando.',
12:'«No temas, porque desde el primer día que dispusiste tu corazón a entender y a humillarte... fueron oídas tus palabras». La respuesta salió el día uno, no el veintiuno.',
13:'«El príncipe del reino de Persia se me opuso durante veintiún días; pero Miguel, uno de los principales príncipes, vino para ayudarme». Los 21 días de retraso coinciden con las 3 semanas de ayuno.',
14:'Vino «para hacerte saber lo que ha de sucederle a tu pueblo en los últimos días».',
15:'Daniel tenía los ojos puestos en tierra y había enmudecido.',
16:'«Uno con semejanza de hijo de hombre» le toca los labios y entonces puede hablar.',
17:'Pregunta cómo podrá hablar el siervo con su señor: «me faltaron las fuerzas, y no me quedó aliento».',
18:'Lo toca otra vez y lo fortalece: es la segunda vez que lo tocan para sostenerlo.',
19:'«Muy amado, no temas; la paz sea contigo; esfuérzate y cobra aliento». Daniel recobra las fuerzas.',
20:'«Ahora tengo que volver para pelear contra el príncipe de Persia; al terminar con él, el príncipe de Grecia vendrá».',
21:'«Yo te declararé lo que está escrito en el libro de la verdad: nadie me ayuda contra ellos, sino Miguel vuestro príncipe».',
}

MAPA['d12'] = {
1:'«En aquel tiempo se levantará Miguel, el gran príncipe que está de parte de los hijos de tu pueblo». Tiempo de angustia «cual nunca fue»; será libertado todo el que se halle inscrito en el libro.',
2:'La resurrección: «muchos de los que duermen en el polvo de la tierra serán despertados», unos para vida eterna y otros para vergüenza y confusión perpetua.',
3:'«Los entendidos resplandecerán como el resplandor del firmamento; y los que enseñan la justicia a la multitud, como las estrellas, a perpetua eternidad».',
4:'«Cierra las palabras y sella el libro hasta el tiempo del fin. Muchos correrán de aquí para allá, y la ciencia aumentará».',
5:'Daniel ve a otros dos en pie, uno a cada lado del río.',
6:'La pregunta: «¿Cuándo será el fin de estas maravillas?».',
7:'El varón vestido de lino alza LAS DOS manos al cielo y jura por el que vive por los siglos: «por tiempo, tiempos y la mitad de un tiempo». Se cumplirá cuando se acabe la dispersión del poder del pueblo santo.',
8:'«Yo oí, pero no entendí»: Daniel pregunta cuál será el fin de estas cosas.',
9:'«Anda, Daniel, pues estas palabras están cerradas y selladas hasta el tiempo del fin».',
10:'«Muchos serán limpios, emblanquecidos y purificados... ninguno de los impíos entenderá; pero los entendidos comprenderán».',
11:'Los mil doscientos noventa días, desde que sea quitado el sacrificio continuo hasta la abominación desoladora.',
12:'«Bienaventurado el que espere, y llegue a mil trescientos treinta y cinco días».',
13:'La promesa personal a Daniel: «tú irás hasta el fin, y reposarás, y te levantarás para recibir tu heredad al fin de los días».',
}
