# -*- coding: utf-8 -*-
MAPA = {}

MAPA['d11'] = {
1:'«También yo en el primer año de Darío, el medo, estuve para animarlo y fortalecerlo». Habla todavía el ángel de Daniel 10.',
2:'«Aún habrá tres reyes en Persia, y el cuarto se hará de grandes riquezas». Ese cuarto levantará a todos contra Grecia.',
3:'«Se levantará luego un rey valiente, que dominará con gran poder y hará su voluntad»: Alejandro Magno.',
4:'Su reino será quebrantado y repartido «hacia los cuatro vientos del cielo», pero no para sus descendientes.',
5:'El rey del sur se hará fuerte, pero uno de sus príncipes será más fuerte que él.',
6:'La alianza por matrimonio: la hija del rey del sur va al rey del norte «para hacer la paz», y acaba entregada a la muerte junto con los que la trajeron.',
7:'«Un renuevo de sus raíces» se levanta, entra en la fortaleza del norte y predomina.',
8:'Se lleva cautivos a Egipto los dioses, las imágenes fundidas y los objetos de plata y oro.',
9:'«Así entrará en el reino el rey del sur, y volverá a su tierra».',
10:'Los hijos del rey del norte reúnen grandes ejércitos; uno viene, «inundará y pasará adelante».',
11:'El rey del sur se enfurece y pelea; la multitud del norte le es entregada.',
12:'Al llevarse la multitud «se elevará su corazón» y derribará a muchos millares, «pero no prevalecerá». La soberbia le quita la victoria.',
13:'El rey del norte vuelve con una multitud mayor, «al cabo de algunos años», con gran ejército y muchas riquezas.',
14:'«Hombres turbulentos de tu pueblo se levantarán, para que se cumpla la visión, pero caerán».',
15:'El rey del norte levanta baluartes y toma la ciudad fuerte; las fuerzas del sur no pueden sostenerse.',
16:'El que viene «hará su propia voluntad» y permanecerá en la tierra gloriosa, «que será consumida bajo su poder».',
17:'Hace convenios y da «una hija por mujer, para destruirlo»; pero no permanecerá ni tendrá éxito.',
18:'Vuelve su rostro a las costas y toma muchas, «pero un príncipe le hará cesar en su afrenta».',
19:'Vuelve a las fortalezas de su tierra: «tropezará y caerá, y no será hallado».',
20:'En su lugar se levanta uno que hace pasar «un cobrador de tributos por la gloria del reino»; muere en pocos días, «aunque no con ira ni en batalla».',
21:'«Ocupará su lugar un hombre despreciable, al cual no darán la honra del reino. Vendrá sin aviso y tomará el reino con halagos».',
22:'Las fuerzas enemigas son barridas «como por inundación de aguas», junto con «el príncipe del pacto».',
23:'«Él, después del pacto, engañará, subirá y saldrá vencedor con poca gente». Crece por acuerdo, no por batalla.',
24:'Entra estando la provincia en paz y hace lo que no hicieron sus padres: reparte botín, despojos y riquezas. «Esto durará un tiempo».',
25:'Despierta sus fuerzas contra el rey del sur, que no prevalece «porque le harán traición».',
26:'«Aun los que coman de sus manjares lo quebrantarán»: la traición viene de la propia mesa.',
27:'Los dos reyes, «sentados a una misma mesa, se mentirán el uno al otro; pero no servirá de nada, porque el plazo aún no habrá llegado».',
28:'Vuelve con gran riqueza y «pondrá su corazón contra el pacto santo».',
29:'«Al tiempo señalado volverá al sur; pero la última venida no será como la primera».',
30:'«Vendrán contra él naves de Quitim»; se contrista, retrocede, se enoja contra el pacto santo y se entiende «con los que abandonen el santo pacto».',
31:'Sus tropas profanan el santuario y la fortaleza, «quitarán el sacrificio continuo y pondrán la abominación desoladora». Es la frase que Jesús cita en Mateo 24:15.',
32:'«Con lisonjas seducirá a los violadores del pacto; pero el pueblo que conoce a su Dios se esforzará y actuará».',
33:'«Los sabios del pueblo instruirán a muchos», pero caerán a espada y a fuego, en cautividad y despojo.',
34:'«En su caída serán ayudados con un pequeño socorro, y muchos se juntarán a ellos con lisonjas».',
35:'Algunos de los sabios caen «para ser depurados, limpiados y emblanquecidos, hasta el tiempo determinado».',
36:'«El rey hará su voluntad, se ensoberbecerá y se engrandecerá sobre todo dios»; hablará maravillas contra el Dios de los dioses y prosperará «hasta que sea consumada la ira».',
37:'No hará caso del Dios de sus padres, «ni del amor de las mujeres», ni respetará a dios alguno.',
38:'«Honrará en su lugar al dios de las fortalezas, un dios que sus padres no conocieron», con oro, plata y piedras preciosas.',
39:'Con un dios ajeno se hará de las fortalezas, colmará de honores a los que lo reconozcan y «repartirá tierras como recompensa».',
40:'«Al cabo del tiempo»: el rey del sur contiende con él y el rey del norte se levanta «como una tempestad», con carros, gente de a caballo y muchas naves.',
41:'Entra en la tierra gloriosa y muchas provincias caen; escapan «Edom, Moab y la mayoría de los hijos de Amón».',
42:'Extiende su mano contra las tierras y «no escapará el país de Egipto».',
43:'Se apodera de los tesoros de oro y plata de Egipto; libios y etíopes lo siguen.',
44:'«Noticias del oriente y del norte lo atemorizarán», y saldrá con gran ira.',
45:'Planta las tiendas de su palacio «entre los mares y el monte glorioso y santo; pero llegará a su fin, y no tendrá quien lo ayude».',
}
