#!/bin/sh
if git diff --cached --name-only --diff-filter=ACM | grep -E '\.(html|js|css|json)$' | xargs -r awk 'length($0) > 2000 { print FILENAME": línea "FNR" tiene "length($0)" caracteres"; found=1 } END { exit found }'; then
  exit 0
else
  echo "✗ Hay líneas de más de 2000 caracteres. Ningún visor de diff las abre."
  exit 1
fi
